; generated by baz

section .data
align 4

section .bss
align 4
stk resd 1024
stk.end:

section .text
align 4
bits 64
global _start
_start:
mov rsp,stk.end
mov rbp,rsp
jmp main

main:
;  [8:5] var a=-2 
;  a: qword[rbp-8]
;  [8:9] a=-2 
;  [8:11] -2 
;  [8:12] a=-2 
   mov qword[rbp-8],-2
;  [9:5] var b=-a 
;  b: qword[rbp-16]
;  [9:9] b=-a 
;  [9:11] -a 
;  [9:12] b=-a 
;  alloc r15
   mov r15,qword[rbp-8]
   mov qword[rbp-16],r15
;  free r15
   neg qword[rbp-16]
   if_11_8:
;  [11:8] ? not a=-1 or not b=-a 
;  [11:8] ? not a=-1 
   cmp_11_8:
   cmp qword[rbp-8],-1
   jne if_11_8_code
;  [11:20] ? not b=-a 
   cmp_11_20:
;  alloc r15
   mov r15,qword[rbp-8]
   neg r15
   cmp qword[rbp-16],r15
;  free r15
   je if_11_5_end
   if_11_8_code:  ; opt1
;    [11:29] exit(1)
;    exit(v:reg_rdi) 
;      inline: 11_29
;      alloc rdi
;      alias v -> rdi
       mov rdi,1
;      [2:5] mov(rax,60)
       mov rax,60
;      [2:17] # exit system call 
;      [3:5] mov(rdi,v)
;      [3:17] # return code 
;      [4:5] syscall 
       syscall
;      free rdi
     exit_11_29_end:
   if_11_5_end:
   if_12_8:
;  [12:13] ? not (a=-1 and b=-a)
;  [12:13] ? a=-1 
   cmp_12_13:
   cmp qword[rbp-8],-1
   jne if_12_5_end
;  [12:22] ? b=-a
   cmp_12_22:
;  alloc r15
   mov r15,qword[rbp-8]
   neg r15
   cmp qword[rbp-16],r15
;  free r15
   jne if_12_5_end
   if_12_8_code:  ; opt1
;    [12:28] exit(1)
;    exit(v:reg_rdi) 
;      inline: 12_28
;      alloc rdi
;      alias v -> rdi
       mov rdi,1
;      [2:5] mov(rax,60)
       mov rax,60
;      [2:17] # exit system call 
;      [3:5] mov(rdi,v)
;      [3:17] # return code 
;      [4:5] syscall 
       syscall
;      free rdi
     exit_12_28_end:
   if_12_5_end:
;  [14:5] exit(0)
;  exit(v:reg_rdi) 
;    inline: 14_5
;    alloc rdi
;    alias v -> rdi
     mov rdi,0
;    [2:5] mov(rax,60)
     mov rax,60
;    [2:17] # exit system call 
;    [3:5] mov(rdi,v)
;    [3:17] # return code 
;    [4:5] syscall 
     syscall
;    free rdi
   exit_14_5_end:

; max scratch registers in use: 1
;            max frames in use: 5

