;
; generated by baz
;

default rel

%macro PUSH_REGS 0
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15
%endmacro

%macro POP_REGS 0
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
%endmacro

section .text
bits 64
global _start
_start:

; allocate named register rbp
lea rbp, [dat]

;[7:1] point : 16 B    fields:
;[7:1]       name :  offset :    size :  array? : array size
;[7:1]          x :       0 :       8 :      no :           
;[7:1]          y :       8 :       8 :      no :           
;
;[9:1] object : 24 B    fields:
;[9:1]       name :  offset :    size :  array? : array size
;[9:1]        pos :       0 :      16 :      no :           
;[9:1]      color :      16 :       4 :      no :           
;
;[11:1] world : 64 B    fields:
;[11:1]       name :  offset :    size :  array? : array size
;[11:1]  locations :       0 :      64 :     yes :          8
;
;[13:1] str : 128 B    fields:
;[13:1]       name :  offset :    size :  array? : array size
;[13:1]        len :       0 :       1 :      no :           
;[13:1]       data :       1 :     127 :     yes :        127
;
;[20:1] dat hello[] i8 = "hello world from baz\n"
;[20:7] hello: i8[21] (21 B @ [rbp])
;[21:1] dat prompt1[] i8 = "enter name:\n"
;[21:5] prompt1: i8[12] (12 B @ [rbp + 21])
;[22:1] dat prompt2[] i8 = "that is not a name.\n"
;[22:5] prompt2: i8[20] (20 B @ [rbp + 33])
;[23:1] dat prompt3[] i8 = "hello "
;[23:5] prompt3: i8[6] (6 B @ [rbp + 53])
;[24:1] dat dot[] i8 = "."
;[24:9] dot: i8[1] (1 B @ [rbp + 59])
;[25:1] dat nl[] i8 = "\n"
;[25:10] nl: i8[1] (1 B @ [rbp + 60])
;[26:1] dat colon[] i8 = ": "
;[26:7] colon: i8[2] (2 B @ [rbp + 61])
;[27:1] dat nums[4] = { 1 }
;[27:8] nums: i64[4] (32 B @ [rbp + 64])
;[28:1] dat str1 str = { 3 }
;[28:8] str1: str (128 B @ [rbp + 96])
;[98:7] const yes = 1
;[99:7] const no = 0
;[100:7] const maybe = -1
;
main:
;   [151:5] var arr[4] i32
;   [151:9] arr: i32[4] (16 B @ [rbp + 224])
;   [151:9] zero 4 * 4 B = 16 B
;   [151:5] size <= 32 B, use mov
    mov qword [rbp + 224], 0
    mov qword [rbp + 232], 0
;   [154:5] var answer
;   [154:9] answer: i64 (8 B @ [rbp + 240])
;   [154:9] zero 1 * 8 B = 8 B
;   [154:5] size <= 32 B, use mov
    mov qword [rbp + 240], 0
;   [155:5] assert(answer == 0)
;   [155:12] allocate scratch register -> r15
;   [155:12] ? answer == 0
;   [155:12] ? answer == 0
    cmp.155.12:
    cmp qword [rbp + 240], 0
    sete r15b
    bool.155.12.end:
;   [32:6] assert(ok bool)
    func.assert.155.5:
;       [155:5] alias ok -> r15b
        if.32.27.155.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.155.5:
        cmp r15b, 0
        jne if.32.24.155.5.end
        if.32.27.155.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.155.5.end:
;       [155:5] free scratch register r15
    func.assert.155.5.end:
;   [158:5] answer = maybe
;   [158:14] maybe
    mov qword [rbp + 240], -1
;   [159:5] assert(answer == -1)
;   [159:12] allocate scratch register -> r15
;   [159:12] ? answer == -1
;   [159:12] ? answer == -1
    cmp.159.12:
    cmp qword [rbp + 240], -1
    sete r15b
    bool.159.12.end:
;   [32:6] assert(ok bool)
    func.assert.159.5:
;       [159:5] alias ok -> r15b
        if.32.27.159.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.159.5:
        cmp r15b, 0
        jne if.32.24.159.5.end
        if.32.27.159.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.159.5.end:
;       [159:5] free scratch register r15
    func.assert.159.5.end:
;       [164:15] const maybe = 33
;       [165:9] assert(maybe == 33)
;       [165:16] allocate scratch register -> r15
;       [165:16] ? maybe == 33
;       [165:16] ? maybe == 33
        cmp.165.16:
;       [165:16] const eval to true
        bool.165.16.end:
        mov r15b, 1
;       [32:6] assert(ok bool)
        func.assert.165.9:
;           [165:9] alias ok -> r15b
            if.32.27.165.9:
;           [32:27] ? not ok
;           [32:27] ? not ok
            cmp.32.27.165.9:
            cmp r15b, 0
            jne if.32.24.165.9.end
            if.32.27.165.9.code:
;               [32:34] exit(1)
;               [32:34] allocate named register rdi
;               [32:39] 1
                mov rdi, 1
                mov rax, 60
                syscall
;               [32:34] free named register rdi
            if.32.24.165.9.end:
;           [165:9] free scratch register r15
        func.assert.165.9.end:
;   [168:5] assert(maybe == -1)
;   [168:12] allocate scratch register -> r15
;   [168:12] ? maybe == -1
;   [168:12] ? maybe == -1
    cmp.168.12:
;   [168:12] const eval to true
    bool.168.12.end:
    mov r15b, 1
;   [32:6] assert(ok bool)
    func.assert.168.5:
;       [168:5] alias ok -> r15b
        if.32.27.168.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.168.5:
        cmp r15b, 0
        jne if.32.24.168.5.end
        if.32.27.168.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.168.5.end:
;       [168:5] free scratch register r15
    func.assert.168.5.end:
;   [170:5] var ix = 1
;   [170:9] ix: i64 (8 B @ [rbp + 248])
;   [170:9] ix = 1
;   [170:14] 1
    mov qword [rbp + 248], 1
;   [173:5] arr[ix] = 2
;   [173:9] allocate scratch register -> r15
;   [173:9] set array index
;   [173:9] ix
    mov r15, qword [rbp + 248]
;   [173:15] 2
    mov dword [rbp + r15 * 4 + 224], 2
;   [173:5] free scratch register r15
;   [174:5] arr[ix + 1] = arr[ix]
;   [174:9] allocate scratch register -> r15
;   [174:9] set array index
;   [174:9] ix
    mov r15, qword [rbp + 248]
;   [174:14] r15 + 1
    add r15, 1
;   [174:19] arr[ix]
;   [174:23] allocate scratch register -> r14
;   [174:23] set array index
;   [174:23] ix
    mov r14, qword [rbp + 248]
;   [174:19] allocate scratch register -> r13
    mov r13d, dword [rbp + r14 * 4 + 224]
    mov dword [rbp + r15 * 4 + 224], r13d
;   [174:19] free scratch register r13
;   [174:19] free scratch register r14
;   [174:5] free scratch register r15
;   [175:5] assert(arr[1] == 2)
;   [175:12] allocate scratch register -> r15
;   [175:12] ? arr[1] == 2
;   [175:12] ? arr[1] == 2
    cmp.175.12:
;   [175:16] allocate scratch register -> r14
;   [175:16] set array index
;   [175:16] 1
    mov r14, 1
    cmp dword [rbp + r14 * 4 + 224], 2
;   [175:12] free scratch register r14
    sete r15b
    bool.175.12.end:
;   [32:6] assert(ok bool)
    func.assert.175.5:
;       [175:5] alias ok -> r15b
        if.32.27.175.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.175.5:
        cmp r15b, 0
        jne if.32.24.175.5.end
        if.32.27.175.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.175.5.end:
;       [175:5] free scratch register r15
    func.assert.175.5.end:
;   [176:5] assert(arr[2] == 2)
;   [176:12] allocate scratch register -> r15
;   [176:12] ? arr[2] == 2
;   [176:12] ? arr[2] == 2
    cmp.176.12:
;   [176:16] allocate scratch register -> r14
;   [176:16] set array index
;   [176:16] 2
    mov r14, 2
    cmp dword [rbp + r14 * 4 + 224], 2
;   [176:12] free scratch register r14
    sete r15b
    bool.176.12.end:
;   [32:6] assert(ok bool)
    func.assert.176.5:
;       [176:5] alias ok -> r15b
        if.32.27.176.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.176.5:
        cmp r15b, 0
        jne if.32.24.176.5.end
        if.32.27.176.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.176.5.end:
;       [176:5] free scratch register r15
    func.assert.176.5.end:
;   [178:5] array_copy(arr[2], arr, 2)
;   [178:16] arr[2]
;   [178:20] allocate scratch register -> r15
;   [178:20] set array index
;   [178:20] 2
    mov r15, 2
;   [178:24] arr
;   [178:5] size <= 16 B, use mov
;   [178:5] allocate named register rax
    mov rax, qword [rbp + r15 * 4 + 224]
    mov qword [rbp + 224], rax
;   [178:5] free named register rax
;   [178:5] free scratch register r15
;   [179:5] assert(arr[0] == 2)
;   [179:12] allocate scratch register -> r15
;   [179:12] ? arr[0] == 2
;   [179:12] ? arr[0] == 2
    cmp.179.12:
;   [179:16] allocate scratch register -> r14
;   [179:16] set array index
;   [179:16] 0
    mov r14, 0
    cmp dword [rbp + r14 * 4 + 224], 2
;   [179:12] free scratch register r14
    sete r15b
    bool.179.12.end:
;   [32:6] assert(ok bool)
    func.assert.179.5:
;       [179:5] alias ok -> r15b
        if.32.27.179.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.179.5:
        cmp r15b, 0
        jne if.32.24.179.5.end
        if.32.27.179.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.179.5.end:
;       [179:5] free scratch register r15
    func.assert.179.5.end:
;   [182:5] var arr1[8] i32
;   [182:9] arr1: i32[8] (32 B @ [rbp + 256])
;   [182:9] zero 8 * 4 B = 32 B
;   [182:5] size <= 32 B, use mov
    mov qword [rbp + 256], 0
    mov qword [rbp + 264], 0
    mov qword [rbp + 272], 0
    mov qword [rbp + 280], 0
;   [183:5] array_copy(arr, arr1, 4)
;   [183:16] arr
;   [183:21] arr1
;   [183:5] size <= 16 B, use mov
;   [183:5] allocate named register rax
    mov rax, qword [rbp + 224]
    mov qword [rbp + 256], rax
    mov rax, qword [rbp + 232]
    mov qword [rbp + 264], rax
;   [183:5] free named register rax
;   [184:5] var eq bool = arrays_equal(arr[1], arr1[1], 3)
;   [184:9] eq: bool (1 B @ [rbp + 288])
;   [184:9] eq = arrays_equal(arr[1], arr1[1], 3)
;   [184:19] ? arrays_equal(arr[1], arr1[1], 3)
;   [184:19] ? arrays_equal(arr[1], arr1[1], 3)
    cmp.184.19:
;       [184:19] arrays_equal(arr[1], arr1[1], 3)
;       [184:19] allocate named register rsi
;       [184:19] allocate named register rdi
;       [184:19] allocate named register rcx
;       [184:49] 3
;       [184:49] 3
        mov rcx, 3
;       [184:32] arr[1]
;       [184:36] allocate scratch register -> r15
;       [184:36] set array index
;       [184:36] 1
        mov r15, 1
        lea rsi, [rbp + r15 * 4 + 224]
;       [184:19] free scratch register r15
;       [184:40] arr1[1]
;       [184:45] allocate scratch register -> r15
;       [184:45] set array index
;       [184:45] 1
        mov r15, 1
        lea rdi, [rbp + r15 * 4 + 256]
;       [184:19] free scratch register r15
        shl rcx, 2
        test rcx, rcx
        repe cmpsb
;       [184:19] free named register rcx
;       [184:19] free named register rdi
;       [184:19] free named register rsi
        sete byte [rbp + 288]
    bool.184.19.end:
;   [187:5] assert(eq)
;   [187:12] allocate scratch register -> r15
;   [187:12] ? eq
;   [187:12] ? eq
    cmp.187.12:
    cmp byte [rbp + 288], 0
    setne r15b
    bool.187.12.end:
;   [32:6] assert(ok bool)
    func.assert.187.5:
;       [187:5] alias ok -> r15b
        if.32.27.187.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.187.5:
        cmp r15b, 0
        jne if.32.24.187.5.end
        if.32.27.187.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.187.5.end:
;       [187:5] free scratch register r15
    func.assert.187.5.end:
;   [189:5] arr1[2] = -1
;   [189:10] allocate scratch register -> r15
;   [189:10] set array index
;   [189:10] 2
    mov r15, 2
;   [189:16] -1
    mov dword [rbp + r15 * 4 + 256], -1
;   [189:5] free scratch register r15
;   [190:5] assert(not arrays_equal(arr, arr1, 4))
;   [190:12] allocate scratch register -> r15
;   [190:12] ? not arrays_equal(arr, arr1, 4)
;   [190:12] ? not arrays_equal(arr, arr1, 4)
    cmp.190.12:
;       [190:16] arrays_equal(arr, arr1, 4)
;       [190:16] allocate named register rsi
;       [190:16] allocate named register rdi
;       [190:16] allocate named register rcx
;       [190:40] 4
;       [190:40] 4
        mov rcx, 4
;       [190:29] arr
        lea rsi, [rbp + 224]
;       [190:34] arr1
        lea rdi, [rbp + 256]
        shl rcx, 2
        test rcx, rcx
        repe cmpsb
;       [190:16] free named register rcx
;       [190:16] free named register rdi
;       [190:16] free named register rsi
        setne r15b
    bool.190.12.end:
;   [32:6] assert(ok bool)
    func.assert.190.5:
;       [190:5] alias ok -> r15b
        if.32.27.190.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.190.5:
        cmp r15b, 0
        jne if.32.24.190.5.end
        if.32.27.190.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.190.5.end:
;       [190:5] free scratch register r15
    func.assert.190.5.end:
;   [192:5] ix = 3
;   [192:10] 3
    mov qword [rbp + 248], 3
;   [193:5] arr[ix] = ~inv(arr[ix - 1])
;   [193:9] allocate scratch register -> r15
;   [193:9] set array index
;   [193:9] ix
    mov r15, qword [rbp + 248]
;   [193:16] arr = ~inv(arr[ix - 1])
;   [193:16] = expression
;   [193:16] ~inv(arr[ix - 1])
;   [193:24] allocate scratch register -> r14
;   [193:24] set array index
;   [193:24] ix
    mov r14, qword [rbp + 248]
;   [193:29] r14 - 1
    sub r14, 1
;   [62:6] inv(i i32) res i32
    func.inv.193.16:
;       [193:16] alias res -> arr (lea: rbp + r15 * 4 + 224)
;       [193:16] alias i -> arr (lea: rbp + r14 * 4 + 224)
;       [63:5] res = ~i
;       [63:12] ~i
;       [63:12] allocate scratch register -> r13
        mov r13d, dword [rbp + r14 * 4 + 224]
        mov dword [rbp + r15 * 4 + 224], r13d
;       [63:12] free scratch register r13
        not dword [rbp + r15 * 4 + 224]
;       [193:16] free scratch register r14
    func.inv.193.16.end:
    not dword [rbp + r15 * 4 + 224]
;   [193:5] free scratch register r15
;   [194:5] assert(arr[ix] == 2)
;   [194:12] allocate scratch register -> r15
;   [194:12] ? arr[ix] == 2
;   [194:12] ? arr[ix] == 2
    cmp.194.12:
;   [194:16] allocate scratch register -> r14
;   [194:16] set array index
;   [194:16] ix
    mov r14, qword [rbp + 248]
    cmp dword [rbp + r14 * 4 + 224], 2
;   [194:12] free scratch register r14
    sete r15b
    bool.194.12.end:
;   [32:6] assert(ok bool)
    func.assert.194.5:
;       [194:5] alias ok -> r15b
        if.32.27.194.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.194.5:
        cmp r15b, 0
        jne if.32.24.194.5.end
        if.32.27.194.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.194.5.end:
;       [194:5] free scratch register r15
    func.assert.194.5.end:
;   [196:5] faz(arr)
;   [72:6] faz(arg[] i32)
    func.faz.196.5:
;       [196:5] alias arg -> arr
;       [73:5] arg[1] = 0xfe
;       [73:9] allocate scratch register -> r15
;       [73:9] set array index
;       [73:9] 1
        mov r15, 1
;       [73:14] 0xfe
        mov dword [rbp + r15 * 4 + 224], 254
;       [73:5] free scratch register r15
    func.faz.196.5.end:
;   [197:5] assert(arr[1] == 0xfe)
;   [197:12] allocate scratch register -> r15
;   [197:12] ? arr[1] == 0xfe
;   [197:12] ? arr[1] == 0xfe
    cmp.197.12:
;   [197:16] allocate scratch register -> r14
;   [197:16] set array index
;   [197:16] 1
    mov r14, 1
    cmp dword [rbp + r14 * 4 + 224], 254
;   [197:12] free scratch register r14
    sete r15b
    bool.197.12.end:
;   [32:6] assert(ok bool)
    func.assert.197.5:
;       [197:5] alias ok -> r15b
        if.32.27.197.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.197.5:
        cmp r15b, 0
        jne if.32.24.197.5.end
        if.32.27.197.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.197.5.end:
;       [197:5] free scratch register r15
    func.assert.197.5.end:
;   [199:5] var arr3[] = { 3, 5 }
;   [199:9] arr3: i64[2] (16 B @ [rbp + 296])
;   [199:9] arr3= { 3, 5 }
;   [199:18] size <= 16 B, use immediates
    mov dword [rbp + 296], 3
    mov dword [rbp + 300], 0
    mov dword [rbp + 304], 5
    mov dword [rbp + 308], 0
;   [200:5] foo arr3
;   [200:9] allocate scratch register -> r15
;   [200:9] e: i64 (r15)
;   [200:9] i: i64 (8 B @ [rbp + 320])
;   [200:9] const n = 2
;   [200:9] initiate iterator e
    lea r15, [rbp + 296]
;   [200:9] initiate counter i
    mov qword [rbp + 320], 0
    foo.200.5:
;       [201:9] e = e + i + n
;       [201:13] instructions without scratch register 3, with 4
;       [201:13] e
;       [201:17] e + i
;       [201:17] allocate scratch register -> r14
        mov r14, qword [rbp + 320]
        add qword [r15], r14
;       [201:17] free scratch register r14
;       [201:21] e + n
        add qword [r15], 2
        foo.200.5.continue:
            add r15, 8
            inc qword [rbp + 320]
            cmp qword [rbp + 320], 2
            jne foo.200.5
    foo.200.5.end:
;   [200:5] free scratch register r15
;   [203:5] assert(arr3[0] == 3 + 0 + 2)
;   [203:12] allocate scratch register -> r15
;   [203:12] ? arr3[0] == 3 + 0 + 2
;   [203:12] ? arr3[0] == 3 + 0 + 2
    cmp.203.12:
;   [203:17] allocate scratch register -> r14
;   [203:17] set array index
;   [203:17] 0
    mov r14, 0
;   [203:23] allocate scratch register -> r13
;       [203:23] 3
        mov r13, 3
;       [203:27] r13 + 0
        add r13, 0
;       [203:31] r13 + 2
        add r13, 2
    cmp qword [rbp + r14 * 8 + 296], r13
;   [203:12] free scratch register r13
;   [203:12] free scratch register r14
    sete r15b
    bool.203.12.end:
;   [32:6] assert(ok bool)
    func.assert.203.5:
;       [203:5] alias ok -> r15b
        if.32.27.203.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.203.5:
        cmp r15b, 0
        jne if.32.24.203.5.end
        if.32.27.203.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.203.5.end:
;       [203:5] free scratch register r15
    func.assert.203.5.end:
;   [204:5] assert(arr3[1] == 5 + 1 + 2)
;   [204:12] allocate scratch register -> r15
;   [204:12] ? arr3[1] == 5 + 1 + 2
;   [204:12] ? arr3[1] == 5 + 1 + 2
    cmp.204.12:
;   [204:17] allocate scratch register -> r14
;   [204:17] set array index
;   [204:17] 1
    mov r14, 1
;   [204:23] allocate scratch register -> r13
;       [204:23] 5
        mov r13, 5
;       [204:27] r13 + 1
        add r13, 1
;       [204:31] r13 + 2
        add r13, 2
    cmp qword [rbp + r14 * 8 + 296], r13
;   [204:12] free scratch register r13
;   [204:12] free scratch register r14
    sete r15b
    bool.204.12.end:
;   [32:6] assert(ok bool)
    func.assert.204.5:
;       [204:5] alias ok -> r15b
        if.32.27.204.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.204.5:
        cmp r15b, 0
        jne if.32.24.204.5.end
        if.32.27.204.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.204.5.end:
;       [204:5] free scratch register r15
    func.assert.204.5.end:
;   [210:5] var p point = {0, 0}
;   [210:9] p: point (16 B @ [rbp + 312])
;   [210:9] p = {0, 0}
;   [210:20] copy field 'x'
    mov qword [rbp + 312], 0
;   [210:23] copy field 'y'
    mov qword [rbp + 320], 0
;   [211:7] p.fooz()
;   [46:6] point.fooz()
    func.point.fooz.211.7:
;       [211:7] alias self -> p
;       [47:5] self.x = 0b10
;       [47:14] 0b10
        mov qword [rbp + 312], 2
;       [48:5] self.y = 0xb
;       [48:14] 0xb
        mov qword [rbp + 320], 11
    func.point.fooz.211.7.end:
;   [212:5] assert(p.x == 2)
;   [212:12] allocate scratch register -> r15
;   [212:12] ? p.x == 2
;   [212:12] ? p.x == 2
    cmp.212.12:
    cmp qword [rbp + 312], 2
    sete r15b
    bool.212.12.end:
;   [32:6] assert(ok bool)
    func.assert.212.5:
;       [212:5] alias ok -> r15b
        if.32.27.212.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.212.5:
        cmp r15b, 0
        jne if.32.24.212.5.end
        if.32.27.212.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.212.5.end:
;       [212:5] free scratch register r15
    func.assert.212.5.end:
;   [213:5] assert(p.y == 0xb)
;   [213:12] allocate scratch register -> r15
;   [213:12] ? p.y == 0xb
;   [213:12] ? p.y == 0xb
    cmp.213.12:
    cmp qword [rbp + 320], 11
    sete r15b
    bool.213.12.end:
;   [32:6] assert(ok bool)
    func.assert.213.5:
;       [213:5] alias ok -> r15b
        if.32.27.213.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.213.5:
        cmp r15b, 0
        jne if.32.24.213.5.end
        if.32.27.213.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.213.5.end:
;       [213:5] free scratch register r15
    func.assert.213.5.end:
;   [215:5] var q point = p
;   [215:9] q: point (16 B @ [rbp + 328])
;   [215:9] q = p
;   [215:19] size <= 16 B, use mov
;   [215:19] allocate named register rax
    mov rax, qword [rbp + 312]
    mov qword [rbp + 328], rax
    mov rax, qword [rbp + 320]
    mov qword [rbp + 336], rax
;   [215:19] free named register rax
;   [216:5] assert(equal(p, q))
;   [216:12] allocate scratch register -> r15
;   [216:12] ? equal(p, q)
;   [216:12] ? equal(p, q)
    cmp.216.12:
;       [216:12] equal(p, q)
;       [216:12] allocate named register rsi
;       [216:12] allocate named register rdi
;       [216:12] allocate named register rcx
;       [216:18] p
        lea rsi, [rbp + 312]
;       [216:21] q
        lea rdi, [rbp + 328]
        mov rcx, 2
        repe cmpsq
;       [216:12] free named register rcx
;       [216:12] free named register rdi
;       [216:12] free named register rsi
        sete r15b
    bool.216.12.end:
;   [32:6] assert(ok bool)
    func.assert.216.5:
;       [216:5] alias ok -> r15b
        if.32.27.216.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.216.5:
        cmp r15b, 0
        jne if.32.24.216.5.end
        if.32.27.216.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.216.5.end:
;       [216:5] free scratch register r15
    func.assert.216.5.end:
;   [220:5] q.x = 3
;   [220:11] 3
    mov qword [rbp + 328], 3
;   [221:5] assert(not equal(p, q))
;   [221:12] allocate scratch register -> r15
;   [221:12] ? not equal(p, q)
;   [221:12] ? not equal(p, q)
    cmp.221.12:
;       [221:16] equal(p, q)
;       [221:16] allocate named register rsi
;       [221:16] allocate named register rdi
;       [221:16] allocate named register rcx
;       [221:22] p
        lea rsi, [rbp + 312]
;       [221:25] q
        lea rdi, [rbp + 328]
        mov rcx, 2
        repe cmpsq
;       [221:16] free named register rcx
;       [221:16] free named register rdi
;       [221:16] free named register rsi
        setne r15b
    bool.221.12.end:
;   [32:6] assert(ok bool)
    func.assert.221.5:
;       [221:5] alias ok -> r15b
        if.32.27.221.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.221.5:
        cmp r15b, 0
        jne if.32.24.221.5.end
        if.32.27.221.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.221.5.end:
;       [221:5] free scratch register r15
    func.assert.221.5.end:
;   [223:5] var i = 0
;   [223:9] i: i64 (8 B @ [rbp + 344])
;   [223:9] i = 0
;   [223:13] 0
    mov qword [rbp + 344], 0
;   [224:5] bar(i)
;   [54:6] bar(arg)
    func.bar.224.5:
;       [224:5] alias arg -> i
        if.55.8.224.5:
;       [55:8] ? arg == 0
;       [55:8] ? arg == 0
        cmp.55.8.224.5:
        cmp qword [rbp + 344], 0
        jne if.55.5.224.5.end
        if.55.8.224.5.code:
;           [55:17] return
            jmp func.bar.224.5.end
        if.55.5.224.5.end:
;       [56:5] arg = 0xff
;       [56:11] 0xff
        mov qword [rbp + 344], 255
    func.bar.224.5.end:
;   [225:5] assert(i == 0)
;   [225:12] allocate scratch register -> r15
;   [225:12] ? i == 0
;   [225:12] ? i == 0
    cmp.225.12:
    cmp qword [rbp + 344], 0
    sete r15b
    bool.225.12.end:
;   [32:6] assert(ok bool)
    func.assert.225.5:
;       [225:5] alias ok -> r15b
        if.32.27.225.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.225.5:
        cmp r15b, 0
        jne if.32.24.225.5.end
        if.32.27.225.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.225.5.end:
;       [225:5] free scratch register r15
    func.assert.225.5.end:
;   [227:5] i = 1
;   [227:9] 1
    mov qword [rbp + 344], 1
;   [228:5] bar(i)
;   [54:6] bar(arg)
    func.bar.228.5:
;       [228:5] alias arg -> i
        if.55.8.228.5:
;       [55:8] ? arg == 0
;       [55:8] ? arg == 0
        cmp.55.8.228.5:
        cmp qword [rbp + 344], 0
        jne if.55.5.228.5.end
        if.55.8.228.5.code:
;           [55:17] return
            jmp func.bar.228.5.end
        if.55.5.228.5.end:
;       [56:5] arg = 0xff
;       [56:11] 0xff
        mov qword [rbp + 344], 255
    func.bar.228.5.end:
;   [229:5] assert(i == 0xff)
;   [229:12] allocate scratch register -> r15
;   [229:12] ? i == 0xff
;   [229:12] ? i == 0xff
    cmp.229.12:
    cmp qword [rbp + 344], 255
    sete r15b
    bool.229.12.end:
;   [32:6] assert(ok bool)
    func.assert.229.5:
;       [229:5] alias ok -> r15b
        if.32.27.229.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.229.5:
        cmp r15b, 0
        jne if.32.24.229.5.end
        if.32.27.229.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.229.5.end:
;       [229:5] free scratch register r15
    func.assert.229.5.end:
;   [231:5] var j = 1
;   [231:9] j: i64 (8 B @ [rbp + 352])
;   [231:9] j = 1
;   [231:13] 1
    mov qword [rbp + 352], 1
;   [232:5] var k = baz(j)
;   [232:9] k: i64 (8 B @ [rbp + 360])
;   [232:9] k = baz(j)
;   [232:13] k = baz(j)
;   [232:13] = expression
;   [232:13] baz(j)
;   [66:6] baz(arg) res
    func.baz.232.13:
;       [232:13] alias res -> k
;       [232:13] alias arg -> j
;       [67:5] res = arg * 2
;       [67:11] instructions without scratch register 3, with 3
;       [67:11] arg
;       [67:11] allocate scratch register -> r15
        mov r15, qword [rbp + 352]
        mov qword [rbp + 360], r15
;       [67:11] free scratch register r15
;       [67:17] res * 2
;       [67:17] dst is not reg, src is const
        sal qword [rbp + 360], 1
    func.baz.232.13.end:
;   [233:5] assert(k == 2)
;   [233:12] allocate scratch register -> r15
;   [233:12] ? k == 2
;   [233:12] ? k == 2
    cmp.233.12:
    cmp qword [rbp + 360], 2
    sete r15b
    bool.233.12.end:
;   [32:6] assert(ok bool)
    func.assert.233.5:
;       [233:5] alias ok -> r15b
        if.32.27.233.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.233.5:
        cmp r15b, 0
        jne if.32.24.233.5.end
        if.32.27.233.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.233.5.end:
;       [233:5] free scratch register r15
    func.assert.233.5.end:
;   [235:5] k = baz(1)
;   [235:9] k = baz(1)
;   [235:9] = expression
;   [235:9] baz(1)
;   [66:6] baz(arg) res
    func.baz.235.9:
;       [235:9] alias res -> k
;       [235:9] alias arg -> 1
;       [67:5] res = arg * 2
;       [67:11] instructions without scratch register 2, with 3
;       [67:11] arg
        mov qword [rbp + 360], 1
;       [67:17] res * 2
;       [67:17] dst is not reg, src is const
        sal qword [rbp + 360], 1
    func.baz.235.9.end:
;   [236:5] assert(k == 2)
;   [236:12] allocate scratch register -> r15
;   [236:12] ? k == 2
;   [236:12] ? k == 2
    cmp.236.12:
    cmp qword [rbp + 360], 2
    sete r15b
    bool.236.12.end:
;   [32:6] assert(ok bool)
    func.assert.236.5:
;       [236:5] alias ok -> r15b
        if.32.27.236.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.236.5:
        cmp r15b, 0
        jne if.32.24.236.5.end
        if.32.27.236.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.236.5.end:
;       [236:5] free scratch register r15
    func.assert.236.5.end:
;   [238:5] var p0 point = {baz(3), 0}
;   [238:9] p0: point (16 B @ [rbp + 368])
;   [238:9] p0 = {baz(3), 0}
;   [238:21] copy field 'x'
;   [238:21] p0.x = baz(3)
;   [238:21] = expression
;   [238:21] baz(3)
;   [66:6] baz(arg) res
    func.baz.238.21:
;       [238:21] alias res -> p0.x (lea: rbp + 368)
;       [238:21] alias arg -> 3
;       [67:5] res = arg * 2
;       [67:11] instructions without scratch register 2, with 3
;       [67:11] arg
        mov qword [rbp + 368], 3
;       [67:17] res * 2
;       [67:17] dst is not reg, src is const
        sal qword [rbp + 368], 1
    func.baz.238.21.end:
;   [238:29] copy field 'y'
    mov qword [rbp + 376], 0
;   [239:5] assert(p0.x == 6)
;   [239:12] allocate scratch register -> r15
;   [239:12] ? p0.x == 6
;   [239:12] ? p0.x == 6
    cmp.239.12:
    cmp qword [rbp + 368], 6
    sete r15b
    bool.239.12.end:
;   [32:6] assert(ok bool)
    func.assert.239.5:
;       [239:5] alias ok -> r15b
        if.32.27.239.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.239.5:
        cmp r15b, 0
        jne if.32.24.239.5.end
        if.32.27.239.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.239.5.end:
;       [239:5] free scratch register r15
    func.assert.239.5.end:
;   [241:5] var pt point = point_init()
;   [241:9] pt: point (16 B @ [rbp + 384])
;   [241:9] pt = point_init()
;   [241:20] point_init()
;   [87:6] point_init() res point
    func.point_init.241.20:
;       [241:20] alias res -> pt
;       [88:5] res.x = -1
;       [88:14] -1
        mov qword [rbp + 384], -1
;       [89:5] res.y = -2
;       [89:14] -2
        mov qword [rbp + 392], -2
    func.point_init.241.20.end:
;   [242:5] assert(pt.x == -1)
;   [242:12] allocate scratch register -> r15
;   [242:12] ? pt.x == -1
;   [242:12] ? pt.x == -1
    cmp.242.12:
    cmp qword [rbp + 384], -1
    sete r15b
    bool.242.12.end:
;   [32:6] assert(ok bool)
    func.assert.242.5:
;       [242:5] alias ok -> r15b
        if.32.27.242.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.242.5:
        cmp r15b, 0
        jne if.32.24.242.5.end
        if.32.27.242.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.242.5.end:
;       [242:5] free scratch register r15
    func.assert.242.5.end:
;   [243:5] assert(pt.y == -2)
;   [243:12] allocate scratch register -> r15
;   [243:12] ? pt.y == -2
;   [243:12] ? pt.y == -2
    cmp.243.12:
    cmp qword [rbp + 392], -2
    sete r15b
    bool.243.12.end:
;   [32:6] assert(ok bool)
    func.assert.243.5:
;       [243:5] alias ok -> r15b
        if.32.27.243.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.243.5:
        cmp r15b, 0
        jne if.32.24.243.5.end
        if.32.27.243.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.243.5.end:
;       [243:5] free scratch register r15
    func.assert.243.5.end:
;   [245:5] var x = 1
;   [245:9] x: i64 (8 B @ [rbp + 400])
;   [245:9] x = 1
;   [245:13] 1
    mov qword [rbp + 400], 1
;   [246:5] var y = 2
;   [246:9] y: i64 (8 B @ [rbp + 408])
;   [246:9] y = 2
;   [246:13] 2
    mov qword [rbp + 408], 2
;   [248:5] var o1 object = {{x * 10, y}, 0xff0000}
;   [248:9] o1: object (24 B @ [rbp + 416])
;   [248:9] o1 = {{x * 10, y}, 0xff0000}
;   [248:22] copy field 'pos'
;   [248:23] copy field 'x'
;   [248:23] instructions without scratch register 5, with 3
;   [248:23] allocate scratch register -> r15
;   [248:23] x
    mov r15, qword [rbp + 400]
;   [248:27] r15 * 10
;   [248:27] dst is reg, src is const
    imul r15, 10
    mov qword [rbp + 416], r15
;   [248:23] free scratch register r15
;   [248:31] copy field 'y'
;   [248:31] allocate scratch register -> r15
    mov r15, qword [rbp + 408]
    mov qword [rbp + 424], r15
;   [248:31] free scratch register r15
;   [248:35] copy field 'color'
    mov dword [rbp + 432], 16711680
;   [248:21] zero padding: 4 B
;   [248:21] size <= 32 B, use mov
    mov dword [rbp + 436], 0
;   [249:5] assert(o1.pos.x == 10)
;   [249:12] allocate scratch register -> r15
;   [249:12] ? o1.pos.x == 10
;   [249:12] ? o1.pos.x == 10
    cmp.249.12:
    cmp qword [rbp + 416], 10
    sete r15b
    bool.249.12.end:
;   [32:6] assert(ok bool)
    func.assert.249.5:
;       [249:5] alias ok -> r15b
        if.32.27.249.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.249.5:
        cmp r15b, 0
        jne if.32.24.249.5.end
        if.32.27.249.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.249.5.end:
;       [249:5] free scratch register r15
    func.assert.249.5.end:
;   [250:5] assert(o1.pos.y == 2)
;   [250:12] allocate scratch register -> r15
;   [250:12] ? o1.pos.y == 2
;   [250:12] ? o1.pos.y == 2
    cmp.250.12:
    cmp qword [rbp + 424], 2
    sete r15b
    bool.250.12.end:
;   [32:6] assert(ok bool)
    func.assert.250.5:
;       [250:5] alias ok -> r15b
        if.32.27.250.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.250.5:
        cmp r15b, 0
        jne if.32.24.250.5.end
        if.32.27.250.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.250.5.end:
;       [250:5] free scratch register r15
    func.assert.250.5.end:
;   [251:5] assert(o1.color == 0xff0000)
;   [251:12] allocate scratch register -> r15
;   [251:12] ? o1.color == 0xff0000
;   [251:12] ? o1.color == 0xff0000
    cmp.251.12:
    cmp dword [rbp + 432], 16711680
    sete r15b
    bool.251.12.end:
;   [32:6] assert(ok bool)
    func.assert.251.5:
;       [251:5] alias ok -> r15b
        if.32.27.251.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.251.5:
        cmp r15b, 0
        jne if.32.24.251.5.end
        if.32.27.251.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.251.5.end:
;       [251:5] free scratch register r15
    func.assert.251.5.end:
;   [253:5] var p1 point = {-x, -y}
;   [253:9] p1: point (16 B @ [rbp + 440])
;   [253:9] p1 = {-x, -y}
;   [253:21] copy field 'x'
;   [253:21] allocate scratch register -> r15
    mov r15, qword [rbp + 400]
    mov qword [rbp + 440], r15
;   [253:21] free scratch register r15
    neg qword [rbp + 440]
;   [253:25] copy field 'y'
;   [253:25] allocate scratch register -> r15
    mov r15, qword [rbp + 408]
    mov qword [rbp + 448], r15
;   [253:25] free scratch register r15
    neg qword [rbp + 448]
;   [254:5] o1.pos = p1
;   [254:14] size <= 16 B, use mov
;   [254:14] allocate named register rax
    mov rax, qword [rbp + 440]
    mov qword [rbp + 416], rax
    mov rax, qword [rbp + 448]
    mov qword [rbp + 424], rax
;   [254:14] free named register rax
;   [255:5] assert(o1.pos.x == -1)
;   [255:12] allocate scratch register -> r15
;   [255:12] ? o1.pos.x == -1
;   [255:12] ? o1.pos.x == -1
    cmp.255.12:
    cmp qword [rbp + 416], -1
    sete r15b
    bool.255.12.end:
;   [32:6] assert(ok bool)
    func.assert.255.5:
;       [255:5] alias ok -> r15b
        if.32.27.255.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.255.5:
        cmp r15b, 0
        jne if.32.24.255.5.end
        if.32.27.255.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.255.5.end:
;       [255:5] free scratch register r15
    func.assert.255.5.end:
;   [256:5] assert(o1.pos.y == -2)
;   [256:12] allocate scratch register -> r15
;   [256:12] ? o1.pos.y == -2
;   [256:12] ? o1.pos.y == -2
    cmp.256.12:
    cmp qword [rbp + 424], -2
    sete r15b
    bool.256.12.end:
;   [32:6] assert(ok bool)
    func.assert.256.5:
;       [256:5] alias ok -> r15b
        if.32.27.256.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.256.5:
        cmp r15b, 0
        jne if.32.24.256.5.end
        if.32.27.256.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.256.5.end:
;       [256:5] free scratch register r15
    func.assert.256.5.end:
;   [258:5] var o2 object = o1
;   [258:9] o2: object (24 B @ [rbp + 456])
;   [258:9] o2 = o1
;   [258:21] allocate named register rsi
;   [258:21] allocate named register rdi
;   [258:21] allocate named register rcx
    lea rsi, [rbp + 416]
    lea rdi, [rbp + 456]
    mov rcx, 24
    rep movsb
;   [258:21] free named register rcx
;   [258:21] free named register rdi
;   [258:21] free named register rsi
;   [259:5] assert(o2.pos.x == -1)
;   [259:12] allocate scratch register -> r15
;   [259:12] ? o2.pos.x == -1
;   [259:12] ? o2.pos.x == -1
    cmp.259.12:
    cmp qword [rbp + 456], -1
    sete r15b
    bool.259.12.end:
;   [32:6] assert(ok bool)
    func.assert.259.5:
;       [259:5] alias ok -> r15b
        if.32.27.259.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.259.5:
        cmp r15b, 0
        jne if.32.24.259.5.end
        if.32.27.259.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.259.5.end:
;       [259:5] free scratch register r15
    func.assert.259.5.end:
;   [260:5] assert(o2.pos.y == -2)
;   [260:12] allocate scratch register -> r15
;   [260:12] ? o2.pos.y == -2
;   [260:12] ? o2.pos.y == -2
    cmp.260.12:
    cmp qword [rbp + 464], -2
    sete r15b
    bool.260.12.end:
;   [32:6] assert(ok bool)
    func.assert.260.5:
;       [260:5] alias ok -> r15b
        if.32.27.260.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.260.5:
        cmp r15b, 0
        jne if.32.24.260.5.end
        if.32.27.260.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.260.5.end:
;       [260:5] free scratch register r15
    func.assert.260.5.end:
;   [261:5] assert(o2.color == 0xff0000)
;   [261:12] allocate scratch register -> r15
;   [261:12] ? o2.color == 0xff0000
;   [261:12] ? o2.color == 0xff0000
    cmp.261.12:
    cmp dword [rbp + 472], 16711680
    sete r15b
    bool.261.12.end:
;   [32:6] assert(ok bool)
    func.assert.261.5:
;       [261:5] alias ok -> r15b
        if.32.27.261.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.261.5:
        cmp r15b, 0
        jne if.32.24.261.5.end
        if.32.27.261.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.261.5.end:
;       [261:5] free scratch register r15
    func.assert.261.5.end:
;   [263:5] var o3[2] object
;   [263:9] o3: object[2] (48 B @ [rbp + 480])
;   [263:9] zero 2 * 24 B = 48 B
;   [263:5] allocate named register rax
;   [263:5] allocate named register rdi
;   [263:5] allocate named register rcx
    xor al, al
    lea rdi, [rbp + 480]
    mov rcx, 48
    rep stosb
;   [263:5] free named register rcx
;   [263:5] free named register rdi
;   [263:5] free named register rax
;   [264:5] o3.pos.y = 73
;   [264:16] 73
    mov qword [rbp + 488], 73
;   [267:5] assert(o3[0].pos.y == 73)
;   [267:12] allocate scratch register -> r15
;   [267:12] ? o3[0].pos.y == 73
;   [267:12] ? o3[0].pos.y == 73
    cmp.267.12:
;   [267:15] allocate scratch register -> r14
;   [267:15] set array index
;   [267:15] 0
    mov r14, 0
    imul r14, 24
    cmp qword [rbp + r14 + 488], 73
;   [267:12] free scratch register r14
    sete r15b
    bool.267.12.end:
;   [32:6] assert(ok bool)
    func.assert.267.5:
;       [267:5] alias ok -> r15b
        if.32.27.267.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.267.5:
        cmp r15b, 0
        jne if.32.24.267.5.end
        if.32.27.267.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.267.5.end:
;       [267:5] free scratch register r15
    func.assert.267.5.end:
;   [268:5] o3[1] = object_init()
;   [268:8] allocate scratch register -> r15
;   [268:8] set array index
;   [268:8] 1
    mov r15, 1
    imul r15, 24
;   [268:13] object_init()
;   [92:6] object_init() res object
    func.object_init.268.13:
;       [268:13] alias res -> o3 (lea: rbp + r15 + 480)
;       [93:5] res.pos.x = 2
;       [93:17] 2
        mov qword [rbp + r15 + 480], 2
;       [94:5] res.pos.y = 74
;       [94:17] 74
        mov qword [rbp + r15 + 488], 74
;       [95:5] res.color = 0xffffff
;       [95:17] 0xffffff
        mov dword [rbp + r15 + 496], 16777215
    func.object_init.268.13.end:
;   [268:5] free scratch register r15
;   [269:5] assert(o3[1].pos.y == 74)
;   [269:12] allocate scratch register -> r15
;   [269:12] ? o3[1].pos.y == 74
;   [269:12] ? o3[1].pos.y == 74
    cmp.269.12:
;   [269:15] allocate scratch register -> r14
;   [269:15] set array index
;   [269:15] 1
    mov r14, 1
    imul r14, 24
    cmp qword [rbp + r14 + 488], 74
;   [269:12] free scratch register r14
    sete r15b
    bool.269.12.end:
;   [32:6] assert(ok bool)
    func.assert.269.5:
;       [269:5] alias ok -> r15b
        if.32.27.269.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.269.5:
        cmp r15b, 0
        jne if.32.24.269.5.end
        if.32.27.269.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.269.5.end:
;       [269:5] free scratch register r15
    func.assert.269.5.end:
;   [271:5] var worlds[8] world
;   [271:9] worlds: world[8] (512 B @ [rbp + 528])
;   [271:9] zero 8 * 64 B = 512 B
;   [271:5] allocate named register rax
;   [271:5] allocate named register rdi
;   [271:5] allocate named register rcx
    xor al, al
    lea rdi, [rbp + 528]
    mov rcx, 512
    rep stosb
;   [271:5] free named register rcx
;   [271:5] free named register rdi
;   [271:5] free named register rax
;   [272:5] worlds[1].locations[1] = 0xffee
;   [272:12] allocate scratch register -> r15
;   [272:12] set array index
;   [272:12] 1
    mov r15, 1
    shl r15, 6
    lea r15, [rbp + r15 + 528]
;   [272:25] allocate scratch register -> r14
;   [272:25] set array index
;   [272:25] 1
    mov r14, 1
;   [272:30] 0xffee
    mov qword [r15 + r14 * 8], 65518
;   [272:5] free scratch register r14
;   [272:5] free scratch register r15
;   [273:5] assert(worlds[1].locations[1] == 0xffee)
;   [273:12] allocate scratch register -> r15
;   [273:12] ? worlds[1].locations[1] == 0xffee
;   [273:12] ? worlds[1].locations[1] == 0xffee
    cmp.273.12:
;   [273:19] allocate scratch register -> r14
;   [273:19] set array index
;   [273:19] 1
    mov r14, 1
    shl r14, 6
    lea r14, [rbp + r14 + 528]
;   [273:32] allocate scratch register -> r13
;   [273:32] set array index
;   [273:32] 1
    mov r13, 1
    cmp qword [r14 + r13 * 8], 65518
;   [273:12] free scratch register r13
;   [273:12] free scratch register r14
    sete r15b
    bool.273.12.end:
;   [32:6] assert(ok bool)
    func.assert.273.5:
;       [273:5] alias ok -> r15b
        if.32.27.273.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.273.5:
        cmp r15b, 0
        jne if.32.24.273.5.end
        if.32.27.273.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.273.5.end:
;       [273:5] free scratch register r15
    func.assert.273.5.end:
;   [275:5] array_copy( worlds[1].locations, worlds[0].locations, array_length(worlds.locations) )
;   [275:5] allocate named register rsi
;   [275:5] allocate named register rdi
;   [275:5] allocate named register rcx
;   [278:9] array_length(worlds.locations)
;   [278:9] rcx = array_length(worlds.locations)
;   [278:9] = expression
;   [278:9] array_length(worlds.locations)
    mov rcx, 8
;   [276:9] worlds[1].locations
;   [276:16] allocate scratch register -> r15
;   [276:16] set array index
;   [276:16] 1
    mov r15, 1
    shl r15, 6
    lea rsi, [rbp + r15 + 528]
;   [275:5] free scratch register r15
;   [277:9] worlds[0].locations
;   [277:16] allocate scratch register -> r15
;   [277:16] set array index
;   [277:16] 0
    mov r15, 0
    shl r15, 6
    lea rdi, [rbp + r15 + 528]
;   [275:5] free scratch register r15
    shl rcx, 3
    rep movsb
;   [275:5] free named register rcx
;   [275:5] free named register rdi
;   [275:5] free named register rsi
;   [282:5] assert(worlds[0].locations[1] == 0xffee)
;   [282:12] allocate scratch register -> r15
;   [282:12] ? worlds[0].locations[1] == 0xffee
;   [282:12] ? worlds[0].locations[1] == 0xffee
    cmp.282.12:
;   [282:19] allocate scratch register -> r14
;   [282:19] set array index
;   [282:19] 0
    mov r14, 0
    shl r14, 6
    lea r14, [rbp + r14 + 528]
;   [282:32] allocate scratch register -> r13
;   [282:32] set array index
;   [282:32] 1
    mov r13, 1
    cmp qword [r14 + r13 * 8], 65518
;   [282:12] free scratch register r13
;   [282:12] free scratch register r14
    sete r15b
    bool.282.12.end:
;   [32:6] assert(ok bool)
    func.assert.282.5:
;       [282:5] alias ok -> r15b
        if.32.27.282.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.282.5:
        cmp r15b, 0
        jne if.32.24.282.5.end
        if.32.27.282.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.282.5.end:
;       [282:5] free scratch register r15
    func.assert.282.5.end:
;   [283:5] assert(arrays_equal( worlds[0].locations, worlds[1].locations, array_length(worlds.locations) ))
;   [283:12] allocate scratch register -> r15
;   [283:12] ? arrays_equal( worlds[0].locations, worlds[1].locations, array_length(worlds.locations) )
;   [283:12] ? arrays_equal( worlds[0].locations, worlds[1].locations, array_length(worlds.locations) )
    cmp.283.12:
;       [283:12] arrays_equal( worlds[0].locations, worlds[1].locations, array_length(worlds.locations) )
;       [283:12] allocate named register rsi
;       [283:12] allocate named register rdi
;       [283:12] allocate named register rcx
;       [286:14] array_length(worlds.locations)
;       [286:14] rcx = array_length(worlds.locations)
;       [286:14] = expression
;       [286:14] array_length(worlds.locations)
        mov rcx, 8
;       [284:14] worlds[0].locations
;       [284:21] allocate scratch register -> r14
;       [284:21] set array index
;       [284:21] 0
        mov r14, 0
        shl r14, 6
        lea rsi, [rbp + r14 + 528]
;       [283:12] free scratch register r14
;       [285:14] worlds[1].locations
;       [285:21] allocate scratch register -> r14
;       [285:21] set array index
;       [285:21] 1
        mov r14, 1
        shl r14, 6
        lea rdi, [rbp + r14 + 528]
;       [283:12] free scratch register r14
        shl rcx, 3
        test rcx, rcx
        repe cmpsb
;       [283:12] free named register rcx
;       [283:12] free named register rdi
;       [283:12] free named register rsi
        sete r15b
    bool.283.12.end:
;   [32:6] assert(ok bool)
    func.assert.283.5:
;       [283:5] alias ok -> r15b
        if.32.27.283.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.283.5:
        cmp r15b, 0
        jne if.32.24.283.5.end
        if.32.27.283.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.283.5.end:
;       [283:5] free scratch register r15
    func.assert.283.5.end:
;   [288:5] var arr2[] = { -1, 2 }
;   [288:9] arr2: i64[2] (16 B @ [rbp + 1040])
;   [288:9] arr2= { -1, 2 }
;   [288:18] size <= 16 B, use immediates
    mov dword [rbp + 1040], -1
    mov dword [rbp + 1044], -1
    mov dword [rbp + 1048], 2
    mov dword [rbp + 1052], 0
;   [289:5] assert(array_length(arr2) == 2)
;   [289:12] allocate scratch register -> r15
;   [289:12] ? array_length(arr2) == 2
;   [289:12] ? array_length(arr2) == 2
    cmp.289.12:
;   [289:12] allocate scratch register -> r14
;       [289:12] r14 = array_length(arr2)
;       [289:12] = expression
;       [289:12] array_length(arr2)
        mov r14, 2
    cmp r14, 2
;   [289:12] free scratch register r14
    sete r15b
    bool.289.12.end:
;   [32:6] assert(ok bool)
    func.assert.289.5:
;       [289:5] alias ok -> r15b
        if.32.27.289.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.289.5:
        cmp r15b, 0
        jne if.32.24.289.5.end
        if.32.27.289.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.289.5.end:
;       [289:5] free scratch register r15
    func.assert.289.5.end:
;   [290:5] assert(arr2[0] == -1)
;   [290:12] allocate scratch register -> r15
;   [290:12] ? arr2[0] == -1
;   [290:12] ? arr2[0] == -1
    cmp.290.12:
;   [290:17] allocate scratch register -> r14
;   [290:17] set array index
;   [290:17] 0
    mov r14, 0
    cmp qword [rbp + r14 * 8 + 1040], -1
;   [290:12] free scratch register r14
    sete r15b
    bool.290.12.end:
;   [32:6] assert(ok bool)
    func.assert.290.5:
;       [290:5] alias ok -> r15b
        if.32.27.290.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.290.5:
        cmp r15b, 0
        jne if.32.24.290.5.end
        if.32.27.290.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.290.5.end:
;       [290:5] free scratch register r15
    func.assert.290.5.end:
;   [291:5] assert(arr2[1] == 2)
;   [291:12] allocate scratch register -> r15
;   [291:12] ? arr2[1] == 2
;   [291:12] ? arr2[1] == 2
    cmp.291.12:
;   [291:17] allocate scratch register -> r14
;   [291:17] set array index
;   [291:17] 1
    mov r14, 1
    cmp qword [rbp + r14 * 8 + 1040], 2
;   [291:12] free scratch register r14
    sete r15b
    bool.291.12.end:
;   [32:6] assert(ok bool)
    func.assert.291.5:
;       [291:5] alias ok -> r15b
        if.32.27.291.5:
;       [32:27] ? not ok
;       [32:27] ? not ok
        cmp.32.27.291.5:
        cmp r15b, 0
        jne if.32.24.291.5.end
        if.32.27.291.5.code:
;           [32:34] exit(1)
;           [32:34] allocate named register rdi
;           [32:39] 1
            mov rdi, 1
            mov rax, 60
            syscall
;           [32:34] free named register rdi
        if.32.24.291.5.end:
;       [291:5] free scratch register r15
    func.assert.291.5.end:
;   [293:5] var counter
;   [293:9] counter: i64 (8 B @ [rbp + 1056])
;   [293:9] zero 1 * 8 B = 8 B
;   [293:5] size <= 32 B, use mov
    mov qword [rbp + 1056], 0
;   [294:5] var nm str
;   [294:9] nm: str (128 B @ [rbp + 1064])
;   [294:9] zero 1 * 128 B = 128 B
;   [294:5] allocate named register rax
;   [294:5] allocate named register rdi
;   [294:5] allocate named register rcx
    xor al, al
    lea rdi, [rbp + 1064]
    mov rcx, 128
    rep stosb
;   [294:5] free named register rcx
;   [294:5] free named register rdi
;   [294:5] free named register rax
;   [295:5] print(hello)
;   [35:6] print(str[] i8)
    func.print.295.5:
;       [295:5] alias str -> hello
;       [36:5] write(1, str)
;       [36:5] allocate named register rdi
;       [36:5] allocate named register rsi
;       [36:5] allocate named register rdx
;       [36:11] 1
        mov rdi, 1
        mov rdx, 21
        lea rsi, [rbp]
;       [36:5] allocate named register rax
        mov rax, 1
        syscall
;       [36:5] free named register rax
;       [36:5] free named register rdx
;       [36:5] free named register rsi
;       [36:5] free named register rdi
    func.print.295.5.end:
;   [296:5] label
    loop.296.5:
;       [297:9] counter = counter + 1
;       [297:19] instructions without scratch register 1, with 3
;       [297:19] counter
;       [297:29] counter + 1
        add qword [rbp + 1056], 1
;       [298:9] print_num(counter)
;       [298:9] address of argument 'counter' to parameter 'num'
;       [298:9] allocate scratch register -> r15
        lea r15, [rbp + 1056]
        mov qword [rbp + 1192], r15
;       [298:9] free scratch register r15
        PUSH_REGS
        lea rbx, [rbp + 1192]
        call func.print_num
        POP_REGS
;       [299:9] print(colon)
;       [35:6] print(str[] i8)
        func.print.299.9:
;           [299:9] alias str -> colon
;           [36:5] write(1, str)
;           [36:5] allocate named register rdi
;           [36:5] allocate named register rsi
;           [36:5] allocate named register rdx
;           [36:11] 1
            mov rdi, 1
            mov rdx, 2
            lea rsi, [rbp + 61]
;           [36:5] allocate named register rax
            mov rax, 1
            syscall
;           [36:5] free named register rax
;           [36:5] free named register rdx
;           [36:5] free named register rsi
;           [36:5] free named register rdi
        func.print.299.9.end:
;       [300:9] print(prompt1)
;       [35:6] print(str[] i8)
        func.print.300.9:
;           [300:9] alias str -> prompt1
;           [36:5] write(1, str)
;           [36:5] allocate named register rdi
;           [36:5] allocate named register rsi
;           [36:5] allocate named register rdx
;           [36:11] 1
            mov rdi, 1
            mov rdx, 12
            lea rsi, [rbp + 21]
;           [36:5] allocate named register rax
            mov rax, 1
            syscall
;           [36:5] free named register rax
;           [36:5] free named register rdx
;           [36:5] free named register rsi
;           [36:5] free named register rdi
        func.print.300.9.end:
;       [301:12] nm.input()
;       [76:6] str.input()
        func.str.input.301.12:
;           [301:12] alias self -> nm
;           [77:5] var nbytes = read(0, self.data)
;           [77:9] nbytes: i64 (8 B @ [rbp + 1192])
;           [77:9] nbytes = read(0, self.data)
;           [77:18] nbytes = read(0, self.data)
;           [77:18] = expression
;           [77:18] read(0, self.data)
;           [77:18] allocate named register rdi
;           [77:18] allocate named register rsi
;           [77:18] allocate named register rdx
;           [77:23] 0
            mov rdi, 0
            mov rdx, 127
            lea rsi, [rbp + 1065]
;           [77:18] allocate named register rax
            mov rax, 0
            syscall
            mov qword [rbp + 1192], rax
;           [77:18] free named register rax
;           [77:18] free named register rdx
;           [77:18] free named register rsi
;           [77:18] free named register rdi
;           [80:5] self.len = i8(nbytes - 1)
;           [80:16] self.len = i8(nbytes - 1)
;           [80:16] = expression
;           [80:19] instructions without scratch register 3, with 3
;           [80:19] nbytes
;           [80:19] allocate scratch register -> r15
            mov r15b, byte [rbp + 1192]
            mov byte [rbp + 1064], r15b
;           [80:19] free scratch register r15
;           [80:28] self.len - 1
            sub byte [rbp + 1064], 1
        func.str.input.301.12.end:
        if.303.12:
;       [303:12] ? nm.len <= 0
;       [303:12] ? nm.len <= 0
        cmp.303.12:
        cmp byte [rbp + 1064], 0
        jg if.305.19
        if.303.12.code:
;           [304:13] break
            jmp loop.296.5.end
        if.305.19:
;       [305:19] ? nm.len <= 4
;       [305:19] ? nm.len <= 4
        cmp.305.19:
        cmp byte [rbp + 1064], 4
        jg if.303.9.else
        if.305.19.code:
;           [306:13] print(prompt2)
;           [35:6] print(str[] i8)
            func.print.306.13:
;               [306:13] alias str -> prompt2
;               [36:5] write(1, str)
;               [36:5] allocate named register rdi
;               [36:5] allocate named register rsi
;               [36:5] allocate named register rdx
;               [36:11] 1
                mov rdi, 1
                mov rdx, 20
                lea rsi, [rbp + 33]
;               [36:5] allocate named register rax
                mov rax, 1
                syscall
;               [36:5] free named register rax
;               [36:5] free named register rdx
;               [36:5] free named register rsi
;               [36:5] free named register rdi
            func.print.306.13.end:
;           [307:13] continue
            jmp loop.296.5
        if.303.9.else:
;           [309:13] print(prompt3)
;           [35:6] print(str[] i8)
            func.print.309.13:
;               [309:13] alias str -> prompt3
;               [36:5] write(1, str)
;               [36:5] allocate named register rdi
;               [36:5] allocate named register rsi
;               [36:5] allocate named register rdx
;               [36:11] 1
                mov rdi, 1
                mov rdx, 6
                lea rsi, [rbp + 53]
;               [36:5] allocate named register rax
                mov rax, 1
                syscall
;               [36:5] free named register rax
;               [36:5] free named register rdx
;               [36:5] free named register rsi
;               [36:5] free named register rdi
            func.print.309.13.end:
;           [310:16] nm.output()
;           [83:6] str.output()
            func.str.output.310.16:
;               [310:16] alias self -> nm
;               [84:5] write(1, self.data, self.len)
;               [84:5] allocate named register rdi
;               [84:5] allocate named register rsi
;               [84:5] allocate named register rdx
;               [84:11] 1
                mov rdi, 1
;               [84:25] self.len
                movsx rdx, byte [rbp + 1064]
                lea rsi, [rbp + 1065]
;               [84:5] allocate named register rax
                mov rax, 1
                syscall
;               [84:5] free named register rax
;               [84:5] free named register rdx
;               [84:5] free named register rsi
;               [84:5] free named register rdi
            func.str.output.310.16.end:
;           [311:13] print(dot)
;           [35:6] print(str[] i8)
            func.print.311.13:
;               [311:13] alias str -> dot
;               [36:5] write(1, str)
;               [36:5] allocate named register rdi
;               [36:5] allocate named register rsi
;               [36:5] allocate named register rdx
;               [36:11] 1
                mov rdi, 1
                mov rdx, 1
                lea rsi, [rbp + 59]
;               [36:5] allocate named register rax
                mov rax, 1
                syscall
;               [36:5] free named register rax
;               [36:5] free named register rdx
;               [36:5] free named register rsi
;               [36:5] free named register rdi
            func.print.311.13.end:
;           [312:13] print(nl)
;           [35:6] print(str[] i8)
            func.print.312.13:
;               [312:13] alias str -> nl
;               [36:5] write(1, str)
;               [36:5] allocate named register rdi
;               [36:5] allocate named register rsi
;               [36:5] allocate named register rdx
;               [36:11] 1
                mov rdi, 1
                mov rdx, 1
                lea rsi, [rbp + 60]
;               [36:5] allocate named register rax
                mov rax, 1
                syscall
;               [36:5] free named register rax
;               [36:5] free named register rdx
;               [36:5] free named register rsi
;               [36:5] free named register rdi
            func.print.312.13.end:
        if.303.9.end:
    jmp loop.296.5
    loop.296.5.end:
    mov rdi, 0
    mov rax, 60
    syscall

;
;[109:15] noinline print_num(num)
func.print_num:
;   [109:25] num: i64 (8 B @ [rbx])
;   [111:11] const buf_count = 20
;   [113:5] var buf[buf_count] i8
;   [113:9] buf: i8[20] (20 B @ [rbx + 8])
;   [113:9] zero 20 * 1 B = 20 B
;   [113:5] size <= 32 B, use mov
    mov qword [rbx + 8], 0
    mov qword [rbx + 16], 0
    mov dword [rbx + 24], 0
;   [114:5] var n = num
;   [114:9] n: i64 (8 B @ [rbx + 32])
;   [114:9] n = num
;   [114:13] num
;   [114:13] allocate scratch register -> r15
    mov r15, qword [rbx]
;   [114:13] allocate scratch register -> r14
    mov r14, qword [r15]
    mov qword [rbx + 32], r14
;   [114:13] free scratch register r14
;   [114:13] free scratch register r15
;   [115:5] var is_negative bool
;   [115:9] is_negative: bool (1 B @ [rbx + 40])
;   [115:9] zero 1 * 1 B = 1 B
;   [115:5] size <= 32 B, use mov
    mov byte [rbx + 40], 0
    if.119.8:
;   [119:8] ? n < 0
;   [119:8] ? n < 0
    cmp.119.8:
    cmp qword [rbx + 32], 0
    jge if.119.5.end
    if.119.8.code:
;       [120:9] is_negative = true
        mov byte [rbx + 40], 1
    if.119.5.end:
    if.122.8:
;   [122:8] ? n > 0
;   [122:8] ? n > 0
    cmp.122.8:
    cmp qword [rbx + 32], 0
    jle if.122.5.end
    if.122.8.code:
;       [123:9] n = -n
;       [123:14] -n
        neg qword [rbx + 32]
    if.122.5.end:
;   [126:5] var i = buf_count
;   [126:9] i: i64 (8 B @ [rbx + 48])
;   [126:9] i = buf_count
;   [126:13] buf_count
    mov qword [rbx + 48], 20
;   [127:5] label
    loop.127.5:
;       [128:9] i = i - 1
;       [128:13] instructions without scratch register 1, with 3
;       [128:13] i
;       [128:17] i - 1
        sub qword [rbx + 48], 1
;       [129:9] buf[i] = i8('0' - n % 10)
;       [129:13] allocate scratch register -> r15
;       [129:13] set array index
;       [129:13] i
        mov r15, qword [rbx + 48]
;       [129:18] buf = i8('0' - n % 10)
;       [129:18] = expression
;       [129:18] allocate scratch register -> r14
;           [129:21] '0'
            mov r14, 48
;           [129:29] r14 - n % 10
;           [129:29] allocate scratch register -> r13
;           [129:27] n
            mov r13, qword [rbx + 32]
;           [129:31] r13 % 10
;           [129:31] div const
;           [129:31] allocate named register rax
            mov rax, r13
;           [129:31] allocate named register rdx
            cqo
;           [129:31] allocate scratch register -> r12
            mov r12, 10
            idiv r12
;           [129:31] free scratch register r12
            mov r13, rdx
;           [129:31] free named register rdx
;           [129:31] free named register rax
            sub r14, r13
;           [129:29] free scratch register r13
        mov byte [rbx + r15 + 8], r14b
;       [129:18] free scratch register r14
;       [129:9] free scratch register r15
;       [130:9] n = n / 10
;       [130:13] instructions without scratch register 5, with 7
;       [130:13] n
;       [130:17] n / 10
;       [130:17] div const
;       [130:17] allocate named register rax
        mov rax, qword [rbx + 32]
;       [130:17] allocate named register rdx
        cqo
;       [130:17] allocate scratch register -> r15
        mov r15, 10
        idiv r15
;       [130:17] free scratch register r15
        mov qword [rbx + 32], rax
;       [130:17] free named register rdx
;       [130:17] free named register rax
        if.131.12:
;       [131:12] ? n == 0
;       [131:12] ? n == 0
        cmp.131.12:
        cmp qword [rbx + 32], 0
        jne if.131.9.end
        if.131.12.code:
;           [131:19] break
            jmp loop.127.5.end
        if.131.9.end:
    jmp loop.127.5
    loop.127.5.end:
    if.134.8:
;   [134:8] ? is_negative
;   [134:8] ? is_negative
    cmp.134.8:
    cmp byte [rbx + 40], 0
    je if.134.5.end
    if.134.8.code:
;       [135:9] i = i - 1
;       [135:13] instructions without scratch register 1, with 3
;       [135:13] i
;       [135:17] i - 1
        sub qword [rbx + 48], 1
;       [136:9] buf[i] = '-'
;       [136:13] allocate scratch register -> r15
;       [136:13] set array index
;       [136:13] i
        mov r15, qword [rbx + 48]
;       [136:18] '-'
        mov byte [rbx + r15 + 8], 45
;       [136:9] free scratch register r15
    if.134.5.end:
;   [139:5] var write_pos
;   [139:9] write_pos: i64 (8 B @ [rbx + 56])
;   [139:9] zero 1 * 8 B = 8 B
;   [139:5] size <= 32 B, use mov
    mov qword [rbx + 56], 0
;   [140:5] label
    loop.140.5:
;       [141:9] buf[write_pos] = buf[i]
;       [141:13] allocate scratch register -> r15
;       [141:13] set array index
;       [141:13] write_pos
        mov r15, qword [rbx + 56]
;       [141:26] buf[i]
;       [141:30] allocate scratch register -> r14
;       [141:30] set array index
;       [141:30] i
        mov r14, qword [rbx + 48]
;       [141:26] allocate scratch register -> r13
        mov r13b, byte [rbx + r14 + 8]
        mov byte [rbx + r15 + 8], r13b
;       [141:26] free scratch register r13
;       [141:26] free scratch register r14
;       [141:9] free scratch register r15
;       [142:9] write_pos = write_pos + 1
;       [142:21] instructions without scratch register 1, with 3
;       [142:21] write_pos
;       [142:33] write_pos + 1
        add qword [rbx + 56], 1
;       [143:9] i = i + 1
;       [143:13] instructions without scratch register 1, with 3
;       [143:13] i
;       [143:17] i + 1
        add qword [rbx + 48], 1
        if.144.12:
;       [144:12] ? i == buf_count
;       [144:12] ? i == buf_count
        cmp.144.12:
        cmp qword [rbx + 48], 20
        jne if.144.9.end
        if.144.12.code:
;           [144:27] break
            jmp loop.140.5.end
        if.144.9.end:
    jmp loop.140.5
    loop.140.5.end:
;   [147:5] write(1, buf, write_pos)
;   [147:5] allocate named register rdi
;   [147:5] allocate named register rsi
;   [147:5] allocate named register rdx
;   [147:11] 1
    mov rdi, 1
;   [147:19] write_pos
    mov rdx, qword [rbx + 56]
    lea rsi, [rbx + 8]
;   [147:5] allocate named register rax
    mov rax, 1
    syscall
;   [147:5] free named register rax
;   [147:5] free named register rdx
;   [147:5] free named register rsi
;   [147:5] free named register rdi
    ret
size.func.print_num equ 64

section .data
align 16
dat:
;[20:7] hello
;[20:20] i8[21]
db `hello world from baz\n`
;[21:5] prompt1
;[21:20] i8[12]
db `enter name:\n`
;[22:5] prompt2
;[22:20] i8[20]
db `that is not a name.\n`
;[23:5] prompt3
;[23:20] i8[6]
db `hello `
;[24:9] dot
;[24:20] i8[1]
db `.`
;[25:10] nl
;[25:20] i8[1]
db `\n`
;[26:7] colon
;[26:20] i8[2]
db `: `
; padding 1 B
times 1 db 0
;[27:8] nums
; i64[4]
;[27:20] [0]
;[27:20] i64
dq 1
; pad 3 'i64' of size 8
times 24 db 0
;[28:8] str1
;[28:21] i8
db 3
;[28:19] zero remaining fields: 127 B
times 127 db 0
dat.end:

section .bss.vars nobits alloc write
align 16
vars:
resb 65536
vars.end:
; free named register rbp

;   removed jumps to next code: 88
;    removed unreachable jumps: 2
; removed same target branches: 33
; inverted branches over jumps: 0

; max scratch registers in use: 4
;            max frames in use: 8
;              dat var padding: 0 B
;                max vars size: 976 B
