#
# generated by baz
#

.option norvc
.option norelax

.macro PUSH_REGS
    addi sp, sp, -128
    sw t0, 16(sp)
    sw t1, 20(sp)
    sw t2, 24(sp)
    sw t3, 108(sp)
    sw t4, 112(sp)
    sw t5, 116(sp)
    sw t6, 120(sp)
    sw s0, 28(sp)
    sw s1, 32(sp)
    sw s2, 68(sp)
    sw s3, 72(sp)
    sw s4, 76(sp)
    sw s5, 80(sp)
    sw s6, 84(sp)
    sw s7, 88(sp)
    sw s8, 92(sp)
    sw s9, 96(sp)
    sw s10, 100(sp)
    sw s11, 104(sp)
    sw tp, 12(sp)
    sw gp, 8(sp)
    sw ra, 0(sp)
    sw a1, 40(sp)
    sw a2, 44(sp)
    sw a3, 48(sp)
    sw a4, 52(sp)
    sw a5, 56(sp)
    sw a6, 60(sp)
    sw a7, 64(sp)
    sw a0, 36(sp)
.endm

.macro POP_REGS
    lw t0, 16(sp)
    lw t1, 20(sp)
    lw t2, 24(sp)
    lw t3, 108(sp)
    lw t4, 112(sp)
    lw t5, 116(sp)
    lw t6, 120(sp)
    lw s0, 28(sp)
    lw s1, 32(sp)
    lw s2, 68(sp)
    lw s3, 72(sp)
    lw s4, 76(sp)
    lw s5, 80(sp)
    lw s6, 84(sp)
    lw s7, 88(sp)
    lw s8, 92(sp)
    lw s9, 96(sp)
    lw s10, 100(sp)
    lw s11, 104(sp)
    lw tp, 12(sp)
    lw gp, 8(sp)
    lw ra, 0(sp)
    lw a1, 40(sp)
    lw a2, 44(sp)
    lw a3, 48(sp)
    lw a4, 52(sp)
    lw a5, 56(sp)
    lw a6, 60(sp)
    lw a7, 64(sp)
    lw a0, 36(sp)
    addi sp, sp, 128
.endm

.text
.globl _start
_start:

# allocate named register s0
la s0, dat

lui sp, 2048

# [1:1] dat hello[] i8 = "u r in roome\n"
# [1:7] hello: i8[13] (13 B @ [s0])
# [2:1] dat prompt1[] i8 = "enter name:\n"
# [2:5] prompt1: i8[12] (12 B @ [s0 + 13])
# [3:1] dat prompt2[] i8 = "that is not a name.\n"
# [3:5] prompt2: i8[20] (20 B @ [s0 + 25])
# [4:1] dat prompt3[] i8 = "hello "
# [4:5] prompt3: i8[6] (6 B @ [s0 + 45])
# [5:1] dat dot[] i8 = "."
# [5:9] dot: i8[1] (1 B @ [s0 + 51])
# [6:1] dat nl[] i8 = "\n"
# [6:10] nl: i8[1] (1 B @ [s0 + 52])
# [7:1] dat erase[] i8 = "\b \b"
# [7:7] erase: i8[3] (3 B @ [s0 + 53])
# [8:1] dat colon[] i8 = ": "
# [8:7] colon: i8[2] (2 B @ [s0 + 56])
# [10:1] str : 128 B    fields:
# [10:1]       name :  offset :    size :  array? : array size
# [10:1]        len :       0 :       1 :      no :           
# [10:1]       data :       1 :     127 :     yes :        127
#
#
main:
    # [85:5] var counter
    # [85:9] counter: i32 (4 B @ [s0 + 64])
    # [85:9] zero 1 * 4 B = 4 B
    sw zero, 64(s0)
    # [86:5] var nm str
    # [86:9] nm: str (128 B @ [s0 + 68])
    # [86:9] zero 1 * 128 B = 128 B
    # [86:5] allocate scratch register -> t0
    # [86:5] allocate scratch register -> t1
    addi t0, s0, 68
    li t1, 32
    1:
    sw zero, 0(t0)
    addi t0, t0, 4
    addi t1, t1, -1
    bnez t1, 1b
    # [86:5] free scratch register t1
    # [86:5] free scratch register t0
    # [87:5] print(hello)
    # [80:6] print(s[] i8)
    func.print.87.5:
        # [87:5] alias s -> hello
        # [81:5] write(1, s)
        # [81:5] allocate named register a0
        # [81:5] allocate named register a1
        # [81:5] allocate named register a2
        # [81:11] 1
        li a0, 1
        li a2, 13
        addi a1, s0, 0
        # [81:5] allocate named register a7
        call a7, .Lbaz_write
        # [81:5] free named register a7
        # [81:5] free named register a2
        # [81:5] free named register a1
        # [81:5] free named register a0
    func.print.87.5.end:
    # [88:5] label
    loop.88.5:
        # [89:9] counter = counter + 1
        # [89:19] counter
        # [89:29] counter + 1
        # [89:29] allocate scratch register -> t0
        lw t0, 64(s0)
        addi t0, t0, 1
        sw t0, 64(s0)
        # [89:29] free scratch register t0
        # [90:9] print_num(counter)
        # [90:9] address of argument 'counter' to parameter 'num'
        # [90:9] allocate scratch register -> t0
        addi t0, s0, 64
        sw t0, 196(s0)
        # [90:9] free scratch register t0
        PUSH_REGS
        addi s1, s0, 196
        call func.print_num
        POP_REGS
        # [91:9] print(colon)
        # [80:6] print(s[] i8)
        func.print.91.9:
            # [91:9] alias s -> colon
            # [81:5] write(1, s)
            # [81:5] allocate named register a0
            # [81:5] allocate named register a1
            # [81:5] allocate named register a2
            # [81:11] 1
            li a0, 1
            li a2, 2
            addi a1, s0, 56
            # [81:5] allocate named register a7
            call a7, .Lbaz_write
            # [81:5] free named register a7
            # [81:5] free named register a2
            # [81:5] free named register a1
            # [81:5] free named register a0
        func.print.91.9.end:
        # [92:9] print(prompt1)
        # [80:6] print(s[] i8)
        func.print.92.9:
            # [92:9] alias s -> prompt1
            # [81:5] write(1, s)
            # [81:5] allocate named register a0
            # [81:5] allocate named register a1
            # [81:5] allocate named register a2
            # [81:11] 1
            li a0, 1
            li a2, 12
            addi a1, s0, 13
            # [81:5] allocate named register a7
            call a7, .Lbaz_write
            # [81:5] free named register a7
            # [81:5] free named register a2
            # [81:5] free named register a1
            # [81:5] free named register a0
        func.print.92.9.end:
        # [93:12] nm.in()
        # [19:6] str.in()
        func.str.in.93.12:
            # [93:12] alias self -> nm
            # [21:5] var nbytes
            # [21:9] nbytes: i32 (4 B @ [s0 + 196])
            # [21:9] zero 1 * 4 B = 4 B
            sw zero, 196(s0)
            # [22:5] label
            loop.22.5.93.12:
                if.23.12.93.12:
                # [23:12] ? nbytes == array_length(self.data)
                # [23:12] ? nbytes == array_length(self.data)
                cmp.23.12.93.12:
                # [23:22] allocate scratch register -> t0
                    # [23:22] t0 = array_length(self.data)
                    # [23:22] = expression
                    # [23:22] array_length(self.data)
                    li t0, 127
                # [23:12] allocate scratch register -> t1
                lw t1, 196(s0)
                beq t1, t0, loop.22.5.93.12.end
                # [23:12] free scratch register t1
                # [23:12] free scratch register t0
                if.23.12.93.12.code:
                    # [23:46] break
                if.23.9.93.12.end:
                if.24.12.93.12:
                # [24:12] ? read(0, self.data, 1, nbytes) == 0
                # [24:12] ? read(0, self.data, 1, nbytes) == 0
                cmp.24.12.93.12:
                # [24:12] allocate scratch register -> t0
                    # [24:12] t0 = read(0, self.data, 1, nbytes)
                    # [24:12] = expression
                    # [24:12] read(0, self.data, 1, nbytes)
                    # [24:12] allocate named register a0
                    # [24:12] allocate named register a1
                    # [24:12] allocate named register a2
                    # [24:17] 0
                    li a0, 0
                    # [24:31] 1
                    li a2, 1
                    # [24:34] allocate scratch register -> t1
                    # [24:34] nbytes
                    lw t1, 196(s0)
                    # [24:34] bounds check
                    bltz t1, 1f
                    bltz a2, 1f
                    # [24:34] allocate scratch register -> t2
                    # [24:34] allocate scratch register -> t3
                    # [24:34] allocate scratch register -> t4
                    srai t4, t1, 31
                    srai t2, a2, 31
                    add t4, t4, t2
                    add t3, t1, a2
                    sltu t2, t3, t1
                    add t4, t4, t2
                    bltz t4, 2f
                    bgtz t4, 1f
                    li t2, 127
                    bgeu t2, t3, 2f
                    1:
                    li a0, 24
                    j baz_bounds_panic
                    2:
                    # [24:34] free scratch register t4
                    # [24:34] free scratch register t3
                    # [24:34] free scratch register t2
                    addi a1, s0, 69
                    add a1, a1, t1
                    # [24:12] free scratch register t1
                    # [24:12] allocate named register a7
                    call a7, .Lbaz_read
                    # [24:12] free named register a7
                    addi t0, a0, 0
                    # [24:12] free named register a2
                    # [24:12] free named register a1
                    # [24:12] free named register a0
                beq t0, zero, loop.22.5.93.12.end
                # [24:12] free scratch register t0
                if.24.12.93.12.code:
                    # [24:47] break
                if.24.9.93.12.end:
                if.25.12.93.12:
                # [25:12] ? self.data[nbytes] == '\x7f'
                # [25:12] ? self.data[nbytes] == '\x7f'
                cmp.25.12.93.12:
                # [25:22] allocate scratch register -> t0
                # [25:22] set array index
                # [25:22] nbytes
                lw t0, 196(s0)
                # [25:22] bounds check
                bltz t0, 1f
                # [25:22] allocate scratch register -> t1
                bltz t0, 2f
                li t1, 127
                bltu t0, t1, 2f
                1:
                li a0, 25
                j baz_bounds_panic
                2:
                # [25:22] free scratch register t1
                # [25:12] allocate scratch register -> t1
                add t1, s0, t0
                lb t1, 69(t1)
                # [25:12] allocate scratch register -> t2
                li t2, 127
                bne t1, t2, if.25.9.93.12.end
                # [25:12] free scratch register t2
                # [25:12] free scratch register t1
                # [25:12] free scratch register t0
                if.25.12.93.12.code:
                    if.26.16.93.12:
                    # [26:16] ? nbytes > 0
                    # [26:16] ? nbytes > 0
                    cmp.26.16.93.12:
                    # [26:16] allocate scratch register -> t0
                    lw t0, 196(s0)
                    bge zero, t0, if.26.13.93.12.end
                    # [26:16] free scratch register t0
                    if.26.16.93.12.code:
                        # [27:17] nbytes = nbytes - 1
                        # [27:26] nbytes
                        # [27:35] nbytes - 1
                        # [27:35] allocate scratch register -> t0
                        lw t0, 196(s0)
                        addi t0, t0, -1
                        sw t0, 196(s0)
                        # [27:35] free scratch register t0
                        # [28:17] write(1, erase)
                        # [28:17] allocate named register a0
                        # [28:17] allocate named register a1
                        # [28:17] allocate named register a2
                        # [28:23] 1
                        li a0, 1
                        li a2, 3
                        addi a1, s0, 53
                        # [28:17] allocate named register a7
                        call a7, .Lbaz_write
                        # [28:17] free named register a7
                        # [28:17] free named register a2
                        # [28:17] free named register a1
                        # [28:17] free named register a0
                    if.26.13.93.12.end:
                    # [30:13] continue
                    j loop.22.5.93.12
                if.25.9.93.12.end:
                # [32:9] write(1, self.data, 1, nbytes)
                # [32:9] allocate named register a0
                # [32:9] allocate named register a1
                # [32:9] allocate named register a2
                # [32:15] 1
                li a0, 1
                # [32:29] 1
                li a2, 1
                # [32:32] allocate scratch register -> t0
                # [32:32] nbytes
                lw t0, 196(s0)
                # [32:32] bounds check
                bltz t0, 1f
                bltz a2, 1f
                # [32:32] allocate scratch register -> t1
                # [32:32] allocate scratch register -> t2
                # [32:32] allocate scratch register -> t3
                srai t3, t0, 31
                srai t1, a2, 31
                add t3, t3, t1
                add t2, t0, a2
                sltu t1, t2, t0
                add t3, t3, t1
                bltz t3, 2f
                bgtz t3, 1f
                li t1, 127
                bgeu t1, t2, 2f
                1:
                li a0, 32
                j baz_bounds_panic
                2:
                # [32:32] free scratch register t3
                # [32:32] free scratch register t2
                # [32:32] free scratch register t1
                addi a1, s0, 69
                add a1, a1, t0
                # [32:9] free scratch register t0
                # [32:9] allocate named register a7
                call a7, .Lbaz_write
                # [32:9] free named register a7
                # [32:9] free named register a2
                # [32:9] free named register a1
                # [32:9] free named register a0
                if.33.12.93.12:
                # [33:12] ? self.data[nbytes] == '\n'
                # [33:12] ? self.data[nbytes] == '\n'
                cmp.33.12.93.12:
                # [33:22] allocate scratch register -> t0
                # [33:22] set array index
                # [33:22] nbytes
                lw t0, 196(s0)
                # [33:22] bounds check
                bltz t0, 1f
                # [33:22] allocate scratch register -> t1
                bltz t0, 2f
                li t1, 127
                bltu t0, t1, 2f
                1:
                li a0, 33
                j baz_bounds_panic
                2:
                # [33:22] free scratch register t1
                # [33:12] allocate scratch register -> t1
                add t1, s0, t0
                lb t1, 69(t1)
                # [33:12] allocate scratch register -> t2
                li t2, 10
                beq t1, t2, loop.22.5.93.12.end
                # [33:12] free scratch register t2
                # [33:12] free scratch register t1
                # [33:12] free scratch register t0
                if.33.12.93.12.code:
                    # [33:38] break
                if.33.9.93.12.end:
                # [34:9] nbytes = nbytes + 1
                # [34:18] nbytes
                # [34:27] nbytes + 1
                # [34:27] allocate scratch register -> t0
                lw t0, 196(s0)
                addi t0, t0, 1
                sw t0, 196(s0)
                # [34:27] free scratch register t0
            j loop.22.5.93.12
            loop.22.5.93.12.end:
            # [36:5] self.len = i8(nbytes)
            # [36:16] self.len = i8(nbytes)
            # [36:16] = expression
            # [36:19] nbytes
            # [36:19] allocate scratch register -> t0
            lw t0, 196(s0)
            sb t0, 68(s0)
            # [36:19] free scratch register t0
        func.str.in.93.12.end:
        if.94.12:
        # [94:12] ? nm.len <= 4
        # [94:12] ? nm.len <= 4
        cmp.94.12:
        # [94:12] allocate scratch register -> t0
        lb t0, 68(s0)
        # [94:12] allocate scratch register -> t1
        li t1, 4
        blt t1, t0, if.94.9.else
        # [94:12] free scratch register t1
        # [94:12] free scratch register t0
        if.94.12.code:
            # [95:13] print(prompt2)
            # [80:6] print(s[] i8)
            func.print.95.13:
                # [95:13] alias s -> prompt2
                # [81:5] write(1, s)
                # [81:5] allocate named register a0
                # [81:5] allocate named register a1
                # [81:5] allocate named register a2
                # [81:11] 1
                li a0, 1
                li a2, 20
                addi a1, s0, 25
                # [81:5] allocate named register a7
                call a7, .Lbaz_write
                # [81:5] free named register a7
                # [81:5] free named register a2
                # [81:5] free named register a1
                # [81:5] free named register a0
            func.print.95.13.end:
            # [96:13] continue
            j loop.88.5
        if.94.9.else:
            # [98:13] print(prompt3)
            # [80:6] print(s[] i8)
            func.print.98.13:
                # [98:13] alias s -> prompt3
                # [81:5] write(1, s)
                # [81:5] allocate named register a0
                # [81:5] allocate named register a1
                # [81:5] allocate named register a2
                # [81:11] 1
                li a0, 1
                li a2, 6
                addi a1, s0, 45
                # [81:5] allocate named register a7
                call a7, .Lbaz_write
                # [81:5] free named register a7
                # [81:5] free named register a2
                # [81:5] free named register a1
                # [81:5] free named register a0
            func.print.98.13.end:
            # [99:16] nm.out()
            # [15:6] str.out()
            func.str.out.99.16:
                # [99:16] alias self -> nm
                # [16:5] write(1, self.data, self.len)
                # [16:5] allocate named register a0
                # [16:5] allocate named register a1
                # [16:5] allocate named register a2
                # [16:11] 1
                li a0, 1
                # [16:25] self.len
                lb a2, 68(s0)
                # [16:14] bounds check
                bltz a2, 1f
                # [16:14] allocate scratch register -> t0
                bltz a2, 2f
                li t0, 127
                bgeu t0, a2, 2f
                1:
                li a0, 16
                j baz_bounds_panic
                2:
                # [16:14] free scratch register t0
                addi a1, s0, 69
                # [16:5] allocate named register a7
                call a7, .Lbaz_write
                # [16:5] free named register a7
                # [16:5] free named register a2
                # [16:5] free named register a1
                # [16:5] free named register a0
            func.str.out.99.16.end:
            # [100:13] print(dot)
            # [80:6] print(s[] i8)
            func.print.100.13:
                # [100:13] alias s -> dot
                # [81:5] write(1, s)
                # [81:5] allocate named register a0
                # [81:5] allocate named register a1
                # [81:5] allocate named register a2
                # [81:11] 1
                li a0, 1
                li a2, 1
                addi a1, s0, 51
                # [81:5] allocate named register a7
                call a7, .Lbaz_write
                # [81:5] free named register a7
                # [81:5] free named register a2
                # [81:5] free named register a1
                # [81:5] free named register a0
            func.print.100.13.end:
            # [101:13] print(nl)
            # [80:6] print(s[] i8)
            func.print.101.13:
                # [101:13] alias s -> nl
                # [81:5] write(1, s)
                # [81:5] allocate named register a0
                # [81:5] allocate named register a1
                # [81:5] allocate named register a2
                # [81:11] 1
                li a0, 1
                li a2, 1
                addi a1, s0, 52
                # [81:5] allocate named register a7
                call a7, .Lbaz_write
                # [81:5] free named register a7
                # [81:5] free named register a2
                # [81:5] free named register a1
                # [81:5] free named register a0
            func.print.101.13.end:
        if.94.9.end:
    j loop.88.5
    loop.88.5.end:
    li a0, 0
    j .Lbaz_exit
#
# [39:15] noinline print_num(num)
func.print_num:
# allocate named register s1
    addi sp, sp, -16
    sw ra, 0(sp)
    # [39:25] num: i32 (4 B @ [s1])
    # [41:11] const buf_count = 20
    # [43:5] var buf[buf_count] i8
    # [43:9] buf: i8[20] (20 B @ [s1 + 4])
    # [43:9] zero 20 * 1 B = 20 B
    # [43:5] allocate scratch register -> t0
    # [43:5] allocate scratch register -> t1
    addi t0, s1, 4
    li t1, 5
    1:
    sw zero, 0(t0)
    addi t0, t0, 4
    addi t1, t1, -1
    bnez t1, 1b
    # [43:5] free scratch register t1
    # [43:5] free scratch register t0
    # [44:5] var n = num
    # [44:9] n: i32 (4 B @ [s1 + 24])
    # [44:9] n = num
    # [44:13] num
    # [44:13] allocate scratch register -> t0
    lw t0, 0(s1)
    # [44:13] allocate scratch register -> t1
    lw t1, 0(t0)
    sw t1, 24(s1)
    # [44:13] free scratch register t1
    # [44:13] free scratch register t0
    # [45:5] var is_negative bool
    # [45:9] is_negative: bool (1 B @ [s1 + 28])
    # [45:9] zero 1 * 1 B = 1 B
    sb zero, 28(s1)
    if.49.8:
    # [49:8] ? n < 0
    # [49:8] ? n < 0
    cmp.49.8:
    # [49:8] allocate scratch register -> t0
    lw t0, 24(s1)
    bge t0, zero, if.49.5.end
    # [49:8] free scratch register t0
    if.49.8.code:
        # [50:9] is_negative = true
        # [50:23] allocate scratch register -> t0
        li t0, 1
        sb t0, 28(s1)
        # [50:23] free scratch register t0
    if.49.5.end:
    if.52.8:
    # [52:8] ? n > 0
    # [52:8] ? n > 0
    cmp.52.8:
    # [52:8] allocate scratch register -> t0
    lw t0, 24(s1)
    bge zero, t0, if.52.5.end
    # [52:8] free scratch register t0
    if.52.8.code:
        # [53:9] n = -n
        # [53:14] -n
        # allocate scratch register -> t0
        lw t0, 24(s1)
        sub t0, zero, t0
        sw t0, 24(s1)
        # free scratch register t0
    if.52.5.end:
    # [56:5] var i = buf_count
    # [56:9] i: i32 (4 B @ [s1 + 32])
    # [56:9] i = buf_count
    # [56:13] buf_count
    # [56:13] allocate scratch register -> t0
    li t0, 20
    sw t0, 32(s1)
    # [56:13] free scratch register t0
    # [57:5] label
    loop.57.5:
        # [58:9] i = i - 1
        # [58:13] i
        # [58:17] i - 1
        # [58:17] allocate scratch register -> t0
        lw t0, 32(s1)
        addi t0, t0, -1
        sw t0, 32(s1)
        # [58:17] free scratch register t0
        # [59:9] buf[i] = i8('0' - n % 10)
        # [59:13] allocate scratch register -> t0
        # [59:13] set array index
        # [59:13] i
        lw t0, 32(s1)
        # [59:13] bounds check
        bltz t0, 1f
        # [59:13] allocate scratch register -> t1
        bltz t0, 2f
        li t1, 20
        bltu t0, t1, 2f
        1:
        li a0, 59
        j baz_bounds_panic
        2:
        # [59:13] free scratch register t1
        # [59:18] buf = i8('0' - n % 10)
        # [59:18] = expression
        # [59:18] allocate scratch register -> t1
            # [59:21] '0'
            li t1, 48
            # [59:29] t1 - n % 10
            # [59:29] allocate scratch register -> t2
            # [59:27] n
            lw t2, 24(s1)
            # [59:31] t2 % 10
            # [59:31] div const
            addi sp, sp, -16
            sw t0, 0(sp)
            sw t1, 4(sp)
            addi a0, t2, 0
            li a1, 10
            call .Lbaz_divide
            addi t2, a1, 0
            lw t0, 0(sp)
            lw t1, 4(sp)
            addi sp, sp, 16
            sub t1, t1, t2
            # [59:29] free scratch register t2
        # [59:18] allocate scratch register -> t2
        add t2, s1, t0
        sb t1, 4(t2)
        # [59:18] free scratch register t2
        # [59:18] free scratch register t1
        # [59:9] free scratch register t0
        # [60:9] n = n / 10
        # [60:13] n
        # [60:17] n / 10
        # [60:17] div const
        lw a0, 24(s1)
        li a1, 10
        call .Lbaz_divide
        sw a0, 24(s1)
        if.61.12:
        # [61:12] ? n == 0
        # [61:12] ? n == 0
        cmp.61.12:
        # [61:12] allocate scratch register -> t0
        lw t0, 24(s1)
        bne t0, zero, loop.57.5
        # [61:12] free scratch register t0
        if.61.12.code:
            # [61:19] break
        if.61.9.end:
    loop.57.5.end:
    if.64.8:
    # [64:8] ? is_negative
    # [64:8] ? is_negative
    cmp.64.8:
    # [64:8] allocate scratch register -> t0
    lbu t0, 28(s1)
    beq t0, zero, if.64.5.end
    # [64:8] free scratch register t0
    if.64.8.code:
        # [65:9] i = i - 1
        # [65:13] i
        # [65:17] i - 1
        # [65:17] allocate scratch register -> t0
        lw t0, 32(s1)
        addi t0, t0, -1
        sw t0, 32(s1)
        # [65:17] free scratch register t0
        # [66:9] buf[i] = '-'
        # [66:13] allocate scratch register -> t0
        # [66:13] set array index
        # [66:13] i
        lw t0, 32(s1)
        # [66:13] bounds check
        bltz t0, 1f
        # [66:13] allocate scratch register -> t1
        bltz t0, 2f
        li t1, 20
        bltu t0, t1, 2f
        1:
        li a0, 66
        j baz_bounds_panic
        2:
        # [66:13] free scratch register t1
        # [66:18] '-'
        # [66:18] allocate scratch register -> t1
        add t1, s1, t0
        # [66:18] allocate scratch register -> t2
        li t2, 45
        sb t2, 4(t1)
        # [66:18] free scratch register t2
        # [66:18] free scratch register t1
        # [66:9] free scratch register t0
    if.64.5.end:
    # [69:5] var write_pos
    # [69:9] write_pos: i32 (4 B @ [s1 + 36])
    # [69:9] zero 1 * 4 B = 4 B
    sw zero, 36(s1)
    # [70:5] label
    loop.70.5:
        # [71:9] buf[write_pos] = buf[i]
        # [71:13] allocate scratch register -> t0
        # [71:13] set array index
        # [71:13] write_pos
        lw t0, 36(s1)
        # [71:13] bounds check
        bltz t0, 1f
        # [71:13] allocate scratch register -> t1
        bltz t0, 2f
        li t1, 20
        bltu t0, t1, 2f
        1:
        li a0, 71
        j baz_bounds_panic
        2:
        # [71:13] free scratch register t1
        # [71:26] buf[i]
        # [71:30] allocate scratch register -> t1
        # [71:30] set array index
        # [71:30] i
        lw t1, 32(s1)
        # [71:30] bounds check
        bltz t1, 1f
        # [71:30] allocate scratch register -> t2
        bltz t1, 2f
        li t2, 20
        bltu t1, t2, 2f
        1:
        li a0, 71
        j baz_bounds_panic
        2:
        # [71:30] free scratch register t2
        # [71:26] allocate scratch register -> t2
        add t2, s1, t1
        lb t2, 4(t2)
        # [71:26] allocate scratch register -> t3
        add t3, s1, t0
        sb t2, 4(t3)
        # [71:26] free scratch register t3
        # [71:26] free scratch register t2
        # [71:26] free scratch register t1
        # [71:9] free scratch register t0
        # [72:9] write_pos = write_pos + 1
        # [72:21] write_pos
        # [72:33] write_pos + 1
        # [72:33] allocate scratch register -> t0
        lw t0, 36(s1)
        addi t0, t0, 1
        sw t0, 36(s1)
        # [72:33] free scratch register t0
        # [73:9] i = i + 1
        # [73:13] i
        # [73:17] i + 1
        # [73:17] allocate scratch register -> t0
        lw t0, 32(s1)
        addi t0, t0, 1
        sw t0, 32(s1)
        # [73:17] free scratch register t0
        if.74.12:
        # [74:12] ? i == buf_count
        # [74:12] ? i == buf_count
        cmp.74.12:
        # [74:12] allocate scratch register -> t0
        lw t0, 32(s1)
        # [74:12] allocate scratch register -> t1
        li t1, 20
        bne t0, t1, loop.70.5
        # [74:12] free scratch register t1
        # [74:12] free scratch register t0
        if.74.12.code:
            # [74:27] break
        if.74.9.end:
    loop.70.5.end:
    # [77:5] write(1, buf, write_pos)
    # [77:5] allocate named register a0
    # [77:5] allocate named register a1
    # [77:5] allocate named register a2
    # [77:11] 1
    li a0, 1
    # [77:19] write_pos
    lw a2, 36(s1)
    # [77:14] bounds check
    bltz a2, 1f
    # [77:14] allocate scratch register -> t0
    bltz a2, 2f
    li t0, 20
    bgeu t0, a2, 2f
    1:
    li a0, 77
    j baz_bounds_panic
    2:
    # [77:14] free scratch register t0
    addi a1, s1, 4
    # [77:5] allocate named register a7
    call a7, .Lbaz_write
    # [77:5] free named register a7
    # [77:5] free named register a2
    # [77:5] free named register a1
    # [77:5] free named register a0
    lw ra, 0(sp)
    addi sp, sp, 16
    ret
# free named register s1
.equ size.func.print_num, 40
#
baz_bounds_panic:
    mv s2, a0
    li a0, 2
    la a1, .Lbaz_bounds_message
    li a2, 22
    call a7, .Lbaz_write
    addi sp, sp, -16
    mv a1, sp
    li a2, 0
    la t0, .Lbaz_decimal_places
1:
    lw t1, 0(t0)
    li t2, 0
2:
    bltu s2, t1, 3f
    sub s2, s2, t1
    addi t2, t2, 1
    j 2b
3:
    or t3, a2, t2
    bnez t3, 4f
    li t3, 1
    bne t1, t3, 5f
4:
    addi t2, t2, 48
    sb t2, 0(a1)
    addi a1, a1, 1
    addi a2, a2, 1
5:
    addi t0, t0, 4
    li t3, 1
    bne t1, t3, 1b
    li t2, 10
    sb t2, 0(a1)
    addi a2, a2, 1
    mv a1, sp
    li a0, 2
    call a7, .Lbaz_write
    li a0, 255
.section .rodata
.Lbaz_bounds_message:
.ascii "panic: bounds at line "
.balign 4
.Lbaz_decimal_places:
.word 1000000000, 100000000, 10000000, 1000000, 100000, 10000, 1000, 100, 10, 1
.text
.Lbaz_exit:
1:
    ebreak
    j 1b
.Lbaz_read:
    li a3, -1
    mv a6, a1
    li a0, 0
1:
    beq a0, a2, 4f
2:
    lw a4, -12(zero)
    beq a4, a3, 2b
    li a5, 4
    beq a4, a5, 4f
    li a5, 13
    bne a4, a5, 3f
    li a4, 10
3:
    sb a4, 0(a6)
    addi a6, a6, 1
    addi a0, a0, 1
    li a5, 10
    bne a4, a5, 1b
4:
    jr a7
.Lbaz_write:
    li a3, -1
    mv a5, a1
    add a0, a1, a2
1:
    beq a5, a0, 3f
2:
    lw a4, -8(zero)
    bne a4, a3, 2b
    lbu a4, 0(a5)
    sw a4, -8(zero)
    addi a5, a5, 1
    j 1b
3:
    mv a0, a2
    jr a7
.Lbaz_divide:
    beqz a1, 5f
    srai t2, a0, 31
    srai t1, a1, 31
    xor a0, a0, t2
    sub a0, a0, t2
    xor a1, a1, t1
    sub a1, a1, t1
    xor t1, t1, t2
    li t0, 0
    li t3, 32
1:
    srli t4, a0, 31
    slli t0, t0, 1
    or t0, t0, t4
    slli a0, a0, 1
    bltu t0, a1, 2f
    sub t0, t0, a1
    ori a0, a0, 1
2:
    addi t3, t3, -1
    bnez t3, 1b
    xor a0, a0, t1
    sub a0, a0, t1
    xor a1, t0, t2
    sub a1, a1, t2
    ret
5:
    ebreak
    j 5b
.data
.balign 16
dat:
# [1:7] hello
# [1:20] i8[13]
.ascii "u r in roome\n"
# [2:5] prompt1
# [2:20] i8[12]
.ascii "enter name:\n"
# [3:5] prompt2
# [3:20] i8[20]
.ascii "that is not a name.\n"
# [4:5] prompt3
# [4:20] i8[6]
.ascii "hello "
# [5:9] dot
# [5:20] i8[1]
.ascii "."
# [6:10] nl
# [6:20] i8[1]
.ascii "\n"
# [7:7] erase
# [7:20] i8[3]
.ascii "\010 \010"
# [8:7] colon
# [8:20] i8[2]
.ascii ": "
dat.end:
.bss
.balign 16
vars:
.zero 131072
vars.end:
# free named register s0

#   removed jumps to next code: 12
#    removed unreachable jumps: 1
# removed same target branches: 0
# inverted branches over jumps: 7
#            max frames in use: 11
#              dat var padding: 6 B
#                max vars size: 136 B
