;
; generated by baz
;

default rel

section .text
bits 64
global _start
_start:

; allocate named register rbp
lea rbp, [dat]

;[1:1] dat hello = "welcome to adventure #6\n    type 'help'\n\nu r in roome\nu c me\nexits: none\ntodo: find an exit\n"
;[1:7] hello: i8[92] (92 B @ [rbp])
;[2:1] dat prompt1 = "> "
;[2:5] prompt1: i8[2] (2 B @ [rbp + 92])
;[3:1] dat prompt2 = "unknown command\n"
;[3:5] prompt2: i8[16] (16 B @ [rbp + 94])
;[4:1] dat prompt3 = "hello "
;[4:5] prompt3: i8[6] (6 B @ [rbp + 110])
;[5:1] dat dot = "."
;[5:9] dot: i8[1] (1 B @ [rbp + 116])
;[6:1] dat nl = "\n"
;[6:10] nl: i8[1] (1 B @ [rbp + 117])
;[7:1] dat erase = "\b \b"
;[7:7] erase: i8[3] (3 B @ [rbp + 118])
;[8:1] dat colon = ": "
;[8:7] colon: i8[2] (2 B @ [rbp + 121])
;[10:1] str : 128 B    fields:
;[10:1]       name :  offset :    size :  array? : array size
;[10:1]        len :       0 :       1 :      no :           
;[10:1]       data :       1 :     127 :     yes :        127
;
;
main:
;   [85:5] var counter = 0
;   [85:9] counter: i64 (8 B @ [rbp + 128])
;   [85:9] counter = 0
;   [85:19] 0
    mov qword [rbp + 128], 0
;   [86:5] var nm = str{}
;   [86:9] nm: str (128 B @ [rbp + 136])
;   [86:9] nm = str{}
;   [86:14] zero remaining fields: 128 B
;   [86:14] allocate named register rax
;   [86:14] allocate named register rdi
;   [86:14] allocate named register rcx
    xor al, al
    lea rdi, [rbp + 136]
    mov rcx, 128
    rep stosb
;   [86:14] free named register rcx
;   [86:14] free named register rdi
;   [86:14] free named register rax
;   [87:5] print(hello)
;   [80:6] print(s i8[])
    func.print.87.5:
;       [87:5] alias s -> hello
;       [81:5] write(1, s)
;       [81:5] allocate named register rdi
;       [81:5] allocate named register rsi
;       [81:5] allocate named register rdx
;       [81:11] 1
        mov rdi, 1
        mov rdx, 92
        lea rsi, [rbp]
;       [81:5] allocate named register rax
        mov rax, 1
        syscall
;       [81:5] free named register rax
;       [81:5] free named register rdx
;       [81:5] free named register rsi
;       [81:5] free named register rdi
    func.print.87.5.end:
;   [88:5] label
    loop.88.5:
;       [89:9] counter = counter + 1
;       [89:19] instructions without scratch register 1, with 3
;       [89:19] counter
;       [89:19] counter + 1
;       [89:19] src: folded constant '+ 1'
        add qword [rbp + 128], 1
;       [90:9] print_num(counter)
;       [90:9] frame capacity check (--checks=frame)
;       [90:9] allocate scratch register -> r15
;       [90:9] allocate scratch register -> r14
        lea r15, [rbp + 264]
        lea r14, [vars]
        cmp r15, r14
        jb baz_frame_overflow
        mov r14, strict qword vars.end
        cmp r15, r14
        ja baz_frame_overflow
        sub r14, r15
        mov r15, size.func.print_num
        cmp r15, r14
        ja baz_frame_overflow
;       [90:9] free scratch register r14
;       [90:9] free scratch register r15
;       [90:9] address of argument 'counter' to parameter 'num'
;       [90:9] allocate scratch register -> r15
        lea r15, [rbp + 128]
        mov qword [rbp + 264], r15
;       [90:9] free scratch register r15
;       [90:9] set function frame base
        lea rbx, [rbp + 264]
        call func.print_num
;       [91:9] print(colon)
;       [80:6] print(s i8[])
        func.print.91.9:
;           [91:9] alias s -> colon
;           [81:5] write(1, s)
;           [81:5] allocate named register rdi
;           [81:5] allocate named register rsi
;           [81:5] allocate named register rdx
;           [81:11] 1
            mov rdi, 1
            mov rdx, 2
            lea rsi, [rbp + 121]
;           [81:5] allocate named register rax
            mov rax, 1
            syscall
;           [81:5] free named register rax
;           [81:5] free named register rdx
;           [81:5] free named register rsi
;           [81:5] free named register rdi
        func.print.91.9.end:
;       [92:9] print(prompt1)
;       [80:6] print(s i8[])
        func.print.92.9:
;           [92:9] alias s -> prompt1
;           [81:5] write(1, s)
;           [81:5] allocate named register rdi
;           [81:5] allocate named register rsi
;           [81:5] allocate named register rdx
;           [81:11] 1
            mov rdi, 1
            mov rdx, 2
            lea rsi, [rbp + 92]
;           [81:5] allocate named register rax
            mov rax, 1
            syscall
;           [81:5] free named register rax
;           [81:5] free named register rdx
;           [81:5] free named register rsi
;           [81:5] free named register rdi
        func.print.92.9.end:
;       [93:12] nm.in()
;       [19:6] str.in()
        func.str.in.93.12:
;           [93:12] alias self -> nm
;           [21:5] var nbytes = 0
;           [21:9] nbytes: i64 (8 B @ [rbp + 264])
;           [21:9] nbytes = 0
;           [21:18] 0
            mov qword [rbp + 264], 0
;           [22:5] label
            loop.22.5.93.12:
                if.23.12.93.12:
;               [23:12] ? nbytes == array_length(self.data)
;               [23:12] ? nbytes == array_length(self.data)
                cmp.23.12.93.12:
;               [23:22] allocate scratch register -> r15
;                   [23:22] r15 = array_length(self.data)
;                   [23:22] = expression
;                   [23:22] array_length(self.data)
                    mov r15, 127
                cmp qword [rbp + 264], r15
;               [23:12] free scratch register r15
                je loop.22.5.93.12.end
                if.23.12.93.12.code:
;                   [23:46] break
                if.23.9.93.12.end:
                if.24.12.93.12:
;               [24:12] ? read(0, self.data, 1, nbytes) == 0
;               [24:12] ? read(0, self.data, 1, nbytes) == 0
                cmp.24.12.93.12:
;               [24:12] allocate scratch register -> r15
;                   [24:12] r15 = read(0, self.data, 1, nbytes)
;                   [24:12] = expression
;                   [24:12] read(0, self.data, 1, nbytes)
;                   [24:12] allocate named register rdi
;                   [24:12] allocate named register rsi
;                   [24:12] allocate named register rdx
;                   [24:17] 0
                    mov rdi, 0
;                   [24:31] 1
                    mov rdx, 1
;                   [24:34] allocate scratch register -> r14
;                   [24:34] nbytes
                    mov r14, qword [rbp + 264]
;                   [24:34] bounds check
;                   [24:34] lower bound (--checks=lower)
                    test r14, r14
                    js baz_bounds_panic
                    test rdx, rdx
                    js baz_bounds_panic
;                   [24:34] upper bound (--checks=upper)
;                   [24:34] allocate scratch register -> r13
                    mov r13, rdx
                    add r13, r14
                    cmp r13, 127
;                   [24:34] free scratch register r13
                    jg baz_bounds_panic
                    lea rsi, [rbp + 137]
                    add rsi, r14
;                   [24:12] free scratch register r14
;                   [24:12] allocate named register rax
                    mov rax, 0
                    syscall
                    mov r15, rax
;                   [24:12] free named register rax
;                   [24:12] free named register rdx
;                   [24:12] free named register rsi
;                   [24:12] free named register rdi
                cmp r15, 0
;               [24:12] free scratch register r15
                je loop.22.5.93.12.end
                if.24.12.93.12.code:
;                   [24:47] break
                if.24.9.93.12.end:
                if.25.12.93.12:
;               [25:12] ? self.data[nbytes] == '\x7f'
;               [25:12] ? self.data[nbytes] == '\x7f'
                cmp.25.12.93.12:
;               [25:22] allocate scratch register -> r15
;               [25:22] set array index
;               [25:22] nbytes
                mov r15, qword [rbp + 264]
;               [25:22] bounds check
;               [25:22] lower bound (--checks=lower)
                test r15, r15
                js baz_bounds_panic
;               [25:22] upper bound (--checks=upper)
                cmp r15, 127
                jge baz_bounds_panic
                cmp byte [rbp + r15 + 137], 127
;               [25:12] free scratch register r15
                jne if.25.9.93.12.end
                if.25.12.93.12.code:
                    if.26.16.93.12:
;                   [26:16] ? nbytes > 0
;                   [26:16] ? nbytes > 0
                    cmp.26.16.93.12:
                    cmp qword [rbp + 264], 0
                    jle if.26.13.93.12.end
                    if.26.16.93.12.code:
;                       [27:17] nbytes = nbytes - 1
;                       [27:26] instructions without scratch register 1, with 3
;                       [27:26] nbytes
;                       [27:26] nbytes - 1
;                       [27:26] src: folded constant '- 1'
                        sub qword [rbp + 264], 1
;                       [28:17] write(1, erase)
;                       [28:17] allocate named register rdi
;                       [28:17] allocate named register rsi
;                       [28:17] allocate named register rdx
;                       [28:23] 1
                        mov rdi, 1
                        mov rdx, 3
                        lea rsi, [rbp + 118]
;                       [28:17] allocate named register rax
                        mov rax, 1
                        syscall
;                       [28:17] free named register rax
;                       [28:17] free named register rdx
;                       [28:17] free named register rsi
;                       [28:17] free named register rdi
                    if.26.13.93.12.end:
;                   [30:13] continue
                    jmp loop.22.5.93.12
                if.25.9.93.12.end:
;               [32:9] write(1, self.data, 1, nbytes)
;               [32:9] allocate named register rdi
;               [32:9] allocate named register rsi
;               [32:9] allocate named register rdx
;               [32:15] 1
                mov rdi, 1
;               [32:29] 1
                mov rdx, 1
;               [32:32] allocate scratch register -> r15
;               [32:32] nbytes
                mov r15, qword [rbp + 264]
;               [32:32] bounds check
;               [32:32] lower bound (--checks=lower)
                test r15, r15
                js baz_bounds_panic
                test rdx, rdx
                js baz_bounds_panic
;               [32:32] upper bound (--checks=upper)
;               [32:32] allocate scratch register -> r14
                mov r14, rdx
                add r14, r15
                cmp r14, 127
;               [32:32] free scratch register r14
                jg baz_bounds_panic
                lea rsi, [rbp + 137]
                add rsi, r15
;               [32:9] free scratch register r15
;               [32:9] allocate named register rax
                mov rax, 1
                syscall
;               [32:9] free named register rax
;               [32:9] free named register rdx
;               [32:9] free named register rsi
;               [32:9] free named register rdi
                if.33.12.93.12:
;               [33:12] ? self.data[nbytes] == '\n'
;               [33:12] ? self.data[nbytes] == '\n'
                cmp.33.12.93.12:
;               [33:22] allocate scratch register -> r15
;               [33:22] set array index
;               [33:22] nbytes
                mov r15, qword [rbp + 264]
;               [33:22] bounds check
;               [33:22] lower bound (--checks=lower)
                test r15, r15
                js baz_bounds_panic
;               [33:22] upper bound (--checks=upper)
                cmp r15, 127
                jge baz_bounds_panic
                cmp byte [rbp + r15 + 137], 10
;               [33:12] free scratch register r15
                je loop.22.5.93.12.end
                if.33.12.93.12.code:
;                   [33:38] break
                if.33.9.93.12.end:
;               [34:9] nbytes = nbytes + 1
;               [34:18] instructions without scratch register 1, with 3
;               [34:18] nbytes
;               [34:18] nbytes + 1
;               [34:18] src: folded constant '+ 1'
                add qword [rbp + 264], 1
            jmp loop.22.5.93.12
            loop.22.5.93.12.end:
;           [36:5] self.len = i8(nbytes)
;           [36:16] self.len = i8(nbytes)
;           [36:16] = expression
;           [36:16] instructions without scratch register 2, with 2
;           [36:19] nbytes
;           [36:19] allocate scratch register -> r15
            mov r15b, byte [rbp + 264]
            mov byte [rbp + 136], r15b
;           [36:19] free scratch register r15
        func.str.in.93.12.end:
        if.94.12:
;       [94:12] ? nm.len <= 4
;       [94:12] ? nm.len <= 4
        cmp.94.12:
        cmp byte [rbp + 136], 4
        jg if.94.9.else
        if.94.12.code:
;           [95:13] print(prompt2)
;           [80:6] print(s i8[])
            func.print.95.13:
;               [95:13] alias s -> prompt2
;               [81:5] write(1, s)
;               [81:5] allocate named register rdi
;               [81:5] allocate named register rsi
;               [81:5] allocate named register rdx
;               [81:11] 1
                mov rdi, 1
                mov rdx, 16
                lea rsi, [rbp + 94]
;               [81:5] allocate named register rax
                mov rax, 1
                syscall
;               [81:5] free named register rax
;               [81:5] free named register rdx
;               [81:5] free named register rsi
;               [81:5] free named register rdi
            func.print.95.13.end:
;           [96:13] continue
            jmp loop.88.5
        if.94.9.else:
;           [98:13] print(prompt3)
;           [80:6] print(s i8[])
            func.print.98.13:
;               [98:13] alias s -> prompt3
;               [81:5] write(1, s)
;               [81:5] allocate named register rdi
;               [81:5] allocate named register rsi
;               [81:5] allocate named register rdx
;               [81:11] 1
                mov rdi, 1
                mov rdx, 6
                lea rsi, [rbp + 110]
;               [81:5] allocate named register rax
                mov rax, 1
                syscall
;               [81:5] free named register rax
;               [81:5] free named register rdx
;               [81:5] free named register rsi
;               [81:5] free named register rdi
            func.print.98.13.end:
;           [99:16] nm.out()
;           [15:6] str.out()
            func.str.out.99.16:
;               [99:16] alias self -> nm
;               [16:5] write(1, self.data, self.len)
;               [16:5] allocate named register rdi
;               [16:5] allocate named register rsi
;               [16:5] allocate named register rdx
;               [16:11] 1
                mov rdi, 1
;               [16:25] self.len
                movsx rdx, byte [rbp + 136]
;               [16:14] bounds check
;               [16:14] lower bound (--checks=lower)
                test rdx, rdx
                js baz_bounds_panic
;               [16:14] upper bound (--checks=upper)
                cmp rdx, 127
                jg baz_bounds_panic
                lea rsi, [rbp + 137]
;               [16:5] allocate named register rax
                mov rax, 1
                syscall
;               [16:5] free named register rax
;               [16:5] free named register rdx
;               [16:5] free named register rsi
;               [16:5] free named register rdi
            func.str.out.99.16.end:
;           [100:13] print(dot)
;           [80:6] print(s i8[])
            func.print.100.13:
;               [100:13] alias s -> dot
;               [81:5] write(1, s)
;               [81:5] allocate named register rdi
;               [81:5] allocate named register rsi
;               [81:5] allocate named register rdx
;               [81:11] 1
                mov rdi, 1
                mov rdx, 1
                lea rsi, [rbp + 116]
;               [81:5] allocate named register rax
                mov rax, 1
                syscall
;               [81:5] free named register rax
;               [81:5] free named register rdx
;               [81:5] free named register rsi
;               [81:5] free named register rdi
            func.print.100.13.end:
;           [101:13] print(nl)
;           [80:6] print(s i8[])
            func.print.101.13:
;               [101:13] alias s -> nl
;               [81:5] write(1, s)
;               [81:5] allocate named register rdi
;               [81:5] allocate named register rsi
;               [81:5] allocate named register rdx
;               [81:11] 1
                mov rdi, 1
                mov rdx, 1
                lea rsi, [rbp + 117]
;               [81:5] allocate named register rax
                mov rax, 1
                syscall
;               [81:5] free named register rax
;               [81:5] free named register rdx
;               [81:5] free named register rsi
;               [81:5] free named register rdi
            func.print.101.13.end:
        if.94.9.end:
    jmp loop.88.5
    loop.88.5.end:
;
;[39:15] noinline print_num(num)
func.print_num:
;   [39:25] num: i64 (8 B @ [rbx])
;   [41:11] const buf_count = 20
;   [43:5] var buf = i8[buf_count]{}
;   [43:9] buf: i8[20] (20 B @ [rbx + 8])
;   [43:9] buf = i8[buf_count]{}
;   [43:15] zero remaining elements: 20 * 1 B = 20 B
;   [43:15] size <= 32 B, use mov
    mov qword [rbx + 8], 0
    mov qword [rbx + 16], 0
    mov dword [rbx + 24], 0
;   [44:5] var n = num
;   [44:9] n: i64 (8 B @ [rbx + 32])
;   [44:9] n = num
;   [44:13] num
;   [44:13] allocate scratch register -> r15
    mov r15, qword [rbx]
;   [44:13] allocate scratch register -> r14
    mov r14, qword [r15]
    mov qword [rbx + 32], r14
;   [44:13] free scratch register r14
;   [44:13] free scratch register r15
;   [45:5] var is_negative = false
;   [45:9] is_negative: bool (1 B @ [rbx + 40])
;   [45:9] is_negative = false
    mov byte [rbx + 40], 0
    if.49.8:
;   [49:8] ? n < 0
;   [49:8] ? n < 0
    cmp.49.8:
    cmp qword [rbx + 32], 0
    jge if.49.5.end
    if.49.8.code:
;       [50:9] is_negative = true
        mov byte [rbx + 40], 1
    if.49.5.end:
    if.52.8:
;   [52:8] ? n > 0
;   [52:8] ? n > 0
    cmp.52.8:
    cmp qword [rbx + 32], 0
    jle if.52.5.end
    if.52.8.code:
;       [53:9] n = -n
;       [53:13] instructions without scratch register 1, with 3
;       [53:14] -n
        neg qword [rbx + 32]
    if.52.5.end:
;   [56:5] var i = buf_count
;   [56:9] i: i64 (8 B @ [rbx + 48])
;   [56:9] i = buf_count
;   [56:13] buf_count
    mov qword [rbx + 48], 20
;   [57:5] label
    loop.57.5:
;       [58:9] i = i - 1
;       [58:13] instructions without scratch register 1, with 3
;       [58:13] i
;       [58:13] i - 1
;       [58:13] src: folded constant '- 1'
        sub qword [rbx + 48], 1
;       [59:9] buf[i] = i8('0' - n % 10)
;       [59:13] allocate scratch register -> r15
;       [59:13] set array index
;       [59:13] i
        mov r15, qword [rbx + 48]
;       [59:13] bounds check
;       [59:13] lower bound (--checks=lower)
        test r15, r15
        js baz_bounds_panic
;       [59:13] upper bound (--checks=upper)
        cmp r15, 20
        jge baz_bounds_panic
;       [59:18] buf = i8('0' - n % 10)
;       [59:18] = expression
;       [59:18] allocate scratch register -> r14
;           [59:21] r14 = 48
;           [59:21] src: folded constant '+ '0''
            mov r14, 48
;           [59:29] r14 - n % 10
;           [59:29] src: expression
;           [59:29] allocate scratch register -> r13
;           [59:27] n
            mov r13, qword [rbx + 32]
;           [59:31] r13 % 10
;           [59:31] src: constant
;           [59:31] allocate named register rax
            mov rax, r13
;           [59:31] allocate named register rdx
            cqo
;           [59:31] allocate scratch register -> r12
            mov r12, 10
            idiv r12
;           [59:31] free scratch register r12
            mov r13, rdx
;           [59:31] free named register rdx
;           [59:31] free named register rax
            sub r14, r13
;           [59:29] free scratch register r13
        mov byte [rbx + r15 + 8], r14b
;       [59:18] free scratch register r14
;       [59:9] free scratch register r15
;       [60:9] n = n / 10
;       [60:13] instructions without scratch register 5, with 7
;       [60:13] n
;       [60:17] n / 10
;       [60:17] src: constant
;       [60:17] allocate named register rax
        mov rax, qword [rbx + 32]
;       [60:17] allocate named register rdx
        cqo
;       [60:17] allocate scratch register -> r15
        mov r15, 10
        idiv r15
;       [60:17] free scratch register r15
        mov qword [rbx + 32], rax
;       [60:17] free named register rdx
;       [60:17] free named register rax
        if.61.12:
;       [61:12] ? n == 0
;       [61:12] ? n == 0
        cmp.61.12:
        cmp qword [rbx + 32], 0
        jne loop.57.5
        if.61.12.code:
;           [61:19] break
        if.61.9.end:
    loop.57.5.end:
    if.64.8:
;   [64:8] ? is_negative
;   [64:8] ? shorthand: is_negative
    cmp.64.8:
    cmp byte [rbx + 40], 0
    je if.64.5.end
    if.64.8.code:
;       [65:9] i = i - 1
;       [65:13] instructions without scratch register 1, with 3
;       [65:13] i
;       [65:13] i - 1
;       [65:13] src: folded constant '- 1'
        sub qword [rbx + 48], 1
;       [66:9] buf[i] = '-'
;       [66:13] allocate scratch register -> r15
;       [66:13] set array index
;       [66:13] i
        mov r15, qword [rbx + 48]
;       [66:13] bounds check
;       [66:13] lower bound (--checks=lower)
        test r15, r15
        js baz_bounds_panic
;       [66:13] upper bound (--checks=upper)
        cmp r15, 20
        jge baz_bounds_panic
;       [66:18] '-'
        mov byte [rbx + r15 + 8], 45
;       [66:9] free scratch register r15
    if.64.5.end:
;   [69:5] var write_pos = 0
;   [69:9] write_pos: i64 (8 B @ [rbx + 56])
;   [69:9] write_pos = 0
;   [69:21] 0
    mov qword [rbx + 56], 0
;   [70:5] label
    loop.70.5:
;       [71:9] buf[write_pos] = buf[i]
;       [71:13] allocate scratch register -> r15
;       [71:13] set array index
;       [71:13] write_pos
        mov r15, qword [rbx + 56]
;       [71:13] bounds check
;       [71:13] lower bound (--checks=lower)
        test r15, r15
        js baz_bounds_panic
;       [71:13] upper bound (--checks=upper)
        cmp r15, 20
        jge baz_bounds_panic
;       [71:26] buf[i]
;       [71:30] allocate scratch register -> r14
;       [71:30] set array index
;       [71:30] i
        mov r14, qword [rbx + 48]
;       [71:30] bounds check
;       [71:30] lower bound (--checks=lower)
        test r14, r14
        js baz_bounds_panic
;       [71:30] upper bound (--checks=upper)
        cmp r14, 20
        jge baz_bounds_panic
;       [71:26] allocate scratch register -> r13
        mov r13b, byte [rbx + r14 + 8]
        mov byte [rbx + r15 + 8], r13b
;       [71:26] free scratch register r13
;       [71:26] free scratch register r14
;       [71:9] free scratch register r15
;       [72:9] write_pos = write_pos + 1
;       [72:21] instructions without scratch register 1, with 3
;       [72:21] write_pos
;       [72:21] write_pos + 1
;       [72:21] src: folded constant '+ 1'
        add qword [rbx + 56], 1
;       [73:9] i = i + 1
;       [73:13] instructions without scratch register 1, with 3
;       [73:13] i
;       [73:13] i + 1
;       [73:13] src: folded constant '+ 1'
        add qword [rbx + 48], 1
        if.74.12:
;       [74:12] ? i == buf_count
;       [74:12] ? i == buf_count
        cmp.74.12:
        cmp qword [rbx + 48], 20
        jne loop.70.5
        if.74.12.code:
;           [74:27] break
        if.74.9.end:
    loop.70.5.end:
;   [77:5] write(1, buf, write_pos)
;   [77:5] allocate named register rdi
;   [77:5] allocate named register rsi
;   [77:5] allocate named register rdx
;   [77:11] 1
    mov rdi, 1
;   [77:19] write_pos
    mov rdx, qword [rbx + 56]
;   [77:14] bounds check
;   [77:14] lower bound (--checks=lower)
    test rdx, rdx
    js baz_bounds_panic
;   [77:14] upper bound (--checks=upper)
    cmp rdx, 20
    jg baz_bounds_panic
    lea rsi, [rbx + 8]
;   [77:5] allocate named register rax
    mov rax, 1
    syscall
;   [77:5] free named register rax
;   [77:5] free named register rdx
;   [77:5] free named register rsi
;   [77:5] free named register rdi
    ret
size.func.print_num equ 64
; frame overflow handler (--checks=frame)
baz_frame_overflow:
;    print message to stderr
    mov rax, 1
    mov rdi, 2
    lea rsi, [msg_frame_overflow]
    mov rdx, msg_frame_overflow_len
    syscall
;    exit with error code 255
    mov rax, 60
    mov rdi, 255
    syscall
section .rodata
msg_frame_overflow:
db `panic: frame overflow\n`
msg_frame_overflow_len equ $ - msg_frame_overflow
section .text
; bounds failure handler (--checks=upper or --checks=lower)
baz_bounds_panic:
;    exit with error code 255
    mov rax, 60
    mov rdi, 255
    syscall

section .data
align 16
dat:
;[1:7] hello
;[1:15] i8[92]
db `welcome to adventure #6\n    type 'help'\n\nu r in roome\nu c me\nexits: none\ntodo: find an exit\n`
;[2:5] prompt1
;[2:15] i8[2]
db `> `
;[3:5] prompt2
;[3:15] i8[16]
db `unknown command\n`
;[4:5] prompt3
;[4:15] i8[6]
db `hello `
;[5:9] dot
;[5:15] i8[1]
db `.`
;[6:10] nl
;[6:15] i8[1]
db `\n`
;[7:7] erase
;[7:15] i8[3]
db `\b \b`
;[8:7] colon
;[8:15] i8[2]
db `: `
dat.end:

section .bss.vars nobits alloc write
align 16
vars:
resb 65536
vars.end:
; free named register rbp

;   removed jumps to next code: 11
;    removed unreachable jumps: 1
; removed same target branches: 0
; inverted branches over jumps: 7

; max scratch registers in use: 4
;            max frames in use: 11
;              dat var padding: 5 B
;                max vars size: 144 B
