#
# generated by baz
#

.option norvc
.option norelax

.text
.globl _start
_start:

# allocate named register s0
la s0, dat

# load stack pointer to 0x80:0000
lui sp, 2048

# [6:1] point : 8 B    fields:
# [6:1]       name :  offset :    size :  array? : array size
# [6:1]          x :       0 :       4 :      no :           
# [6:1]          y :       4 :       4 :      no :           
#
# [8:1] object : 12 B    fields:
# [8:1]       name :  offset :    size :  array? : array size
# [8:1]        pos :       0 :       8 :      no :           
# [8:1]      color :       8 :       4 :      no :           
#
# [10:1] world : 32 B    fields:
# [10:1]       name :  offset :    size :  array? : array size
# [10:1]  locations :       0 :      32 :     yes :          8
#
#
main:
    # [39:5] var x = 1
    # [39:9] x: i32 (4 B @ [s0])
    # [39:9] x = 1
    # [39:13] 1
    # [39:13] allocate scratch register -> t0
    li t0, 1
    sw t0, 0(s0)
    # [39:13] free scratch register t0
    # [40:5] var arr[4] i32
    # [40:9] arr: i32[4] (16 B @ [s0 + 4])
    # [40:9] zero 4 * 4 B = 16 B
    sw zero, 4(s0)
    sw zero, 8(s0)
    sw zero, 12(s0)
    sw zero, 16(s0)
    # [41:5] var arr3[] = { 3, 5 }
    # [41:9] arr3: i32[2] (8 B @ [s0 + 20])
    # [41:9] arr3= { 3, 5 }
    # [41:18] allocate scratch register -> t0
    li t0, 3
    sw t0, 20(s0)
    li t0, 5
    sw t0, 24(s0)
    # [41:18] free scratch register t0
    # [42:5] var o3[2] object
    # [42:9] o3: object[2] (24 B @ [s0 + 28])
    # [42:9] zero 2 * 12 B = 24 B
    sw zero, 28(s0)
    sw zero, 32(s0)
    sw zero, 36(s0)
    sw zero, 40(s0)
    sw zero, 44(s0)
    sw zero, 48(s0)
    # [43:5] var worlds[8] world
    # [43:9] worlds: world[8] (256 B @ [s0 + 52])
    # [43:9] zero 8 * 32 B = 256 B
    # [43:5] zero loop of 4-byte accesses: start word aligned
    # [43:5] allocate scratch register -> t0
    addi t0, s0, 52
    # [43:5] allocate scratch register -> t1
    # [43:5] zero 4-byte words
    li t1, 64
    1:
    sw zero, 0(t0)
    addi t0, t0, 4
    addi t1, t1, -1
    bnez t1, 1b
    # [43:5] free scratch register t1
    # [43:5] free scratch register t0
    # [46:5] assert(arr3[0] + 2 == 3 + 0 + 2)
    # [46:12] allocate scratch register -> t0
    # [46:12] ? arr3[0] + 2 == 3 + 0 + 2
    # [46:12] ? arr3[0] + 2 == 3 + 0 + 2
    cmp.46.12:
    # [46:12] allocate scratch register -> t1
        # [46:12] arr3[0]
        lw t1, 20(s0)
        # [46:12] t1 + 2
        # [46:12] src: folded constant '+ 2'
        addi t1, t1, 2
    # [46:27] src: folded constant '3 + 0 + 2'
    xori t0, t1, 5
    sltiu t0, t0, 1
    # [46:12] free scratch register t1
    bool.46.12.end:
    # [12:6] assert(ok bool)
    func.assert.46.5:
        # [46:5] alias ok -> t0
        if.12.27.46.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.46.5:
        bne t0, zero, if.12.24.46.5.end
        if.12.27.46.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.46.5.end:
        # [46:5] free scratch register t0
    func.assert.46.5.end:
    # [49:5] assert(array_length(arr3) == 2)
    # [49:12] allocate scratch register -> t0
    # [49:12] ? array_length(arr3) == 2
    # [49:12] ? array_length(arr3) == 2
    cmp.49.12:
    # [49:12] allocate scratch register -> t1
        # [49:12] t1 = array_length(arr3)
        # [49:12] = expression
        # [49:12] array_length(arr3)
        li t1, 2
    xori t0, t1, 2
    sltiu t0, t0, 1
    # [49:12] free scratch register t1
    bool.49.12.end:
    # [12:6] assert(ok bool)
    func.assert.49.5:
        # [49:5] alias ok -> t0
        if.12.27.49.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.49.5:
        bne t0, zero, if.12.24.49.5.end
        if.12.27.49.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.49.5.end:
        # [49:5] free scratch register t0
    func.assert.49.5.end:
    # [52:5] arr[1] = 2
    # [52:14] 2
    # [52:14] allocate scratch register -> t0
    li t0, 2
    sw t0, 8(s0)
    # [52:14] free scratch register t0
    # [53:5] assert(arr[1] == 2)
    # [53:12] allocate scratch register -> t0
    # [53:12] ? arr[1] == 2
    # [53:12] ? arr[1] == 2
    cmp.53.12:
    lw t0, 8(s0)
    xori t0, t0, 2
    sltiu t0, t0, 1
    bool.53.12.end:
    # [12:6] assert(ok bool)
    func.assert.53.5:
        # [53:5] alias ok -> t0
        if.12.27.53.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.53.5:
        bne t0, zero, if.12.24.53.5.end
        if.12.27.53.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.53.5.end:
        # [53:5] free scratch register t0
    func.assert.53.5.end:
    # [56:5] o3[1].pos.y = 74
    # [56:19] 74
    # [56:19] allocate scratch register -> t0
    li t0, 74
    sw t0, 44(s0)
    # [56:19] free scratch register t0
    # [57:5] assert(o3[1].pos.y == 74)
    # [57:12] allocate scratch register -> t0
    # [57:12] ? o3[1].pos.y == 74
    # [57:12] ? o3[1].pos.y == 74
    cmp.57.12:
    lw t0, 44(s0)
    xori t0, t0, 74
    sltiu t0, t0, 1
    bool.57.12.end:
    # [12:6] assert(ok bool)
    func.assert.57.5:
        # [57:5] alias ok -> t0
        if.12.27.57.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.57.5:
        bne t0, zero, if.12.24.57.5.end
        if.12.27.57.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.57.5.end:
        # [57:5] free scratch register t0
    func.assert.57.5.end:
    # [60:5] worlds[1].locations[1] = 0xffee
    # [60:30] 0xffee
    # [60:30] allocate scratch register -> t0
    li t0, 65518
    sw t0, 88(s0)
    # [60:30] free scratch register t0
    # [64:5] var ix = 1
    # [64:9] ix: i32 (4 B @ [s0 + 308])
    # [64:9] ix = 1
    # [64:14] 1
    # [64:14] allocate scratch register -> t0
    li t0, 1
    sw t0, 308(s0)
    # [64:14] free scratch register t0
    # [65:5] arr[ix + 1] = arr[ix]
    # [65:9] allocate scratch register -> t0
    # [65:9] set array index
    # [65:9] ix
    lw t0, 308(s0)
    # [65:9] t0 + 1
    # [65:9] src: folded constant '+ 1'
    addi t0, t0, 1
    # [65:19] arr[ix]
    # [65:23] allocate scratch register -> t1
    # [65:23] set array index
    # [65:23] ix
    lw t1, 308(s0)
    # [65:19] allocate scratch register -> t2
    slli t2, t1, 2
    add t2, t2, s0
    lw t2, 4(t2)
    # [65:19] allocate scratch register -> t3
    slli t3, t0, 2
    add t3, t3, s0
    sw t2, 4(t3)
    # [65:19] free scratch register t3
    # [65:19] free scratch register t2
    # [65:19] free scratch register t1
    # [65:5] free scratch register t0
    # [66:5] worlds[ix].locations[1] = 0xffee
    # [66:12] allocate scratch register -> t0
    # [66:12] set array index
    # [66:12] ix
    lw t0, 308(s0)
    # [66:31] 0xffee
    # [66:31] allocate scratch register -> t1
    slli t1, t0, 5
    add t1, t1, s0
    # [66:31] allocate scratch register -> t2
    li t2, 65518
    sw t2, 56(t1)
    # [66:31] free scratch register t2
    # [66:31] free scratch register t1
    # [66:5] free scratch register t0
    # [69:5] var a = -x
    # [69:9] a: i32 (4 B @ [s0 + 312])
    # [69:9] a = -x
    # [69:13] allocate scratch register -> t0
    # [69:14] -x
    lw t0, 0(s0)
    sub t0, zero, t0
    sw t0, 312(s0)
    # [69:13] free scratch register t0
    # [70:5] a = ~x
    # [70:9] allocate scratch register -> t0
    # [70:10] ~x
    lw t0, 0(s0)
    xori t0, t0, -1
    sw t0, 312(s0)
    # [70:9] free scratch register t0
    # [73:5] var b i8
    # [73:9] b: i8 (1 B @ [s0 + 316])
    # [73:9] zero 1 * 1 B = 1 B
    sb zero, 316(s0)
    # [74:5] b = i8(x - 1)
    # [74:9] b = i8(x - 1)
    # [74:9] = expression
    # [74:12] allocate scratch register -> t0
    # [74:12] x
    lw t0, 0(s0)
    # [74:12] t0 - 1
    # [74:12] src: folded constant '- 1'
    addi t0, t0, -1
    sb t0, 316(s0)
    # [74:12] free scratch register t0
    # [77:5] var p1 point = {-x, -a}
    # [77:9] p1: point (8 B @ [s0 + 320])
    # [77:9] p1 = {-x, -a}
    # [77:21] copy field 'x'
    # [77:21] allocate scratch register -> t0
    lw t0, 0(s0)
    sub t0, zero, t0
    sw t0, 320(s0)
    # [77:21] free scratch register t0
    # [77:25] copy field 'y'
    # [77:25] allocate scratch register -> t0
    lw t0, 312(s0)
    sub t0, zero, t0
    sw t0, 324(s0)
    # [77:25] free scratch register t0
    # [80:5] arr[ix] = ~inv(arr[ix - 1])
    # [80:9] allocate scratch register -> t0
    # [80:9] set array index
    # [80:9] ix
    lw t0, 308(s0)
    # [80:16] arr = ~inv(arr[ix - 1])
    # [80:16] = expression
    # [80:16] ~inv(arr[ix - 1])
    # [80:16] allocate scratch register -> t1
    # [80:24] allocate scratch register -> t2
    # [80:24] set array index
    # [80:24] ix
    lw t2, 308(s0)
    # [80:24] t2 - 1
    # [80:24] src: folded constant '- 1'
    addi t2, t2, -1
    # [14:6] inv(i i32) res i32
    func.inv.80.16:
        # [80:16] alias res -> t1
        # [80:16] alias i -> arr
        # [15:5] res = ~i
        # [15:12] ~i
        slli t1, t2, 2
        add t1, t1, s0
        lw t1, 4(t1)
        xori t1, t1, -1
        # [80:16] free scratch register t2
    func.inv.80.16.end:
    xori t1, t1, -1
    # [80:16] allocate scratch register -> t2
    slli t2, t0, 2
    add t2, t2, s0
    sw t1, 4(t2)
    # [80:16] free scratch register t2
    # [80:16] free scratch register t1
    # [80:5] free scratch register t0
    # [83:5] assert(x == 1)
    # [83:12] allocate scratch register -> t0
    # [83:12] ? x == 1
    # [83:12] ? x == 1
    cmp.83.12:
    lw t0, 0(s0)
    xori t0, t0, 1
    sltiu t0, t0, 1
    bool.83.12.end:
    # [12:6] assert(ok bool)
    func.assert.83.5:
        # [83:5] alias ok -> t0
        if.12.27.83.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.83.5:
        bne t0, zero, if.12.24.83.5.end
        if.12.27.83.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.83.5.end:
        # [83:5] free scratch register t0
    func.assert.83.5.end:
    # [86:5] var eq bool = x == 1
    # [86:9] eq: bool (1 B @ [s0 + 328])
    # [86:9] eq = x == 1
    # [86:19] ? x == 1
    # [86:19] ? x == 1
    cmp.86.19:
    # [86:19] allocate scratch register -> t0
    lw t0, 0(s0)
    xori t0, t0, 1
    sltiu t0, t0, 1
    sb t0, 328(s0)
    # [86:19] free scratch register t0
    bool.86.19.end:
    # [87:5] assert(eq)
    # [87:12] allocate scratch register -> t0
    # [87:12] ? eq
    # [87:12] ? shorthand: eq
    cmp.87.12:
    lbu t0, 328(s0)
    bool.87.12.end:
    # [12:6] assert(ok bool)
    func.assert.87.5:
        # [87:5] alias ok -> t0
        if.12.27.87.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.87.5:
        bne t0, zero, if.12.24.87.5.end
        if.12.27.87.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.87.5.end:
        # [87:5] free scratch register t0
    func.assert.87.5.end:
    # [90:5] a = x * 10
    # [90:9] allocate scratch register -> t0
    # [90:9] x
    lw t0, 0(s0)
    # [90:9] t0 * 10
    # [90:9] src: folded constant '* 10'
    # [90:9] allocate scratch register -> t1
    slli t1, t0, 2
    add t0, t1, t0
    slli t0, t0, 1
    # [90:9] free scratch register t1
    sw t0, 312(s0)
    # [90:9] free scratch register t0
    # [93:5] a = arr[ix]
    # [93:9] arr[ix]
    # [93:13] allocate scratch register -> t0
    # [93:13] set array index
    # [93:13] ix
    lw t0, 308(s0)
    # [93:9] allocate scratch register -> t1
    slli t1, t0, 2
    add t1, t1, s0
    lw t1, 4(t1)
    sw t1, 312(s0)
    # [93:9] free scratch register t1
    # [93:9] free scratch register t0
    # [96:5] o3[ix] = object_init()
    # [96:8] allocate scratch register -> t0
    # [96:8] set array index
    # [96:8] ix
    lw t0, 308(s0)
    # [96:8] allocate scratch register -> t1
    slli t1, t0, 2
    sub t0, t1, t0
    slli t0, t0, 2
    # [96:8] free scratch register t1
    # [96:14] object_init()
    # [96:14] allocate scratch register -> t1
    # [96:14] address of result element in array 'o3'
    add t1, s0, t0
    addi t1, t1, 28
    # [18:6] object_init() res object
    func.object_init.96.14:
        # [96:14] alias res -> o3
        # [19:5] res.pos.x = 2
        # [19:17] 2
        # [19:17] allocate scratch register -> t2
        li t2, 2
        sw t2, 0(t1)
        # [19:17] free scratch register t2
        # [20:5] res.pos.y = 74
        # [20:17] 74
        # [20:17] allocate scratch register -> t2
        li t2, 74
        sw t2, 4(t1)
        # [20:17] free scratch register t2
        # [21:5] res.color = 0xffffff
        # [21:17] 0xffffff
        # [21:17] allocate scratch register -> t2
        li t2, 16777215
        sw t2, 8(t1)
        # [21:17] free scratch register t2
    func.object_init.96.14.end:
    # [96:14] free scratch register t1
    # [96:5] free scratch register t0
    # [101:5] var buf[20] i8
    # [101:9] buf: i8[20] (20 B @ [s0 + 329])
    # [101:9] zero 20 * 1 B = 20 B
    # [101:5] zero 1 + 2 + 4 x 4 + 1 B: start 1 B past a word boundary, widest aligned access at each offset
    sb zero, 329(s0)
    sh zero, 330(s0)
    sw zero, 332(s0)
    sw zero, 336(s0)
    sw zero, 340(s0)
    sw zero, 344(s0)
    sb zero, 348(s0)
    # [104:5] var q point = p1
    # [104:9] q: point (8 B @ [s0 + 352])
    # [104:9] q = p1
    # [104:19] allocate scratch register -> t0
    lw t0, 320(s0)
    sw t0, 352(s0)
    lw t0, 324(s0)
    sw t0, 356(s0)
    # [104:19] free scratch register t0
    # [105:5] assert(equal(p1, q))
    # [105:12] allocate scratch register -> t0
    # [105:12] ? equal(p1, q)
    # [105:12] ? shorthand: equal(p1, q)
    cmp.105.12:
        # [105:12] equal(p1, q)
        # [105:12] allocate scratch register -> t1
        # [105:12] allocate scratch register -> t2
        # [105:12] allocate scratch register -> t3
        # [105:12] t1: source, t2: destination, t3: count
        # [105:18] p1
        addi t1, s0, 320
        # [105:22] q
        addi t2, s0, 352
        # [105:12] allocate scratch register -> t4
        # [105:12] t0: left value/result, t4: right value
        # [105:12] stop at first mismatch
        # [105:12] 4-byte accesses: type 4-byte aligned, addresses not proven more aligned
        # [105:12] compare 4-byte words
        li t3, 2
        1:
        lw t0, 0(t1)
        lw t4, 0(t2)
        bne t0, t4, 5f
        addi t1, t1, 4
        addi t2, t2, 4
        addi t3, t3, -1
        bnez t3, 1b
        # [105:12] all matched or empty: true
        li t0, 1
        j 6f
        5:
        # [105:12] mismatch: false
        li t0, 0
        6:
        # [105:12] free scratch register t4
        # [105:12] free scratch register t3
        # [105:12] free scratch register t2
        # [105:12] free scratch register t1
    bool.105.12.end:
    # [12:6] assert(ok bool)
    func.assert.105.5:
        # [105:5] alias ok -> t0
        if.12.27.105.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.105.5:
        bne t0, zero, if.12.24.105.5.end
        if.12.27.105.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.105.5.end:
        # [105:5] free scratch register t0
    func.assert.105.5.end:
    # [108:5] array_copy(worlds[1].locations, worlds[0].locations, array_length(worlds[0].locations))
    # [108:5] allocate scratch register -> t0
    # [108:5] allocate scratch register -> t1
    # [108:5] allocate scratch register -> t2
    # [108:5] t0: source, t1: destination, t2: count
    # [109:16] array_length(worlds[0].locations)
    # [109:16] t2 = array_length(worlds[0].locations)
    # [109:16] = expression
    # [109:16] array_length(worlds[0].locations)
    li t2, 8
    # [108:16] worlds[1].locations
    addi t0, s0, 84
    # [108:37] worlds[0].locations
    addi t1, s0, 52
    # [108:5] t2: elements to bytes (4 bytes/element)
    slli t2, t2, 2
    # [108:5] allocate scratch register -> t3
    # [108:5] 4-byte accesses: type 4-byte aligned, addresses not proven more aligned
    # [108:5] allocate scratch register -> t4
    # [108:5] t4: words, t2: tail bytes
    # [108:5] split bytes into chunks and tail; skip loop if none
    srli t4, t2, 2
    andi t2, t2, 3
    beqz t4, 2f
    # [108:5] copy 4-byte words
    1:
    lw t3, 0(t0)
    sw t3, 0(t1)
    addi t0, t0, 4
    addi t1, t1, 4
    addi t4, t4, -1
    bnez t4, 1b
    2:
    # [108:5] copy optional 2-byte tail
    andi t4, t2, 2
    beqz t4, 3f
    lhu t3, 0(t0)
    sh t3, 0(t1)
    addi t0, t0, 2
    addi t1, t1, 2
    3:
    andi t2, t2, 1
    # [108:5] copy optional final byte
    beqz t2, 4f
    lbu t3, 0(t0)
    sb t3, 0(t1)
    4:
    # [108:5] free scratch register t4
    # [108:5] free scratch register t3
    # [108:5] free scratch register t2
    # [108:5] free scratch register t1
    # [108:5] free scratch register t0
    # [112:5] print_num(a)
    # [112:5] address of argument 'a' to parameter 'num'
    # [112:5] allocate scratch register -> t0
    addi t0, s0, 312
    sw t0, 360(s0)
    # [112:5] free scratch register t0
    # [112:5] set function frame base
    addi s1, s0, 360
    call func.print_num
    # [114:5] assert(buf[0] == 0)
    # [114:12] allocate scratch register -> t0
    # [114:12] ? buf[0] == 0
    # [114:12] ? buf[0] == 0
    cmp.114.12:
    lb t0, 329(s0)
    sltiu t0, t0, 1
    bool.114.12.end:
    # [12:6] assert(ok bool)
    func.assert.114.5:
        # [114:5] alias ok -> t0
        if.12.27.114.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.114.5:
        bne t0, zero, if.12.24.114.5.end
        if.12.27.114.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.114.5.end:
        # [114:5] free scratch register t0
    func.assert.114.5.end:
    # [115:5] assert(b == 0)
    # [115:12] allocate scratch register -> t0
    # [115:12] ? b == 0
    # [115:12] ? b == 0
    cmp.115.12:
    lb t0, 316(s0)
    sltiu t0, t0, 1
    bool.115.12.end:
    # [12:6] assert(ok bool)
    func.assert.115.5:
        # [115:5] alias ok -> t0
        if.12.27.115.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.115.5:
        bne t0, zero, if.12.24.115.5.end
        if.12.27.115.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.115.5.end:
        # [115:5] free scratch register t0
    func.assert.115.5.end:
    # [116:5] assert(p1.x == -1)
    # [116:12] allocate scratch register -> t0
    # [116:12] ? p1.x == -1
    # [116:12] ? p1.x == -1
    cmp.116.12:
    lw t0, 320(s0)
    xori t0, t0, -1
    sltiu t0, t0, 1
    bool.116.12.end:
    # [12:6] assert(ok bool)
    func.assert.116.5:
        # [116:5] alias ok -> t0
        if.12.27.116.5:
        # [12:27] ? not ok
        # [12:27] ? shorthand: not ok
        cmp.12.27.116.5:
        bne t0, zero, if.12.24.116.5.end
        if.12.27.116.5.code:
            # [12:34] exit(1)
            # [12:34] allocate named register a0
            # [12:39] 1
            li a0, 1
            j .Lbaz_exit
            # [12:34] free named register a0
        if.12.24.116.5.end:
        # [116:5] free scratch register t0
    func.assert.116.5.end:
    # [120:5] exit(0)
    # [120:5] allocate named register a0
    # [120:10] 0
    li a0, 0
    j .Lbaz_exit
    # [120:5] free named register a0
#
# [24:15] noinline print_num(num)
func.print_num:
# allocate named register s1
    addi sp, sp, -16
    sw ra, 0(sp)
    # [24:25] num: i32 (4 B @ [s1])
    # [25:5] var buf[20] i8
    # [25:9] buf: i8[20] (20 B @ [s1 + 4])
    # [25:9] zero 20 * 1 B = 20 B
    sw zero, 4(s1)
    sw zero, 8(s1)
    sw zero, 12(s1)
    sw zero, 16(s1)
    sw zero, 20(s1)
    # [26:5] var n = num
    # [26:9] n: i32 (4 B @ [s1 + 24])
    # [26:9] n = num
    # [26:13] num
    # [26:13] allocate scratch register -> t0
    lw t0, 0(s1)
    # [26:13] allocate scratch register -> t1
    lw t1, 0(t0)
    sw t1, 24(s1)
    # [26:13] free scratch register t1
    # [26:13] free scratch register t0
    # [27:5] var i = 20
    # [27:9] i: i32 (4 B @ [s1 + 28])
    # [27:9] i = 20
    # [27:13] 20
    # [27:13] allocate scratch register -> t0
    li t0, 20
    sw t0, 28(s1)
    # [27:13] free scratch register t0
    # [28:5] label
    loop.28.5:
        # [29:9] i = i - 1
        # [29:13] i
        # [29:13] i - 1
        # [29:13] src: folded constant '- 1'
        # [29:13] allocate scratch register -> t0
        lw t0, 28(s1)
        addi t0, t0, -1
        sw t0, 28(s1)
        # [29:13] free scratch register t0
        # [31:9] buf[i] = i8('0' - n % 10)
        # [31:13] allocate scratch register -> t0
        # [31:13] set array index
        # [31:13] i
        lw t0, 28(s1)
        # [31:18] buf = i8('0' - n % 10)
        # [31:18] = expression
        # [31:18] allocate scratch register -> t1
            # [31:21] t1 = 48
            # [31:21] src: folded constant '+ '0''
            li t1, 48
            # [31:29] t1 - n % 10
            # [31:29] src: expression
            # [31:29] allocate scratch register -> t2
            # [31:27] n
            lw t2, 24(s1)
            # [31:31] t2 % 10
            # [31:31] src: constant
            addi a0, t2, 0
            li a1, 10
            call .Lbaz_divide
            addi t2, a1, 0
            sub t1, t1, t2
            # [31:29] free scratch register t2
        # [31:18] allocate scratch register -> t2
        add t2, s1, t0
        sb t1, 4(t2)
        # [31:18] free scratch register t2
        # [31:18] free scratch register t1
        # [31:9] free scratch register t0
        # [32:9] n = n / 10
        # [32:13] n
        # [32:17] n / 10
        # [32:17] src: constant
        lw a0, 24(s1)
        li a1, 10
        call .Lbaz_divide
        sw a0, 24(s1)
        if.33.12:
        # [33:12] ? n == 0
        # [33:12] ? n == 0
        cmp.33.12:
        # [33:12] allocate scratch register -> t0
        lw t0, 24(s1)
        bne t0, zero, loop.28.5
        # [33:12] free scratch register t0
        if.33.12.code:
            # [33:19] break
        if.33.9.end:
    loop.28.5.end:
    # [35:5] write(1, buf, 20)
    # [35:5] allocate named register a0
    # [35:5] allocate named register a1
    # [35:5] allocate named register a2
    # [35:11] 1
    li a0, 1
    # [35:19] 20
    li a2, 20
    addi a1, s1, 4
    # [35:5] allocate named register a7
    call a7, .Lbaz_write
    # [35:5] free named register a7
    # [35:5] free named register a2
    # [35:5] free named register a1
    # [35:5] free named register a0
    lw ra, 0(sp)
    addi sp, sp, 16
    ret
# free named register s1
.equ size.func.print_num, 32
.Lbaz_exit:
1:
    ebreak
    j 1b
.Lbaz_write:
    li a3, -1
    mv a5, a1
    add a0, a1, a2
1:
    beq a5, a0, 3f
2:
    lw a4, -8(zero)
    bne a4, a3, 2b
    lbu a4, 0(a5)
    sw a4, -8(zero)
    addi a5, a5, 1
    j 1b
3:
    mv a0, a2
    jr a7
.Lbaz_divide:
    beqz a1, 5f
    srai a4, a0, 31
    srai a3, a1, 31
    xor a0, a0, a4
    sub a0, a0, a4
    xor a1, a1, a3
    sub a1, a1, a3
    xor a3, a3, a4
    li a2, 0
    li a5, 32
1:
    srli a6, a0, 31
    slli a2, a2, 1
    or a2, a2, a6
    slli a0, a0, 1
    bltu a2, a1, 2f
    sub a2, a2, a1
    ori a0, a0, 1
2:
    addi a5, a5, -1
    bnez a5, 1b
    xor a0, a0, a3
    sub a0, a0, a3
    xor a1, a2, a4
    sub a1, a1, a4
    ret
5:
    ebreak
    j 5b
.data
.balign 16
dat:
dat.end:
.bss
.balign 16
vars:
.zero 65536
vars.end:
# free named register s0

#   removed jumps to next code: 22
#    removed unreachable jumps: 0
# removed same target branches: 9
# inverted branches over jumps: 2
#            max frames in use: 6
#              dat var padding: 0 B
#                max vars size: 360 B
