#
# generated by baz
#

.option norvc
.option norelax

.text
.globl _start
_start:

# allocate named register s0
la s0, dat

# load stack pointer to 0x80:0000
lui sp, 2048

# [1:1] dat str_hello = "\nwelcome to adventure #6\n    type 'help'\n"
# [1:6] str_hello: i8[41] (41 B @ [s0])
# [2:1] dat str_uc = "u c "
# [2:9] str_uc: i8[4] (4 B @ [s0 + 41])
# [3:1] dat str_exits = "exits: "
# [3:6] str_exits: i8[7] (7 B @ [s0 + 45])
# [4:1] dat str_prompt = " > "
# [4:5] str_prompt: i8[3] (3 B @ [s0 + 52])
# [5:1] dat str_nl = "\n"
# [5:9] str_nl: i8[1] (1 B @ [s0 + 55])
# [6:1] dat str_erase = "\b \b"
# [6:6] str_erase: i8[3] (3 B @ [s0 + 56])
# [8:1] dat str_not_understood = "not understood"
# [8:5] str_not_understood: i8[14] (14 B @ [s0 + 59])
# [10:1] dat str_action_look = "l"
# [10:5] str_action_look: i8[1] (1 B @ [s0 + 73])
# [11:1] dat str_action_go = "go"
# [11:5] str_action_go: i8[2] (2 B @ [s0 + 74])
# [17:1] str : 128 B    fields:
# [17:1]       name :  offset :    size :  array? : array size
# [17:1]       data :       0 :     127 :     yes :        127
# [17:1]        len :     127 :       1 :      no :           
#
# [46:7] const name_len = 16
# [47:7] const id_list_len = 32
# [48:7] const room_objects_len = 64
# [49:7] const room_entities_len = 32
# [50:7] const room_links_len = 8
# [51:7] const link_names_len = 1024
# [52:7] const rooms_len = 128
# [53:7] const entities_len = 32
# [55:1] id_list : 66 B    fields:
# [55:1]       name :  offset :    size :  array? : array size
# [55:1]        ids :       0 :      64 :     yes :         32
# [55:1]        len :      64 :       2 :      no :           
#
# [60:1] name : 17 B    fields:
# [60:1]       name :  offset :    size :  array? : array size
# [60:1]       text :       0 :      16 :     yes :         16
# [60:1]        len :      16 :       1 :      no :           
#
# [69:1] dat link_names = name[link_names_len]{ { "none", 4 } }
# [69:5] link_names: name[1024] (17408 B @ [s0 + 76])
# [73:1] link : 6 B    fields:
# [73:1]       name :  offset :    size :  array? : array size
# [73:1] link_name_id :       0 :       2 :      no :           
# [73:1]       from :       2 :       2 :      no :           
# [73:1]         to :       4 :       2 :      no :           
#
# [79:1] room : 518 B    fields:
# [79:1]       name :  offset :    size :  array? : array size
# [79:1]       name :       0 :      17 :      no :           
# [79:1] description :      17 :     128 :      no :           
# [79:1]       note :     145 :     128 :      no :           
# [79:1]   entities :     274 :      66 :      no :           
# [79:1]      links :     340 :      48 :     yes :          8
# [79:1]  links_len :     388 :       1 :      no :           
# [79:1]    objects :     390 :     128 :     yes :         64
#
# [89:1] entity : 2068 B    fields:
# [89:1]       name :  offset :    size :  array? : array size
# [89:1]       name :       0 :      17 :      no :           
# [89:1]    room_id :      18 :       2 :      no :           
# [89:1]   messages :      20 :    2048 :     yes :         16
#
# [99:1] dat rooms = room[rooms_len]{ { { "roome", 5 }, { "u r in roome", 12 }, { "todo: find an exit", 18 }, { { 0 }, 1 }, { {0, 0, 0} }, 1 } }
# [99:5] rooms: room[128] (66304 B @ [s0 + 17484])
# [109:1] dat entities = entity[entities_len]{ { { "me", 2 }, 0 } }
# [109:5] entities: entity[32] (66176 B @ [s0 + 83788])
# [113:1] dat entities_len = 1
# [113:5] entities_len: i32 (4 B @ [s0 + 149964])
# [144:1] dat str_went = "went\n"
# [144:5] str_went: i8[5] (5 B @ [s0 + 149968])
#
main:
    # [162:5] print(str_hello)
    # [13:6] print(s i8[])
    func.print.162.5:
        # [162:5] alias s -> str_hello
        # [14:5] write(1, s)
        # [14:5] allocate named register a0
        # [14:5] allocate named register a1
        # [14:5] allocate named register a2
        # [14:11] 1
        li a0, 1
        li a2, 41
        addi a1, s0, 0
        # [14:5] allocate named register a7
        call a7, .Lbaz_write
        # [14:5] free named register a7
        # [14:5] free named register a2
        # [14:5] free named register a1
        # [14:5] free named register a0
    func.print.162.5.end:
    # [164:5] var inp = str{}
    # [164:9] inp: str (128 B @ [s0 + 149984])
    # [164:9] inp = str{}
    # [164:15] zero remaining fields: 128 B
    # [164:15] zero loop of 4-byte accesses: start word aligned
    # [164:15] allocate scratch register -> t0
    lui t0, 37
    add t0, t0, s0
    addi t0, t0, -1568
    # [164:15] allocate scratch register -> t1
    # [164:15] zero 4-byte words
    li t1, 32
    1:
    sw zero, 0(t0)
    addi t0, t0, 4
    addi t1, t1, -1
    bnez t1, 1b
    # [164:15] free scratch register t1
    # [164:15] free scratch register t0
    # [165:5] var cur_entity = 0
    # [165:9] cur_entity: i32 (4 B @ [s0 + 150112])
    # [165:9] cur_entity = 0
    # [165:22] 0
    # [165:22] allocate scratch register -> t0
    lui t0, 37
    add t0, t0, s0
    sw zero, -1440(t0)
    # [165:22] free scratch register t0
    # [166:5] label
    loop.166.5:
        if.167.12:
        # [167:12] ? cur_entity == entities_len
        # [167:12] ? cur_entity == entities_len
        cmp.167.12:
        # [167:12] allocate scratch register -> t0
        lui t0, 37
        add t0, t0, s0
        lw t0, -1440(t0)
        # [167:12] allocate scratch register -> t1
        lui t1, 37
        add t1, t1, s0
        lw t1, -1588(t1)
        bne t0, t1, if.167.9.end
        # [167:12] free scratch register t1
        # [167:12] free scratch register t0
        if.167.12.code:
            # [168:13] cur_entity = 0
            # [168:26] 0
            # [168:26] allocate scratch register -> t0
            lui t0, 37
            add t0, t0, s0
            sw zero, -1440(t0)
            # [168:26] free scratch register t0
        if.167.9.end:
        # [170:9] print(str_nl)
        # [13:6] print(s i8[])
        func.print.170.9:
            # [170:9] alias s -> str_nl
            # [14:5] write(1, s)
            # [14:5] allocate named register a0
            # [14:5] allocate named register a1
            # [14:5] allocate named register a2
            # [14:11] 1
            li a0, 1
            li a2, 1
            addi a1, s0, 55
            # [14:5] allocate named register a7
            call a7, .Lbaz_write
            # [14:5] free named register a7
            # [14:5] free named register a2
            # [14:5] free named register a1
            # [14:5] free named register a0
        func.print.170.9.end:
        # [171:45] rooms[entities[cur_entity].room_id].print()
        # [171:15] allocate scratch register -> t0
        # [171:15] set array index
        # [171:15] entities[cur_entity].room_id
        # [171:24] allocate scratch register -> t1
        # [171:24] set array index
        # [171:24] cur_entity
        lui t1, 37
        add t1, t1, s0
        lw t1, -1440(t1)
        # [171:24] bounds check
        # [171:24] lower bound (--checks=lower)
        bltz t1, 1f
        # [171:24] upper bound (--checks=upper)
        # [171:24] allocate scratch register -> t2
        li t2, 32
        bltu t1, t2, 2f
        1:
        j baz_bounds_panic
        2:
        # [171:24] free scratch register t2
        # [171:24] allocate scratch register -> t2
        slli t2, t1, 7
        add t2, t2, t1
        slli t2, t2, 2
        add t1, t2, t1
        slli t1, t1, 2
        # [171:24] free scratch register t2
        add t0, s0, t1
        # [171:15] allocate scratch register -> t2
        lui t2, 20
        add t0, t0, t2
        # [171:15] free scratch register t2
        lh t0, 1886(t0)
        # [171:15] free scratch register t1
        # [171:15] bounds check
        # [171:15] lower bound (--checks=lower)
        bltz t0, 1f
        # [171:15] upper bound (--checks=upper)
        # [171:15] allocate scratch register -> t1
        li t1, 128
        bltu t0, t1, 2f
        1:
        j baz_bounds_panic
        2:
        # [171:15] free scratch register t1
        # [171:15] allocate scratch register -> t1
        slli t1, t0, 6
        add t1, t1, t0
        slli t1, t1, 2
        sub t0, t1, t0
        slli t0, t0, 1
        # [171:15] free scratch register t1
        # [171:45] allocate scratch register -> t1
        # [171:45] address of parameter 'self'
        add t1, s0, t0
        # [171:45] allocate scratch register -> t2
        lui t2, 4
        add t1, t1, t2
        # [171:45] free scratch register t2
        addi t1, t1, 1100
        # [115:6] room.print()
        func.room.print.171.45:
            # [171:45] alias self -> rooms
            # [116:22] self.description.print()
            # [22:6] str.print()
            func.str.print.116.22.171.45:
                # [116:22] alias self -> self.description
                # [23:5] write(1, self.data, self.len)
                # [23:5] allocate named register a0
                # [23:5] allocate named register a1
                # [23:5] allocate named register a2
                # [23:11] 1
                li a0, 1
                # [23:25] self.len
                lb a2, 144(t1)
                # [23:14] bounds check
                # [23:14] lower bound (--checks=lower)
                bltz a2, 1f
                # [23:14] upper bound (--checks=upper)
                # [23:14] allocate scratch register -> t2
                li t2, 127
                bgeu t2, a2, 2f
                1:
                j baz_bounds_panic
                2:
                # [23:14] free scratch register t2
                addi a1, t1, 17
                # [23:5] allocate named register a7
                call a7, .Lbaz_write
                # [23:5] free named register a7
                # [23:5] free named register a2
                # [23:5] free named register a1
                # [23:5] free named register a0
            func.str.print.116.22.171.45.end:
            # [117:5] print(str_nl)
            # [13:6] print(s i8[])
            func.print.117.5.171.45:
                # [117:5] alias s -> str_nl
                # [14:5] write(1, s)
                # [14:5] allocate named register a0
                # [14:5] allocate named register a1
                # [14:5] allocate named register a2
                # [14:11] 1
                li a0, 1
                li a2, 1
                addi a1, s0, 55
                # [14:5] allocate named register a7
                call a7, .Lbaz_write
                # [14:5] free named register a7
                # [14:5] free named register a2
                # [14:5] free named register a1
                # [14:5] free named register a0
            func.print.117.5.171.45.end:
            if.118.7.171.45:
            # [118:7] ? (self.entities.len > 0)
            cmp.118.7.171.45:
            # [118:7] ? (self.entities.len > 0)
            # [118:8] ? self.entities.len > 0
            cmp.118.8.171.45:
            # [118:8] allocate scratch register -> t2
            lh t2, 338(t1)
            bge zero, t2, if.118.5.171.45.end
            # [118:8] free scratch register t2
            if.118.7.171.45.code:
                # [119:9] print(str_uc)
                # [13:6] print(s i8[])
                func.print.119.9.171.45:
                    # [119:9] alias s -> str_uc
                    # [14:5] write(1, s)
                    # [14:5] allocate named register a0
                    # [14:5] allocate named register a1
                    # [14:5] allocate named register a2
                    # [14:11] 1
                    li a0, 1
                    li a2, 4
                    addi a1, s0, 41
                    # [14:5] allocate named register a7
                    call a7, .Lbaz_write
                    # [14:5] free named register a7
                    # [14:5] free named register a2
                    # [14:5] free named register a1
                    # [14:5] free named register a0
                func.print.119.9.171.45.end:
                # [120:9] var i = i16(0)
                # [120:13] i: i16 (2 B @ [s0 + 150116])
                # [120:13] i = i16(0)
                # [120:17] allocate scratch register -> t2
                lui t2, 37
                add t2, t2, s0
                sh zero, -1436(t2)
                # [120:17] free scratch register t2
                # [121:9] label
                loop.121.9.171.45:
                    if.122.16.171.45:
                    # [122:16] ? self.entities.len == i
                    # [122:16] ? self.entities.len == i
                    cmp.122.16.171.45:
                    # [122:16] allocate scratch register -> t2
                    lh t2, 338(t1)
                    # [122:16] allocate scratch register -> t3
                    lui t3, 37
                    add t3, t3, s0
                    lh t3, -1436(t3)
                    beq t2, t3, loop.121.9.171.45.end
                    # [122:16] free scratch register t3
                    # [122:16] free scratch register t2
                    if.122.16.171.45.code:
                        # [122:39] break
                    if.122.13.171.45.end:
                    # [123:44] entities[self.entities.ids[i]].print()
                    # [123:22] allocate scratch register -> t2
                    # [123:22] set array index
                    # [123:22] self.entities.ids[i]
                    # [123:40] allocate scratch register -> t3
                    # [123:40] set array index
                    # [123:40] i
                    lui t3, 37
                    add t3, t3, s0
                    lh t3, -1436(t3)
                    # [123:40] bounds check
                    # [123:40] lower bound (--checks=lower)
                    bltz t3, 1f
                    # [123:40] upper bound (--checks=upper)
                    # [123:40] allocate scratch register -> t4
                    li t4, 32
                    bltu t3, t4, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [123:40] free scratch register t4
                    slli t2, t3, 1
                    add t2, t2, t1
                    lh t2, 274(t2)
                    # [123:22] free scratch register t3
                    # [123:22] bounds check
                    # [123:22] lower bound (--checks=lower)
                    bltz t2, 1f
                    # [123:22] upper bound (--checks=upper)
                    # [123:22] allocate scratch register -> t3
                    li t3, 32
                    bltu t2, t3, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [123:22] free scratch register t3
                    # [123:22] allocate scratch register -> t3
                    slli t3, t2, 7
                    add t3, t3, t2
                    slli t3, t3, 2
                    add t2, t3, t2
                    slli t2, t2, 2
                    # [123:22] free scratch register t3
                    # [123:44] allocate scratch register -> t3
                    # [123:44] address of parameter 'self'
                    add t3, s0, t2
                    # [123:44] allocate scratch register -> t4
                    lui t4, 20
                    add t3, t3, t4
                    # [123:44] free scratch register t4
                    addi t3, t3, 1868
                    # [95:6] entity.print()
                    func.entity.print.123.44.171.45:
                        # [123:44] alias self -> entities
                        # [96:5] write(1, self.name.text, self.name.len)
                        # [96:5] allocate named register a0
                        # [96:5] allocate named register a1
                        # [96:5] allocate named register a2
                        # [96:11] 1
                        li a0, 1
                        # [96:30] self.name.len
                        lb a2, 16(t3)
                        # [96:14] bounds check
                        # [96:14] lower bound (--checks=lower)
                        bltz a2, 1f
                        # [96:14] upper bound (--checks=upper)
                        # [96:14] allocate scratch register -> t4
                        li t4, 16
                        bgeu t4, a2, 2f
                        1:
                        j baz_bounds_panic
                        2:
                        # [96:14] free scratch register t4
                        addi a1, t3, 0
                        # [96:5] allocate named register a7
                        call a7, .Lbaz_write
                        # [96:5] free named register a7
                        # [96:5] free named register a2
                        # [96:5] free named register a1
                        # [96:5] free named register a0
                        # [123:44] free scratch register t3
                    func.entity.print.123.44.171.45.end:
                        # [123:44] free scratch register t2
                    # [124:13] print(str_nl)
                    # [13:6] print(s i8[])
                    func.print.124.13.171.45:
                        # [124:13] alias s -> str_nl
                        # [14:5] write(1, s)
                        # [14:5] allocate named register a0
                        # [14:5] allocate named register a1
                        # [14:5] allocate named register a2
                        # [14:11] 1
                        li a0, 1
                        li a2, 1
                        addi a1, s0, 55
                        # [14:5] allocate named register a7
                        call a7, .Lbaz_write
                        # [14:5] free named register a7
                        # [14:5] free named register a2
                        # [14:5] free named register a1
                        # [14:5] free named register a0
                    func.print.124.13.171.45.end:
                    # [125:13] i = i + 1
                    # [125:17] i
                    # [125:17] i + 1
                    # [125:17] src: folded constant '+ 1'
                    # [125:17] allocate scratch register -> t2
                    lui t2, 37
                    add t2, t2, s0
                    # [125:17] allocate scratch register -> t3
                    lh t3, -1436(t2)
                    addi t3, t3, 1
                    sh t3, -1436(t2)
                    # [125:17] free scratch register t3
                    # [125:17] free scratch register t2
                j loop.121.9.171.45
                loop.121.9.171.45.end:
            if.118.5.171.45.end:
            if.128.7.171.45:
            # [128:7] ? (self.links_len > 0)
            cmp.128.7.171.45:
            # [128:7] ? (self.links_len > 0)
            # [128:8] ? self.links_len > 0
            cmp.128.8.171.45:
            # [128:8] allocate scratch register -> t2
            lb t2, 388(t1)
            bge zero, t2, if.128.5.171.45.end
            # [128:8] free scratch register t2
            if.128.7.171.45.code:
                # [129:9] print(str_exits)
                # [13:6] print(s i8[])
                func.print.129.9.171.45:
                    # [129:9] alias s -> str_exits
                    # [14:5] write(1, s)
                    # [14:5] allocate named register a0
                    # [14:5] allocate named register a1
                    # [14:5] allocate named register a2
                    # [14:11] 1
                    li a0, 1
                    li a2, 7
                    addi a1, s0, 45
                    # [14:5] allocate named register a7
                    call a7, .Lbaz_write
                    # [14:5] free named register a7
                    # [14:5] free named register a2
                    # [14:5] free named register a1
                    # [14:5] free named register a0
                func.print.129.9.171.45.end:
                # [130:9] var i = i8(0)
                # [130:13] i: i8 (1 B @ [s0 + 150116])
                # [130:13] i = i8(0)
                # [130:17] allocate scratch register -> t2
                lui t2, 37
                add t2, t2, s0
                sb zero, -1436(t2)
                # [130:17] free scratch register t2
                # [131:9] label
                loop.131.9.171.45:
                    if.132.16.171.45:
                    # [132:16] ? self.links_len == i
                    # [132:16] ? self.links_len == i
                    cmp.132.16.171.45:
                    # [132:16] allocate scratch register -> t2
                    lb t2, 388(t1)
                    # [132:16] allocate scratch register -> t3
                    lui t3, 37
                    add t3, t3, s0
                    lb t3, -1436(t3)
                    beq t2, t3, loop.131.9.171.45.end
                    # [132:16] free scratch register t3
                    # [132:16] free scratch register t2
                    if.132.16.171.45.code:
                        # [132:36] break
                    if.132.13.171.45.end:
                    # [133:52] link_names[self.links[i].link_name_id].print()
                    # [133:24] allocate scratch register -> t2
                    # [133:24] set array index
                    # [133:24] self.links[i].link_name_id
                    # [133:35] allocate scratch register -> t3
                    # [133:35] set array index
                    # [133:35] i
                    lui t3, 37
                    add t3, t3, s0
                    lb t3, -1436(t3)
                    # [133:35] bounds check
                    # [133:35] lower bound (--checks=lower)
                    bltz t3, 1f
                    # [133:35] upper bound (--checks=upper)
                    # [133:35] allocate scratch register -> t4
                    li t4, 8
                    bltu t3, t4, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [133:35] free scratch register t4
                    # [133:35] allocate scratch register -> t4
                    slli t4, t3, 2
                    sub t3, t4, t3
                    slli t3, t3, 1
                    # [133:35] free scratch register t4
                    add t2, t1, t3
                    lh t2, 340(t2)
                    # [133:24] free scratch register t3
                    # [133:24] bounds check
                    # [133:24] lower bound (--checks=lower)
                    bltz t2, 1f
                    # [133:24] upper bound (--checks=upper)
                    # [133:24] allocate scratch register -> t3
                    li t3, 1024
                    bltu t2, t3, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [133:24] free scratch register t3
                    # [133:24] allocate scratch register -> t3
                    slli t3, t2, 4
                    add t2, t3, t2
                    # [133:24] free scratch register t3
                    # [133:52] allocate scratch register -> t3
                    # [133:52] address of parameter 'self'
                    add t3, s0, t2
                    # [65:6] name.print()
                    func.name.print.133.52.171.45:
                        # [133:52] alias self -> link_names
                        # [66:5] write(1, self.text, self.len)
                        # [66:5] allocate named register a0
                        # [66:5] allocate named register a1
                        # [66:5] allocate named register a2
                        # [66:11] 1
                        li a0, 1
                        # [66:25] self.len
                        lb a2, 92(t3)
                        # [66:14] bounds check
                        # [66:14] lower bound (--checks=lower)
                        bltz a2, 1f
                        # [66:14] upper bound (--checks=upper)
                        # [66:14] allocate scratch register -> t4
                        li t4, 16
                        bgeu t4, a2, 2f
                        1:
                        j baz_bounds_panic
                        2:
                        # [66:14] free scratch register t4
                        addi a1, t3, 76
                        # [66:5] allocate named register a7
                        call a7, .Lbaz_write
                        # [66:5] free named register a7
                        # [66:5] free named register a2
                        # [66:5] free named register a1
                        # [66:5] free named register a0
                        # [133:52] free scratch register t3
                    func.name.print.133.52.171.45.end:
                        # [133:52] free scratch register t2
                    # [134:13] print(str_nl)
                    # [13:6] print(s i8[])
                    func.print.134.13.171.45:
                        # [134:13] alias s -> str_nl
                        # [14:5] write(1, s)
                        # [14:5] allocate named register a0
                        # [14:5] allocate named register a1
                        # [14:5] allocate named register a2
                        # [14:11] 1
                        li a0, 1
                        li a2, 1
                        addi a1, s0, 55
                        # [14:5] allocate named register a7
                        call a7, .Lbaz_write
                        # [14:5] free named register a7
                        # [14:5] free named register a2
                        # [14:5] free named register a1
                        # [14:5] free named register a0
                    func.print.134.13.171.45.end:
                    # [135:13] i = i + 1
                    # [135:17] i
                    # [135:17] i + 1
                    # [135:17] src: folded constant '+ 1'
                    # [135:17] allocate scratch register -> t2
                    lui t2, 37
                    add t2, t2, s0
                    # [135:17] allocate scratch register -> t3
                    lb t3, -1436(t2)
                    addi t3, t3, 1
                    sb t3, -1436(t2)
                    # [135:17] free scratch register t3
                    # [135:17] free scratch register t2
                j loop.131.9.171.45
                loop.131.9.171.45.end:
            if.128.5.171.45.end:
            if.138.8.171.45:
            # [138:8] ? self.note.len != 0
            # [138:8] ? self.note.len != 0
            cmp.138.8.171.45:
            # [138:8] allocate scratch register -> t2
            lb t2, 272(t1)
            beq t2, zero, if.138.5.171.45.end
            # [138:8] free scratch register t2
            if.138.8.171.45.code:
                # [139:19] self.note.print()
                # [22:6] str.print()
                func.str.print.139.19.171.45:
                    # [139:19] alias self -> self.note
                    # [23:5] write(1, self.data, self.len)
                    # [23:5] allocate named register a0
                    # [23:5] allocate named register a1
                    # [23:5] allocate named register a2
                    # [23:11] 1
                    li a0, 1
                    # [23:25] self.len
                    lb a2, 272(t1)
                    # [23:14] bounds check
                    # [23:14] lower bound (--checks=lower)
                    bltz a2, 1f
                    # [23:14] upper bound (--checks=upper)
                    # [23:14] allocate scratch register -> t2
                    li t2, 127
                    bgeu t2, a2, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [23:14] free scratch register t2
                    addi a1, t1, 145
                    # [23:5] allocate named register a7
                    call a7, .Lbaz_write
                    # [23:5] free named register a7
                    # [23:5] free named register a2
                    # [23:5] free named register a1
                    # [23:5] free named register a0
                func.str.print.139.19.171.45.end:
                # [140:9] print(str_nl)
                # [13:6] print(s i8[])
                func.print.140.9.171.45:
                    # [140:9] alias s -> str_nl
                    # [14:5] write(1, s)
                    # [14:5] allocate named register a0
                    # [14:5] allocate named register a1
                    # [14:5] allocate named register a2
                    # [14:11] 1
                    li a0, 1
                    li a2, 1
                    addi a1, s0, 55
                    # [14:5] allocate named register a7
                    call a7, .Lbaz_write
                    # [14:5] free named register a7
                    # [14:5] free named register a2
                    # [14:5] free named register a1
                    # [14:5] free named register a0
                func.print.140.9.171.45.end:
            if.138.5.171.45.end:
            # [171:45] free scratch register t1
        func.room.print.171.45.end:
            # [171:45] free scratch register t0
        # [172:35] entities[cur_entity].name.print()
        # [172:18] allocate scratch register -> t0
        # [172:18] set array index
        # [172:18] cur_entity
        lui t0, 37
        add t0, t0, s0
        lw t0, -1440(t0)
        # [172:18] bounds check
        # [172:18] lower bound (--checks=lower)
        bltz t0, 1f
        # [172:18] upper bound (--checks=upper)
        # [172:18] allocate scratch register -> t1
        li t1, 32
        bltu t0, t1, 2f
        1:
        j baz_bounds_panic
        2:
        # [172:18] free scratch register t1
        # [172:18] allocate scratch register -> t1
        slli t1, t0, 7
        add t1, t1, t0
        slli t1, t1, 2
        add t0, t1, t0
        slli t0, t0, 2
        # [172:18] free scratch register t1
        # [172:35] allocate scratch register -> t1
        # [172:35] address of parameter 'self'
        add t1, s0, t0
        # [172:35] allocate scratch register -> t2
        lui t2, 20
        add t1, t1, t2
        # [172:35] free scratch register t2
        addi t1, t1, 1868
        # [65:6] name.print()
        func.name.print.172.35:
            # [172:35] alias self -> entities.name
            # [66:5] write(1, self.text, self.len)
            # [66:5] allocate named register a0
            # [66:5] allocate named register a1
            # [66:5] allocate named register a2
            # [66:11] 1
            li a0, 1
            # [66:25] self.len
            lb a2, 16(t1)
            # [66:14] bounds check
            # [66:14] lower bound (--checks=lower)
            bltz a2, 1f
            # [66:14] upper bound (--checks=upper)
            # [66:14] allocate scratch register -> t2
            li t2, 16
            bgeu t2, a2, 2f
            1:
            j baz_bounds_panic
            2:
            # [66:14] free scratch register t2
            addi a1, t1, 0
            # [66:5] allocate named register a7
            call a7, .Lbaz_write
            # [66:5] free named register a7
            # [66:5] free named register a2
            # [66:5] free named register a1
            # [66:5] free named register a0
            # [172:35] free scratch register t1
        func.name.print.172.35.end:
            # [172:35] free scratch register t0
        # [173:9] print(str_prompt)
        # [13:6] print(s i8[])
        func.print.173.9:
            # [173:9] alias s -> str_prompt
            # [14:5] write(1, s)
            # [14:5] allocate named register a0
            # [14:5] allocate named register a1
            # [14:5] allocate named register a2
            # [14:11] 1
            li a0, 1
            li a2, 3
            addi a1, s0, 52
            # [14:5] allocate named register a7
            call a7, .Lbaz_write
            # [14:5] free named register a7
            # [14:5] free named register a2
            # [14:5] free named register a1
            # [14:5] free named register a0
        func.print.173.9.end:
        # [174:13] inp.input()
        # [26:6] str.input()
        func.str.input.174.13:
            # [174:13] alias self -> inp
            # [28:5] var nbytes = 0
            # [28:9] nbytes: i32 (4 B @ [s0 + 150116])
            # [28:9] nbytes = 0
            # [28:18] 0
            # [28:18] allocate scratch register -> t0
            lui t0, 37
            add t0, t0, s0
            sw zero, -1436(t0)
            # [28:18] free scratch register t0
            # [29:5] label
            loop.29.5.174.13:
                if.30.12.174.13:
                # [30:12] ? nbytes == array_length(self.data)
                # [30:12] ? nbytes == array_length(self.data)
                cmp.30.12.174.13:
                # [30:22] allocate scratch register -> t0
                    # [30:22] t0 = array_length(self.data)
                    # [30:22] = expression
                    # [30:22] array_length(self.data)
                    li t0, 127
                # [30:12] allocate scratch register -> t1
                lui t1, 37
                add t1, t1, s0
                lw t1, -1436(t1)
                beq t1, t0, loop.29.5.174.13.end
                # [30:12] free scratch register t1
                # [30:12] free scratch register t0
                if.30.12.174.13.code:
                    # [30:46] break
                if.30.9.174.13.end:
                if.31.12.174.13:
                # [31:12] ? read(0, self.data, 1, nbytes) == 0
                # [31:12] ? read(0, self.data, 1, nbytes) == 0
                cmp.31.12.174.13:
                # [31:12] allocate scratch register -> t0
                    # [31:12] t0 = read(0, self.data, 1, nbytes)
                    # [31:12] = expression
                    # [31:12] read(0, self.data, 1, nbytes)
                    # [31:12] allocate named register a0
                    # [31:12] allocate named register a1
                    # [31:12] allocate named register a2
                    # [31:17] 0
                    li a0, 0
                    # [31:31] 1
                    li a2, 1
                    # [31:34] allocate scratch register -> t1
                    # [31:34] nbytes
                    lui t1, 37
                    add t1, t1, s0
                    lw t1, -1436(t1)
                    # [31:34] bounds check
                    # [31:34] lower bound (--checks=lower)
                    bltz t1, 1f
                    bltz a2, 1f
                    # [31:34] upper bound (--checks=upper)
                    # [31:34] allocate scratch register -> t2
                    # [31:34] allocate scratch register -> t3
                    add t3, t1, a2
                    li t2, 127
                    bgeu t2, t3, 2f
                    1:
                    j baz_bounds_panic
                    2:
                    # [31:34] free scratch register t3
                    # [31:34] free scratch register t2
                    lui a1, 37
                    add a1, a1, s0
                    addi a1, a1, -1568
                    add a1, a1, t1
                    # [31:12] free scratch register t1
                    # [31:12] allocate named register a7
                    call a7, .Lbaz_read
                    # [31:12] free named register a7
                    addi t0, a0, 0
                    # [31:12] free named register a2
                    # [31:12] free named register a1
                    # [31:12] free named register a0
                beq t0, zero, loop.29.5.174.13.end
                # [31:12] free scratch register t0
                if.31.12.174.13.code:
                    # [31:47] break
                if.31.9.174.13.end:
                if.32.12.174.13:
                # [32:12] ? self.data[nbytes] == '\x7f'
                # [32:12] ? self.data[nbytes] == '\x7f'
                cmp.32.12.174.13:
                # [32:22] allocate scratch register -> t0
                # [32:22] set array index
                # [32:22] nbytes
                lui t0, 37
                add t0, t0, s0
                lw t0, -1436(t0)
                # [32:22] bounds check
                # [32:22] lower bound (--checks=lower)
                bltz t0, 1f
                # [32:22] upper bound (--checks=upper)
                # [32:22] allocate scratch register -> t1
                li t1, 127
                bltu t0, t1, 2f
                1:
                j baz_bounds_panic
                2:
                # [32:22] free scratch register t1
                # [32:12] allocate scratch register -> t1
                add t1, s0, t0
                # [32:12] allocate scratch register -> t2
                lui t2, 37
                add t1, t1, t2
                # [32:12] free scratch register t2
                lb t1, -1568(t1)
                # [32:12] allocate scratch register -> t2
                li t2, 127
                bne t1, t2, if.32.9.174.13.end
                # [32:12] free scratch register t2
                # [32:12] free scratch register t1
                # [32:12] free scratch register t0
                if.32.12.174.13.code:
                    if.33.16.174.13:
                    # [33:16] ? nbytes > 0
                    # [33:16] ? nbytes > 0
                    cmp.33.16.174.13:
                    # [33:16] allocate scratch register -> t0
                    lui t0, 37
                    add t0, t0, s0
                    lw t0, -1436(t0)
                    bge zero, t0, if.33.13.174.13.end
                    # [33:16] free scratch register t0
                    if.33.16.174.13.code:
                        # [34:17] nbytes = nbytes - 1
                        # [34:26] nbytes
                        # [34:26] nbytes - 1
                        # [34:26] src: folded constant '- 1'
                        # [34:26] allocate scratch register -> t0
                        lui t0, 37
                        add t0, t0, s0
                        # [34:26] allocate scratch register -> t1
                        lw t1, -1436(t0)
                        addi t1, t1, -1
                        sw t1, -1436(t0)
                        # [34:26] free scratch register t1
                        # [34:26] free scratch register t0
                        # [35:17] write(1, str_erase)
                        # [35:17] allocate named register a0
                        # [35:17] allocate named register a1
                        # [35:17] allocate named register a2
                        # [35:23] 1
                        li a0, 1
                        li a2, 3
                        addi a1, s0, 56
                        # [35:17] allocate named register a7
                        call a7, .Lbaz_write
                        # [35:17] free named register a7
                        # [35:17] free named register a2
                        # [35:17] free named register a1
                        # [35:17] free named register a0
                    if.33.13.174.13.end:
                    # [37:13] continue
                    j loop.29.5.174.13
                if.32.9.174.13.end:
                # [39:9] write(1, self.data, 1, nbytes)
                # [39:9] allocate named register a0
                # [39:9] allocate named register a1
                # [39:9] allocate named register a2
                # [39:15] 1
                li a0, 1
                # [39:29] 1
                li a2, 1
                # [39:32] allocate scratch register -> t0
                # [39:32] nbytes
                lui t0, 37
                add t0, t0, s0
                lw t0, -1436(t0)
                # [39:32] bounds check
                # [39:32] lower bound (--checks=lower)
                bltz t0, 1f
                bltz a2, 1f
                # [39:32] upper bound (--checks=upper)
                # [39:32] allocate scratch register -> t1
                # [39:32] allocate scratch register -> t2
                add t2, t0, a2
                li t1, 127
                bgeu t1, t2, 2f
                1:
                j baz_bounds_panic
                2:
                # [39:32] free scratch register t2
                # [39:32] free scratch register t1
                lui a1, 37
                add a1, a1, s0
                addi a1, a1, -1568
                add a1, a1, t0
                # [39:9] free scratch register t0
                # [39:9] allocate named register a7
                call a7, .Lbaz_write
                # [39:9] free named register a7
                # [39:9] free named register a2
                # [39:9] free named register a1
                # [39:9] free named register a0
                if.40.12.174.13:
                # [40:12] ? self.data[nbytes] == '\n'
                # [40:12] ? self.data[nbytes] == '\n'
                cmp.40.12.174.13:
                # [40:22] allocate scratch register -> t0
                # [40:22] set array index
                # [40:22] nbytes
                lui t0, 37
                add t0, t0, s0
                lw t0, -1436(t0)
                # [40:22] bounds check
                # [40:22] lower bound (--checks=lower)
                bltz t0, 1f
                # [40:22] upper bound (--checks=upper)
                # [40:22] allocate scratch register -> t1
                li t1, 127
                bltu t0, t1, 2f
                1:
                j baz_bounds_panic
                2:
                # [40:22] free scratch register t1
                # [40:12] allocate scratch register -> t1
                add t1, s0, t0
                # [40:12] allocate scratch register -> t2
                lui t2, 37
                add t1, t1, t2
                # [40:12] free scratch register t2
                lb t1, -1568(t1)
                # [40:12] allocate scratch register -> t2
                li t2, 10
                beq t1, t2, loop.29.5.174.13.end
                # [40:12] free scratch register t2
                # [40:12] free scratch register t1
                # [40:12] free scratch register t0
                if.40.12.174.13.code:
                    # [40:38] break
                if.40.9.174.13.end:
                # [41:9] nbytes = nbytes + 1
                # [41:18] nbytes
                # [41:18] nbytes + 1
                # [41:18] src: folded constant '+ 1'
                # [41:18] allocate scratch register -> t0
                lui t0, 37
                add t0, t0, s0
                # [41:18] allocate scratch register -> t1
                lw t1, -1436(t0)
                addi t1, t1, 1
                sw t1, -1436(t0)
                # [41:18] free scratch register t1
                # [41:18] free scratch register t0
            j loop.29.5.174.13
            loop.29.5.174.13.end:
            # [43:5] self.len = i8(nbytes)
            # [43:16] self.len = i8(nbytes)
            # [43:16] = expression
            # [43:19] nbytes
            # [43:19] allocate scratch register -> t0
            lui t0, 37
            add t0, t0, s0
            lw t0, -1436(t0)
            # [43:19] allocate scratch register -> t1
            lui t1, 37
            add t1, t1, s0
            sb t0, -1441(t1)
            # [43:19] free scratch register t1
            # [43:19] free scratch register t0
        func.str.input.174.13.end:
        # [175:9] parse_input(cur_entity, inp)
        # [150:6] parse_input(cur_entity, inp str)
        func.parse_input.175.9:
            # [175:9] alias cur_entity -> cur_entity
            # [175:9] alias inp -> inp
            if.151.8.175.9:
            # [151:8] ? i(inp.len) >= array_length(str_action_go) and arrays_equal(str_action_go, inp.data, array_length(str_action_go))
            # [151:8] ? i(inp.len) >= array_length(str_action_go)
            cmp.151.8.175.9:
            # [151:8] allocate scratch register -> t0
                # [151:8] t0 = i(inp.len)
                # [151:8] = expression
                # [151:10] inp.len
                lui t0, 37
                add t0, t0, s0
                lb t0, -1441(t0)
            # [151:22] allocate scratch register -> t1
                # [151:22] t1 = array_length(str_action_go)
                # [151:22] = expression
                # [151:22] array_length(str_action_go)
                li t1, 2
            blt t0, t1, if.151.5.175.9.end
            # [151:8] free scratch register t1
            # [151:8] free scratch register t0
            # [152:8] ? shorthand: arrays_equal(str_action_go, inp.data, array_length(str_action_go))
            cmp.152.8.175.9:
            # [152:8] allocate scratch register -> t0
                # [152:8] t0 = arrays_equal(str_action_go, inp.data, array_length(str_action_go))
                # [152:8] = expression
                # [152:8] arrays_equal(str_action_go, inp.data, array_length(str_action_go))
                # [152:8] allocate scratch register -> t1
                # [152:8] allocate scratch register -> t2
                # [152:8] allocate scratch register -> t3
                # [152:8] t1: source, t2: destination, t3: count
                # [152:46] array_length(str_action_go)
                # [152:46] t3 = array_length(str_action_go)
                # [152:46] = expression
                # [152:46] array_length(str_action_go)
                li t3, 2
                # [152:21] str_action_go
                # [152:21] bounds check
                # [152:21] lower bound (--checks=lower)
                bltz t3, 1f
                # [152:21] upper bound (--checks=upper)
                # [152:21] allocate scratch register -> t4
                li t4, 2
                bgeu t4, t3, 2f
                1:
                j baz_bounds_panic
                2:
                # [152:21] free scratch register t4
                addi t1, s0, 74
                # [152:36] inp.data
                # [152:36] bounds check
                # [152:36] lower bound (--checks=lower)
                bltz t3, 1f
                # [152:36] upper bound (--checks=upper)
                # [152:36] allocate scratch register -> t4
                li t4, 127
                bgeu t4, t3, 2f
                1:
                j baz_bounds_panic
                2:
                # [152:36] free scratch register t4
                lui t2, 37
                add t2, t2, s0
                addi t2, t2, -1568
                # [152:8] t3: elements to bytes (1 bytes/element)
                # [152:8] allocate scratch register -> t4
                # [152:8] t0: left value/result, t4: right value
                # [152:8] stop at first mismatch
                # [152:8] 2-byte accesses: both addresses 2-byte aligned, type 1-byte aligned
                # [152:8] allocate scratch register -> t5
                # [152:8] t5: halfwords, t3: tail bytes
                # [152:8] split bytes into chunks and tail; skip loop if none
                srli t5, t3, 1
                andi t3, t3, 1
                beqz t5, 2f
                # [152:8] compare 2-byte halfwords
                1:
                lhu t0, 0(t1)
                lhu t4, 0(t2)
                bne t0, t4, 5f
                addi t1, t1, 2
                addi t2, t2, 2
                addi t5, t5, -1
                bnez t5, 1b
                2:
                # [152:8] compare optional final byte
                beqz t3, 4f
                lbu t0, 0(t1)
                lbu t4, 0(t2)
                bne t0, t4, 5f
                4:
                # [152:8] free scratch register t5
                # [152:8] all matched or empty: true
                li t0, 1
                j 6f
                5:
                # [152:8] mismatch: false
                li t0, 0
                6:
                # [152:8] free scratch register t4
                # [152:8] free scratch register t3
                # [152:8] free scratch register t2
                # [152:8] free scratch register t1
            beq t0, zero, if.151.5.175.9.end
            # [152:8] free scratch register t0
            if.151.8.175.9.code:
                # [153:9] action_go(cur_entity)
                # [146:6] action_go(cur_entity)
                func.action_go.153.9.175.9:
                    # [153:9] alias cur_entity -> cur_entity
                    # [147:5] print(str_went)
                    # [13:6] print(s i8[])
                    func.print.147.5.153.9.175.9:
                        # [147:5] alias s -> str_went
                        # [14:5] write(1, s)
                        # [14:5] allocate named register a0
                        # [14:5] allocate named register a1
                        # [14:5] allocate named register a2
                        # [14:11] 1
                        li a0, 1
                        li a2, 5
                        lui a1, 37
                        add a1, a1, s0
                        addi a1, a1, -1584
                        # [14:5] allocate named register a7
                        call a7, .Lbaz_write
                        # [14:5] free named register a7
                        # [14:5] free named register a2
                        # [14:5] free named register a1
                        # [14:5] free named register a0
                    func.print.147.5.153.9.175.9.end:
                func.action_go.153.9.175.9.end:
                # [154:9] return
                j func.parse_input.175.9.end
            if.151.5.175.9.end:
            # [157:5] print(str_not_understood)
            # [13:6] print(s i8[])
            func.print.157.5.175.9:
                # [157:5] alias s -> str_not_understood
                # [14:5] write(1, s)
                # [14:5] allocate named register a0
                # [14:5] allocate named register a1
                # [14:5] allocate named register a2
                # [14:11] 1
                li a0, 1
                li a2, 14
                addi a1, s0, 59
                # [14:5] allocate named register a7
                call a7, .Lbaz_write
                # [14:5] free named register a7
                # [14:5] free named register a2
                # [14:5] free named register a1
                # [14:5] free named register a0
            func.print.157.5.175.9.end:
            # [158:5] print(str_nl)
            # [13:6] print(s i8[])
            func.print.158.5.175.9:
                # [158:5] alias s -> str_nl
                # [14:5] write(1, s)
                # [14:5] allocate named register a0
                # [14:5] allocate named register a1
                # [14:5] allocate named register a2
                # [14:11] 1
                li a0, 1
                li a2, 1
                addi a1, s0, 55
                # [14:5] allocate named register a7
                call a7, .Lbaz_write
                # [14:5] free named register a7
                # [14:5] free named register a2
                # [14:5] free named register a1
                # [14:5] free named register a0
            func.print.158.5.175.9.end:
        func.parse_input.175.9.end:
    j loop.166.5
    loop.166.5.end:
# frame overflow handler (--checks=frame)
baz_frame_overflow:
    li a0, 2
    la a1, .Lbaz_frame_message
    li a2, 22
    call a7, .Lbaz_write
    li a0, 255
    j .Lbaz_exit
.section .rodata
.Lbaz_frame_message:
.ascii "panic: frame overflow"
.byte 10
.text
# bounds failure handler (--checks=upper or --checks=lower)
baz_bounds_panic:
    li a0, 255
.Lbaz_exit:
1:
    ebreak
    j 1b
.Lbaz_read:
    li a3, -1
    mv a6, a1
    li a0, 0
1:
    beq a0, a2, 4f
2:
    lw a4, -12(zero)
    beq a4, a3, 2b
    li a5, 4
    beq a4, a5, 4f
    li a5, 13
    bne a4, a5, 3f
    li a4, 10
3:
    sb a4, 0(a6)
    addi a6, a6, 1
    addi a0, a0, 1
    li a5, 10
    bne a4, a5, 1b
4:
    jr a7
.Lbaz_write:
    li a3, -1
    mv a5, a1
    add a0, a1, a2
1:
    beq a5, a0, 3f
2:
    lw a4, -8(zero)
    bne a4, a3, 2b
    lbu a4, 0(a5)
    sw a4, -8(zero)
    addi a5, a5, 1
    j 1b
3:
    mv a0, a2
    jr a7
.data
.balign 16
dat:
# [1:6] str_hello
# [1:18] i8[41]
.ascii "\nwelcome to adventure #6\n    type 'help'\n"
# [2:9] str_uc
# [2:18] i8[4]
.ascii "u c "
# [3:6] str_exits
# [3:18] i8[7]
.ascii "exits: "
# [4:5] str_prompt
# [4:18] i8[3]
.ascii " > "
# [5:9] str_nl
# [5:18] i8[1]
.ascii "\n"
# [6:6] str_erase
# [6:18] i8[3]
.ascii "\010 \010"
# [8:5] str_not_understood
# [8:26] i8[14]
.ascii "not understood"
# [10:5] str_action_look
# [10:23] i8[1]
.ascii "l"
# [11:5] str_action_go
# [11:21] i8[2]
.ascii "go"
# [69:5] link_names
# [69:18] name[1024]
# [70:1] [0]
# [70:7] i8[16]
.ascii "none"
# [70:7] zero remaining array
.rept 12
.byte 0
.endr
# [70:15] i8
.rept 1
.byte 4
.endr
# [69:18] pad 1023 'name' of size 17
.zero 17391
# [99:5] rooms
# [99:13] room[128]
# [100:1] [0]
# [101:11] i8[16]
.ascii "roome"
# [101:11] zero remaining array
.rept 11
.byte 0
.endr
# [101:20] i8
.rept 1
.byte 5
.endr
# [102:11] i8[127]
.ascii "u r in roome"
# [102:11] zero remaining array
.rept 115
.byte 0
.endr
# [102:27] i8
.rept 1
.byte 12
.endr
# [103:11] i8[127]
.ascii "todo: find an exit"
# [103:11] zero remaining array
.rept 109
.byte 0
.endr
# [103:33] i8
.rept 1
.byte 18
.endr
# [104:1] padding 1 B
.zero 1
# [104:11] i16[32]
.rept 1
.half 0
.endr
.rept 31
.half 0
.endr
# [104:18] i16
.rept 1
.half 1
.endr
# [105:1] link[8]
# [105:11] [0]
# [105:12] i16
.rept 1
.half 0
.endr
# [105:15] i16
.rept 1
.half 0
.endr
# [105:18] i16
.rept 1
.half 0
.endr
# [105:1] pad 7 'link' of size 6
.zero 42
# [105:24] i8
.rept 1
.byte 1
.endr
# [100:1] zero remaining fields: 129 B
.zero 129
# [99:13] pad 127 'room' of size 518
.zero 65786
# [109:5] entities
# [109:16] entity[32]
# [110:1] [0]
# [110:9] i8[16]
.ascii "me"
# [110:9] zero remaining array
.rept 14
.byte 0
.endr
# [110:15] i8
.rept 1
.byte 2
.endr
# [110:20] padding 1 B
.zero 1
# [110:20] i16
.rept 1
.half 0
.endr
# [110:1] zero remaining fields: 2048 B
.zero 2048
# [109:16] pad 31 'entity' of size 2068
.zero 64108
# [113:5] entities_len
# [113:20] i32
.rept 1
.word 1
.endr
# [144:5] str_went
# [144:16] i8[5]
.ascii "went\n"
dat.end:
.bss
.balign 16
vars:
.zero 131072
vars.end:
# free named register s0

#   removed jumps to next code: 13
#    removed unreachable jumps: 0
# removed same target branches: 0
# inverted branches over jumps: 5
#            max frames in use: 12
#              dat var padding: 11 B
#                max vars size: 136 B
