#pragma once
// reviewed: 2025-09-28

#include <memory>
#include <ostream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "compiler_exception.hpp"
#include "statement.hpp"
#include "stmt_def_const.hpp"
#include "stmt_def_func.hpp"
#include "stmt_def_type.hpp"
#include "toc.hpp"
#include "tokenizer.hpp"
#include "unary_ops.hpp"

class program final {
    static constexpr size_t stack_and_data_alignment_{16};

    // built-in types
    type type_void{"void", 0, true};
    type type_i64{"i64", toc::size_qword, true};
    type type_i32{"i32", toc::size_dword, true};
    type type_i16{"i16", toc::size_word, true};
    type type_i8{"i8", toc::size_byte, true};
    type type_bool{"bool", toc::size_byte, true};

    std::vector<std::unique_ptr<statement>> statements_;
    toc tc_; // table of contents
    size_t stack_size_{};

  public:
    program(const std::string_view source, const size_t stack_size,
            const bool bounds_check_upper, const bool bounds_check_lower,
            const bool bounds_check_with_line)
        : tc_{source, bounds_check_upper, bounds_check_lower,
              bounds_check_with_line},
          stack_size_{stack_size} {

        // create a placeholder token to use with 'toc' functions
        const token prgtk{};

        // add built-in assembler calls
        tc_.add_func(prgtk, "mov", type_void, nullptr);
        tc_.add_func(prgtk, "syscall", type_void, nullptr);

        // add built-in types
        tc_.add_type(prgtk, type_i64);
        tc_.add_type(prgtk, type_i32);
        tc_.add_type(prgtk, type_i16);
        tc_.add_type(prgtk, type_i8);
        tc_.add_type(prgtk, type_bool);
        tc_.add_type(prgtk, type_void);

        // set defaults
        tc_.set_type_void(type_void);
        tc_.set_type_bool(type_bool);
        tc_.set_type_default(type_i64);

        tc_.enter_block();

        tokenizer tz{source};
        while (true) {
            const token tk{tz.next_token()};
            if (tk.is_empty()) {
                if (not tz.is_eos()) {
                    throw compiler_exception{tk, "unexpected character"};
                }
                break;
            }
            if (tk.is_text("func")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_func>(tc_, tk, tz));
            } else if (tk.is_text("type")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_type>(tc_, tk, tz));
            } else if (tk.is_text("const")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_const>(tc_, tk, tz));
            } else if (tk.is_text("dat")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_dat>(tc_, tk, tz));
            } else if (tk.is_text("var")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_var>(tc_, tk, tz));
            } else if (tk.text().starts_with("#")) {
                statements_.emplace_back(
                    std::make_unique<stmt_comment>(tc_, unary_ops{}, tk, tz));
            } else {
                throw compiler_exception{
                    tk, std::format("unexpected keyword '{}'", tk.text())};
            }
        }

        tc_.exit_block();

        assert_functions_set_return_value(tc_.get_func_defs());
    }

    auto source_to(std::ostream& os) const -> void {
        for (const std::unique_ptr<statement>& st : statements_) {
            st->source_to(os);
        }
    }

    auto compile(toc& tc, x86& x, const size_t indent) const -> void {
        x.println(";\n; generated by baz\n;\n\ndefault rel\n");
        x.println(
            "section .bss.stack nobits\nalign {}\nstk:\nstk resb {}\nstk.end:",
            std::format("{}", stack_and_data_alignment_),
            std::format("{}", stack_size_));
        x.println("\nsection .text\nbits 64\nglobal _start\n_start:\n");
        x.println("; initialize stack pointer\nmov rsp, dat.end\n\n;\n; "
                  "program\n;\n");

        tc.enter_block();

        for (const std::unique_ptr<statement>& st : statements_) {
            st->compile(tc, x, indent, ident_info::make_empty());
        }
        const stmt_def_func& func_main{tc.get_func_or_throw(token{}, "main")};

        x.println();

        x.label(0, "main");
        tc.enter_func("main", {});
        func_main.code().compile(tc, x, indent, ident_info::make_empty());
        tc.exit_func("main");

        tc.exit_block();

        x.println("    ; system call: exit 0");
        x.println("    mov rax, 60");
        x.println("    mov rdi, 0");
        x.println("    syscall");
        x.println();
        if (tc.is_bounds_check_upper() or tc.is_bounds_check_lower()) {
            if (not tc.is_bounds_check_with_line()) {
                x.println();
                x.println("panic_bounds:");
                x.println("    ; system call: exit 255");
                x.println("    mov rax, 60");
                x.println("    mov rdi, 255");
                x.println("    syscall");
            } else {
                x.println("panic_bounds:");
                x.println(";   print message to stderr");
                x.println("    mov rax, 1");
                x.println("    mov rdi, 2");
                x.println("    lea rsi, [msg_panic]");
                x.println("    mov rdx, msg_panic_len");
                x.println("    syscall");
                x.println(";   line number is in `rbp`");
                x.println("    mov rax, rbp");
                x.println(";   convert to string");
                x.println("    lea rdi, [num_buffer + 19]");
                x.println("    mov byte [rdi], 10");
                x.println("    dec rdi");
                x.println("    mov rcx, 10");
                x.println(".convert_loop:");
                x.println("    xor rdx, rdx");
                x.println("    div rcx");
                x.println("    add dl, '0'");
                x.println("    mov [rdi], dl");
                x.println("    dec rdi");
                x.println("    test rax, rax");
                x.println("    jnz .convert_loop");
                x.println("    inc rdi");
                x.println(";   print line number to stderr");
                x.println("    mov rax, 1");
                x.println("    mov rsi, rdi");
                x.println("    lea rdx, [num_buffer + 20]");
                x.println("    sub rdx, rdi");
                x.println("    mov rdi, 2");
                x.println("    syscall");
                x.println(";   exit with error code 255");
                x.println("    mov rax, 60");
                x.println("    mov rdi, 255");
                x.println("    syscall");
                x.println("section .rodata");
                x.println("    msg_panic: db 'panic: bounds at line '");
                x.println("    msg_panic_len equ $ - msg_panic");
                x.println("section .bss");
                x.println("    num_buffer: resb 21");
            }
        }

        // data section
        x.println("\nsection .data\nalign {}\ndat:",
                  std::format("{}", stack_and_data_alignment_));

        for (const statement* stmt : tc.get_data() | std::views::reverse) {
            stmt->compile_data(tc, x);
        }

        x.println("dat.end:");
    }

    auto build(std::ostream& os) -> void {
        x86 x{os, tc_.source()};
        x.set_type_default(type_i64);
        x.set_builtin_types(type_i64, type_i32, type_i16, type_i8, type_bool);
        compile(tc_, x, 0);
        x.finish();
        tc_.finish(os);
    }

    static auto assert_functions_set_return_value(
        const std::span<const stmt_def_func* const>& funcs) -> void {

        for (const stmt_def_func* f : funcs) {
            const std::optional<func_return_info> ret_info{f->returns()};
            if (not ret_info) {
                continue;
            }
            if (not f->code().is_var_set(ret_info->ident_tk.text())) {
                throw compiler_exception(
                    f->tok(),
                    "function may return without setting its return value");
            }
            f->code().assert_no_ub_for_var(ret_info->ident_tk.text());
        }
    }
};
