#pragma once
// reviewed: 2025-09-28

#include <memory>
#include <ostream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "compiler_exception.hpp"
#include "statement.hpp"
#include "stmt_def_const.hpp"
#include "stmt_def_func.hpp"
#include "stmt_def_type.hpp"
#include "toc.hpp"
#include "tokenizer.hpp"
#include "unary_ops.hpp"

class program final {
    // built-in types
    type type_void{"void", 0, true};
    type type_i64{"i64", toc::size_qword, true};
    type type_i32{"i32", toc::size_dword, true};
    type type_i16{"i16", toc::size_word, true};
    type type_i8{"i8", toc::size_byte, true};
    type type_bool{"bool", toc::size_byte, true};

    std::vector<std::unique_ptr<statement>> statements_;
    toc tc_; // table of contents
    size_t stack_size_{};

  public:
    program(const std::string_view source, const size_t stack_size,
            const bool bounds_check_upper, const bool bounds_check_lower,
            const bool bounds_check_with_line)
        : tc_{source, bounds_check_upper, bounds_check_lower,
              bounds_check_with_line},
          stack_size_{stack_size} {

        // create a placeholder token to use with 'toc' functions
        const token prgtk{};

        // add built-in assembler calls
        tc_.add_func(prgtk, "mov", type_void, nullptr);
        tc_.add_func(prgtk, "syscall", type_void, nullptr);

        // add built-in types
        tc_.add_type(prgtk, type_i64);
        tc_.add_type(prgtk, type_i32);
        tc_.add_type(prgtk, type_i16);
        tc_.add_type(prgtk, type_i8);
        tc_.add_type(prgtk, type_bool);
        tc_.add_type(prgtk, type_void);

        // set defaults
        tc_.set_type_void(type_void);
        tc_.set_type_bool(type_bool);
        tc_.set_type_default(type_i64);

        tc_.enter_block();

        tokenizer tz{source};
        while (true) {
            const token tk{tz.next_token()};
            if (tk.is_empty()) {
                if (not tz.is_eos()) {
                    throw compiler_exception{tk, "unexpected character"};
                }
                break;
            }
            if (tk.is_text("func")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_func>(tc_, tk, tz));
            } else if (tk.is_text("type")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_type>(tc_, tk, tz));
            } else if (tk.is_text("const")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_const>(tc_, tk, tz));
            } else if (tk.is_text("dat")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_dat>(tc_, tk, tz));
            } else if (tk.is_text("var")) {
                statements_.emplace_back(
                    std::make_unique<stmt_def_var>(tc_, tk, tz));
            } else if (tk.text().starts_with("#")) {
                statements_.emplace_back(
                    std::make_unique<stmt_comment>(tc_, unary_ops{}, tk, tz));
            } else {
                throw compiler_exception{
                    tk, std::format("unexpected keyword '{}'", tk.text())};
            }
        }

        tc_.exit_block();

        assert_functions_set_return_value(tc_.get_func_defs());
    }

    auto source_to(std::ostream& os) const -> void {
        for (const std::unique_ptr<statement>& st : statements_) {
            st->source_to(os);
        }
    }

    auto compile(toc& tc, x86& x, const size_t indent) const -> void {
        std::println(x.os, ";\n; generated by baz\n;\n\ndefault rel\n");
        std::println(x.os, "section .bss\nstk resd {}\nstk.end:",
                     std::to_string(stack_size_));
        std::println(x.os, "\nsection .text\nbits 64\nglobal _start\n_start:\n");
        std::println(x.os, "; copy data to stack");
        std::println(x.os, "lea rsi, [dat]");
        std::println(x.os, "lea rdi, [stk.end]");
        std::println(x.os, "sub rdi, dat.len");
        std::println(x.os, "mov rcx, dat.len");
        std::println(x.os, "cld");
        std::println(x.os, "rep movsb\n");

        std::println(x.os, "; initialize stack pointer\nmov rsp, stk.end\n\n;\n; "
                         "program\n;\n");

        tc.enter_block();
        for (const std::unique_ptr<statement>& st : statements_) {
            st->compile(tc, x, indent, toc::make_ident_info_empty());
        }
        const stmt_def_func& func_main{tc.get_func_or_throw(token{}, "main")};
        std::println(x.os);
        x86::label(tc, x.os, 0, "main");
        tc.enter_func("main", {});
        func_main.code().compile(tc, x, indent, toc::make_ident_info_empty());
        tc.exit_func("main");
        tc.exit_block();

        std::println(x.os, "    ; system call: exit 0");
        std::println(x.os, "    mov rax, 60");
        std::println(x.os, "    mov rdi, 0");
        std::println(x.os, "    syscall");
        std::println(x.os);
        if (tc.is_bounds_check_upper() or tc.is_bounds_check_lower()) {
            if (not tc.is_bounds_check_with_line()) {
                std::println(x.os);
                std::println(x.os, "panic_bounds:");
                std::println(x.os, "    ; system call: exit 255");
                std::println(x.os, "    mov rax, 60");
                std::println(x.os, "    mov rdi, 255");
                std::println(x.os, "    syscall");
            } else {
                std::println(x.os, "panic_bounds:");
                std::println(x.os, ";   print message to stderr");
                std::println(x.os, "    mov rax, 1");
                std::println(x.os, "    mov rdi, 2");
                std::println(x.os, "    lea rsi, [msg_panic]");
                std::println(x.os, "    mov rdx, msg_panic_len");
                std::println(x.os, "    syscall");
                std::println(x.os, ";   line number is in `rbp`");
                std::println(x.os, "    mov rax, rbp");
                std::println(x.os, ";   convert to string");
                std::println(x.os, "    lea rdi, [num_buffer + 19]");
                std::println(x.os, "    mov byte [rdi], 10");
                std::println(x.os, "    dec rdi");
                std::println(x.os, "    mov rcx, 10");
                std::println(x.os, ".convert_loop:");
                std::println(x.os, "    xor rdx, rdx");
                std::println(x.os, "    div rcx");
                std::println(x.os, "    add dl, '0'");
                std::println(x.os, "    mov [rdi], dl");
                std::println(x.os, "    dec rdi");
                std::println(x.os, "    test rax, rax");
                std::println(x.os, "    jnz .convert_loop");
                std::println(x.os, "    inc rdi");
                std::println(x.os, ";   print line number to stderr");
                std::println(x.os, "    mov rax, 1");
                std::println(x.os, "    mov rsi, rdi");
                std::println(x.os, "    lea rdx, [num_buffer + 20]");
                std::println(x.os, "    sub rdx, rdi");
                std::println(x.os, "    mov rdi, 2");
                std::println(x.os, "    syscall");
                std::println(x.os, ";   exit with error code 255");
                std::println(x.os, "    mov rax, 60");
                std::println(x.os, "    mov rdi, 255");
                std::println(x.os, "    syscall");
                std::println(x.os, "section .rodata");
                std::println(x.os, "    msg_panic: db 'panic: bounds at line '");
                std::println(x.os, "    msg_panic_len equ $ - msg_panic");
                std::println(x.os, "section .bss");
                std::println(x.os, "    num_buffer: resb 21");
            }
        }

        // data section
        std::println(x.os, "\nsection .rodata\ndat:");
        for (const statement* stmt : tc.get_data() | std::views::reverse) {
            stmt->compile_data(tc, x);
        }
        std::println(x.os, "dat.len equ $ - dat");
    }

    auto build(std::ostream& os) -> void {
        x86 x{os};
        compile(tc_, x, 0);
        tc_.finish(os);
    }

    static auto assert_functions_set_return_value(
        const std::span<const stmt_def_func* const>& funcs) -> void {

        for (const stmt_def_func* f : funcs) {
            const std::optional<func_return_info> ret_info{f->returns()};
            if (not ret_info) {
                continue;
            }
            if (not f->code().is_var_set(ret_info->ident_tk.text())) {
                throw compiler_exception(
                    f->tok(),
                    "function may return without setting its return value");
            }
            f->code().assert_no_ub_for_var(ret_info->ident_tk.text());
        }
    }
};
